### ISSUE TITLE
Homepage featured venues

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#10]
As a customer visiting the Club Soda Guide homepage,
I'd like to see a list of top venues,
So I can get an idea of what a good alcohol-free / low alcohol offering looks like.

## Acceptance Criteria
+ [x] Venues marked as 'favourites' (#75) appear in the venue slots on the homepage
+ [x] Limited to 4 venues
+ [x] Once 4 venues limit has been reached, ignore other 'favourited' venues

(Note: Limits above agreed in sprint 3 planning session)

**Comment by iteles** [comment]
Flagged as favourites by CS admins #75

**Comment by iteles** [comment]
![image](https://user-images.githubusercontent.com/4185328/49111802-0dc11880-f289-11e8-9ec7-b7f8af04626a.png)
