### ISSUE TITLE
Venue Signup tweaks

### ISSUE THREAD

**Issue by Danwhy** [club-soda/club-soda-guide#101]
A few changes to make to the venue signup page before deployment:

- [x] Lookup postcode moved to correct location
- [x] Replace 'I can't find my product' with text on click (hover on desktop, focus on mobile)
- [x] Remove 'claim venue' from venue page (will be dealt with in #30 later on)
- [x] 'sample/coming soon' map copy
- [x] Add brand to drink card
- [x] Add if statement for venue phone number to either add it or display it.

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/46485933-96c15380-c7f4-11e8-875d-73129b6b7fed.png)

**Comment by iteles** [comment]
👍
