### ISSUE TITLE
Content for homepage

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#104]
@jussi-club-soda You mentioned in our sprint planning session yesterday that you had some content changes for the homepage/landing page.

Would you be able to please send those through to us, along with a confirmation of which version of the landing page designs you settled on to make sure we're all on the same page please?

**Comment by Cleop** [comment]
**Other content questions for the landings page:**

- What images would you like for:
  - the hero image at the top?
  - the nominate venue banner image
  - the sign up to newsletter banner image
  - the footer banner image
Can you please share the relevant assets with us?

- How would you like the drink type buttons to stack on mobile? Would putting displaying them 2 to a row work, in 3 rows? Or are they not so important and so they shouldn't show at all on mobile or perhaps they should show somewhere else? If you remind us of the name of that site that you had seen something similar on then I'd be happy to look at how they adapt their designs for mobile.

![image](https://user-images.githubusercontent.com/16775804/46664441-f636af00-cbb8-11e8-90be-ce21fdcf1c49.png)

**Comment by jussi-club-soda** [comment]
Laura should have shared the updated front page design with @iteles ? I think I'll need to dig out the hi-res versions of the images too?

@Cleop Drink type buttons - yes I'd like them on mobile too! This was our "inspiration": https://demos.pixelgrade.com/listable/

**Comment by jussi-club-soda** [comment]
Clare's wireframe version with new images (text in this is still the old version - Laura has sent @iteles an updated Sketch file)
![homepage with assets](https://user-images.githubusercontent.com/43003062/46852950-a0e6e180-cdf4-11e8-9665-b14e1ce5cb33.jpg)

**Comment by jussi-club-soda** [comment]
Top image
![homepage top](https://user-images.githubusercontent.com/43003062/46852981-b65c0b80-cdf4-11e8-8e04-f2ca8705b16d.jpg)

**Comment by jussi-club-soda** [comment]
Middle image
![homepage middle](https://user-images.githubusercontent.com/43003062/46853003-c83dae80-cdf4-11e8-9939-de304dd23478.jpg)

**Comment by jussi-club-soda** [comment]
Bottom 
![homepage bottom](https://user-images.githubusercontent.com/43003062/46853043-e3a8b980-cdf4-11e8-8048-e30dabb858c9.jpg)
image

**Comment by jussi-club-soda** [comment]
Oh and the "nominate a venue" strip is taken from this one (the original image is over 10Mb so couldn't upload it - let me know if you need it via Dropbox!):

![nominate venue image](https://user-images.githubusercontent.com/43003062/46853579-772eba00-cdf6-11e8-8c67-8dad99d71ef1.jpg)

**Comment by iteles** [comment]
@Cleop Some small text copy changes from the original:
![image](https://user-images.githubusercontent.com/4185328/47017848-3fec4000-d14b-11e8-8fdf-8d89fa1bb9e0.png)

![image](https://user-images.githubusercontent.com/4185328/47017874-50041f80-d14b-11e8-9bf5-da30b6fbe62b.png)

![image](https://user-images.githubusercontent.com/4185328/47017931-6d38ee00-d14b-11e8-9910-924ec0185424.png)

**Comment by jussi-club-soda** [comment]
@Cleop @iteles Now that we've made changes to the drinks database categories, I'm afraid one of the six buttons here would need to change too... Under the "Explore all drinks" text:

"Spirits & Botanicals"  is now "Spirits & Premixed"

**Comment by jussi-club-soda** [comment]
All good, the only thing still to do is the 3 blocks at the bottom: links to static pages, drinks, and venues.

**Comment by jussi-club-soda** [comment]
I think the last bits of this are now in #262 so closing this issue.
