### ISSUE TITLE
Drinks and Brands Schema

### ISSUE THREAD

**Issue by Cleop** [club-soda/club-soda-guide#105]
**These are the fields from the airtable brands table with types/ examples:** 

| Column Name    | Type          | Example                                                         |
|----------------|---------------|-----------------------------------------------------------------|
| Brand          | String        | Big Drop                                                        |
| Type | List [String] | AF Beer                                                         |
| Style   | String        | Lager                                                           |
| Products       | List [String] | Sour, Spiced Ale, Lager                                         |
| Member         | Bool          | True                                                            |
| Description    | String        | "Sweet malt and a soft mouthfeel with citrus and floral notes." |
| No of Products | Int           | 6                                                               |
| ABV            | Float         | 0.0%                                                            |
| Website        | String        | https://www.bigdropbrew.com/                                    |

From the fields in the airtable we will split them into 4 tables. Drinks, brands and then drinks - brands table and drinks - drink categories/ sub categories

### Brands

| Column Name    | Type          | Example                                                                                                                                    |
|----------------|---------------|--------------------------------------------------------------------------------------------------------------------------------------------|
| Brand          | String        | Big Drop                                                                                                                                   |
| Member         | Bool          | True                                                                                                                                       |
| Brand Description    | String        | Seedlip is the world’s first distilled non-alcoholic spirit, solving the ever-growing dilemma of ‘what to drink when you’re not drinking’. |
| Brand logo     | String        | (Members only)                                                                                                                             |
| Website        | String        | https://www.bigdropbrew.com/                                                                                                               |

### Drinks

| Column Name       | Type   | Example                                                                                      |
|-------------------|--------|----------------------------------------------------------------------------------------------|
| Product Name      | String | Big Drop                                                                                     |
| Drink Description | String | With a backbone of 8 different speciality malts, Nanny State will tantalise your taste buds. |
| ABV               | Float  | 0.0%                                                                                         |

We will then connect the brands and drinks tables with their corresponding Ids. There will also be a table for drink categories and drink sub categories for their many to many relationships with the drinks ids. We'll also need to agree where tags come in e.g. vegan, gf etc.

**Comment by jussi-club-soda** [comment]
A bookmark here for me to get back to this later!!

**Comment by iteles** [comment]
@Cleop @Danwhy Starter drinks data (16 drinks) here, from Jussi: https://drive.google.com/drive/u/1/folders/1auziXzdfkRQO1MWJt7AzAZrdfBak6glM

**Comment by Cleop** [comment]
@jussi-club-soda - please can you confirm which fields are mandatory/optional so that when we add them to the code this is being considered?

**Comment by jussi-club-soda** [comment]
I've emailed @iteles an updated dummy data file with answers to @Cleop questions too!

**Comment by iteles** [comment]
Schema now needs to be updated as per https://github.com/club-soda/club-soda-guide/issues/61#issuecomment-432580004

**Comment by jussi-club-soda** [comment]
With my apologies for making this more complicated than it should have been...

**Comment by jussi-club-soda** [comment]
@iteles @Cleop can we also do a bit of "future proofing" here? = Add some fields to the database we aren't using in this iteration but would like to add in future (eg vegan? gluten-free?)? Unless you think there's no need and that it would have any negative impacts (eg taking up resources for no good reason).
Also, I think there was a couple of things in Harry's designs on the drinks listing page that aren't in my dummy data (social media handles etc) which would also be good to include.

**Comment by Cleop** [comment]
Notes to self for things to add:
- social media handles etc from drinks/brand page (venue page too?)
- Check airtable for fields on online stockists
- future fields

**Comment by Cleop** [comment]
### Drinks

| Column Name       | Type   | Example                                                                                      |
|-------------------|--------|----------------------------------------------------------------------------------------------|
| Product Name      | String | Pale Ale                                                                                   |
| Drink Description | String | With a backbone of 8 different speciality malts, Nanny State will tantalise your taste buds. |
| ABV               | Float  | 0.0%                                                                                         |
| Image* | String |https://www.beerhawk.co.uk/media/catalog/product/cache/c687aa7517cf01e65c009f6943c2b1e9/b/i/bigdrop_pale.png |
|Ingredients*|String|Water, barley, oats, wheat, hops, yeast|

* indicates a new field in comparison to the tables outlined at the top of this issue

**Comment by jussi-club-soda** [comment]
@Cleop Anja has been working on the Airtable, I've been working on something else...

Ingredients - this is something Anja has collected for quite few drinks, but it isn't in Harry's designs anywhere? Could we still squeeze it in somewhere?

Does your schema above include 
- the "where to buy info" fields: 3 online shops (URLs if available), retailers, wholesalers
- the second drink type (eg wine-red, wine-white, wine-sparkling)

Images: I think Clare added a couple of links when she set up the Airtable in the first place, but we haven't collected these. Do you have the details for what the various image requirements are, we could try to gather some of them to add as soon as we can, to make the site look a bit nicer from day 1?

**Comment by Cleop** [comment]
I believe Harry had them on the back of the drink cards underneath the description. However I think that if they only have them for a few, perhaps we should hold off on displaying them for now. But the column will be included so you can continue adding to them.

- 'Where to buy info' will be recorded in the Venues table which is what I meant when I said:
> Online stockists will be listed as 'Venues'
They don't require any new columns as venues already have a name and website.

- By second drink type I think you're referring to the airtable column 'style'? There are 2 columns relating to drink category: 'type' and 'style'. Type is more general and then style is more specific. Is my thinking right?

I will come back to you on the details for images.

**Comment by jussi-club-soda** [comment]
@Cleop 
Ingredients - yes we think of the best place for them later.

"Online stockists will be listed as venues" - is that just a technical thing, or will they then also show up in searches etc? We were at one point hoping to have direct URLs to products, for example rather than amazon.co.uk, we could have https://www.amazon.co.uk/Seedlip-Spice-Non-alcoholic-Spirit-70cl/dp/B01FK78MZC/ with also our affiliate links added (though I think we can add that to just amazon.co.uk too)

"Second drink type" - yes you are right! Style is nested under Type.

**Comment by Cleop** [comment]
@jussi-club-soda for the drinks images requirements:

Drinks images must be in a 9:16 ratio as closely sized to 900 x 1600px as possible. 

Acceptable formats are jpg and png.

**Comment by jussi-club-soda** [comment]
think this is all fine now?
