### ISSUE TITLE
Creating & editing brands and drinks

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#107]
Jussi the Club Soda admin would like to be able to add new brands and drinks to the database, when he discovers them or when they are launched to the market. And he would also like to edit all existing database entries to fix any errors and do any updates he wants to.

Inputs to include:
- [x] the fields listed in #105  
- [x] photos of bottles for each drink https://github.com/club-soda/club-soda-guide/issues/105#issuecomment-439872589
- [x] banner photo for brand (if paid-up member)
- [x] longer description (if paid-up member)
- [x] social media handles, website URL (if paid-up member)
- [ ] whether available in the online shops
- [x] where to buy retail
- [ ] where to buy wholesale

**Comment by iteles** [comment]
Drink image uploading is up and awaiting review.

**Comment by nelsonic** [comment]
Reviewed. merged. being deployed to "staging" ... 👍

**Comment by Danwhy** [comment]
@jussi-club-soda Image uploads for drinks has now been deployed, here are the instructions for how to upload:
https://github.com/club-soda/club-soda-guide#uploading-images

**Comment by iteles** [comment]
@Danwhy The `Show` and the `Delete` button _both_ delete the brand on my machine, no matter how carefully I try to hit 'show' instead of 'delete'!

**Comment by iteles** [comment]
@Danwhy I just added a description to Budvar and got an internal server error on saving:
1. Copy this text: `Our 700-year long tradition of brewing Budějovice beer means we take 102 days to brew and condition Budweiser Budvar. About 7 times longer than most other beers. It’s the only way to preserve our unique and unmatchable taste. This pale lager has a beautiful golden colour and rich head, its mild hop aroma balances well with the perfectly synchronised sweet-bitter taste. You will understand why it is the lager for those in the know.`  
2. Paste into description field in: https://club-soda-guide-staging.herokuapp.com/brands/d4021d5c-1d2b-429d-9f98-0fe33bc94ee4/edit
3. Press Save

**Comment by Danwhy** [comment]
It looks like the description is too long for the 'string' type in the database. We'll need to change it to 'text'

**Comment by jussi-club-soda** [comment]
Issues I've discovered:

- [ ] ABV on drinks - this field seems to want integer numbers only on the edit form? I tried to change a beer from 0.0 to 0.05 and get a "! Please enter a valid value. The two nearest valid values are 0 and 1" error message...

- [ ] Adding new drinks in https://www.clubsodaguide.com/drinks/new - "Brand" "is invalid" even though the brand exists...

**Comment by jussi-club-soda** [comment]
I believe this is all ok, retailers etc is covered elsewhere?
