### ISSUE TITLE
Nominate a venue

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#11]
As a customer visiting the Club Soda Guide homepage,
I'd like to see a block with a title and CTA, encouraging me to nominate a venue,
So I can ensure other mindful drinkers know about a great venue I've found

Clicking on button opens up a simple form with basic venue details: name, location/address, why it's a great venue.
Once filled in and submitted, send form information via email to site admin.

**Acceptance criteria:**
- [x] As in wireframe designs, a block on site home page with a CTA for the public to nominate venues to sign up to the Guide
- [x] Either an online form hosted on the website which sends an email to admins when a new submission is posted OR a link to Typeform to gather a few basic details about the nominated venue (this is our Typeform we can use: https://clubsoda.typeform.com/to/Z5sMPA)

**Comment by iteles** [comment]
@jussi-club-soda Is this issue now superseding #80?

**Comment by jussi-club-soda** [comment]
@iteles yes - I would drop #80, and have just taken the priority off it! This one (#11) is what we will be using to get customers to nominate good venues they know.

**Comment by iteles** [comment]
Looks like a `please-test` to me @Cleop  :+1:

**Comment by iteles** [comment]
@jussi-club-soda Just hit the 'Close' button under the comment box.

You'll see a lot more `please-test` issues over the course of the next 24 hours so we can begin to clear out the backlog 😊 

<img width="720" alt="screen shot 2018-12-04 at 10 48 40" src="https://user-images.githubusercontent.com/4185328/49436962-58bfbc00-f7b2-11e8-8154-0fec8f28e34d.png">

**Comment by jussi-club-soda** [comment]
Whoop! :)
