### ISSUE TITLE
Newsletter Sign Up

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#12]
As a customer visiting the Club Soda Guide homepage,
I'd like to sign up to the newsletter,
so I can stay up to date with exciting new venues and products.

Clicking on button opens up a simple form: name, email address, GDPR compliant tick box to opt-in.
Once form filled in and submitted, API to MailChimp Club Soda Main email list.

**Comment by iteles** [comment]
Simplest implementation to be discussed.

**Comment by jussi-club-soda** [comment]
fine!
