### ISSUE TITLE
Venue 'cards' for landing page and search

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#122]
Similar to #106, each venue has a 'card view'.

@jussi-club-soda The key question for us here is: can we have _one_ type of 'venue card' displayed both on the landing page _and_ in the Venues search page(s) so that we can reuse these cards in multiple locations, allowing them to fit into scope?

What information do you want to _test_ your customers need here?

I would propose we go with the landing page suggested cards for now ensuring they contain the information in the Acceptance Criteria below:
![image](https://user-images.githubusercontent.com/4185328/47385006-c7642100-d700-11e8-8ab9-f3e47fe6eab7.png)

## Acceptance Criteria
Venues cards should include the following:
+ [x] Photo of venue
+ [x] Venue name
+ [x] Venue type
+ [x] Venue Club Soda score
+ [x] Venue location/post code
+ [x] Clicking on the venue card should take the customer to the venue page

**Comment by jussi-club-soda** [comment]
@iteles that sounds fine to us!

**Comment by Cleop** [comment]
Where should the venue type appear as it's not featured on the designs @iteles / @jussi-club-soda ?

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/48481192-97420680-e804-11e8-89ac-c4245bde82a1.png)

I've moved the order around to what looked best to me, how does this look to you @jussi-club-soda?

**Comment by iteles** [comment]
There are no venues appearing in staging:
![image](https://user-images.githubusercontent.com/4185328/49040664-19460e00-f1bb-11e8-8c4a-6d79c463d562.png)

It's highly probable that this is because there are no _favourited_ venues in the data itself yet. 

https://github.com/club-soda/club-soda-guide/issues/75#issuecomment-441788296 will need to be fixed before this can be fully implemented.

@simonlab Are you able to test this is working by manually altering a couple of values in staging db in the meantime to force 4 venues to be 'favourited'? Ideally, if there are any issues here we can catch them asap. All the commits should be linked to this issue.

**Comment by SimonLab** [comment]
Tested on localhost by editing the venues:
![image](https://user-images.githubusercontent.com/6057298/49044592-30d6c400-f1c6-11e8-83d4-bc160740ceb3.png)

However I think the ranking needs to be updated to display the venues with the highest scores first

**Comment by iteles** [comment]
@SimonLab Could you please also add a couple of pictures to the venues in localhost and check those also appear (instead of the default green rectangles) please?

**Comment by SimonLab** [comment]
I manage to upload an image for a venue on localhost. However I'm not sure if the image needs to have a specific size, @Danwhy @iteles do you if there are any limits for the images? We can see that the text is on top of the image in this case:
![image](https://user-images.githubusercontent.com/6057298/49047304-f02f7880-f1ce-11e8-9aa0-798f0840f729.png)

**Comment by iteles** [comment]
![image](https://user-images.githubusercontent.com/4185328/49111802-0dc11880-f289-11e8-9ec7-b7f8af04626a.png)

Only thing left to do here is make the whole card, not just the title clickable.
