### ISSUE TITLE
Venue description on the venue page

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#128]
As venue owner/manager, I would like to be able to describe my venue to the site user in the best possible way - therefore, the venue description field needs to be able to accommodate enough text.

**Acceptance criteria:**
- [x] Venue description field in the listing form needs to be able to contain XXX characters 
- [x] Venue description should be able to process '&' characters, see #250

**Comment by jussi-club-soda** [comment]
I've left the exact length of the field open - do we need to set up an upper limit here? In practice, most venues wouldn't need more than a few paragraphs of text (though there may always be some who want to write a long essay....)

**Comment by Cleop** [comment]
Relates to https://github.com/dwyl/fields/issues/20

**Comment by iteles** [comment]
@jussi-club-soda Suspect we'll have some more acceptance criteria coming out of this testing!

**Comment by jussi-club-soda** [comment]
Ok, I'm not sure what the status of this is @iteles ? *Confused face*

**Comment by ctrembath** [comment]
I've updated the acceptance criteria for this card to include #250.

**Comment by iteles** [comment]
@Cleop Venue description field currently still presenting as an `input` field rather than a text area:
![image](https://user-images.githubusercontent.com/4185328/50180533-c404a480-0301-11e9-80b3-ac4dca4e8c58.png)

**Comment by Cleop** [comment]
Strange @iteles - the two places in the code look as I would expect:

The venue migration lists it as type 'text' as opposed to 'string':
 ` add(:description, :text)`

And the schema has it as the 'fields' type:
` field(:description, Fields.DescriptionPlaintextUnlimited)`

And @Danwhy 's documentation says:
> For example, Fields.DescriptionPlaintextUnlimited.input_type returns :textarea.
>   def input_type, do: :textarea

I will need to look into this further to work out why it's not working yet...

**Comment by Cleop** [comment]
@Danwhy spotted that this was because we were calling `render_autoform`, where it needed to be `custom_render_autoform`. It is now displaying as it should be:

![image](https://user-images.githubusercontent.com/16775804/50629153-58dae500-0f33-11e9-8a57-c336be519802.png)
