### ISSUE TITLE
"Find venues near me" functionality

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#129]
As a site user, I'd like to be able to find good venues in my local area.

**Acceptance criteria:**
- [x] The website has a "find venues near me" button or link
- [x] The site can identify the users location (and asks for permission for this if needed)
- [x] Pressing the button/link displays a list (ordered by distance from user) or a map of venues on the Guide

**Comment by iteles** [comment]
Note: likely this button should appear both on the homepage and on the venues page.
Linked to #6

**Comment by RobStallion** [comment]
Have been looking into possible solutions for this issue.

As you cannot calculate distance between two postcodes without using an api which converting the addresses to latitudes and longitudes (geocoding) first seems to make most sense.

Using the google maps api does not seem like the best idea. We would have to withdraw every venue location from the database, send them all to the front end, individually geocode each one and then filter those geocodes by calculating the distance from the users location and removing the all locations 'x' distance away. 
This seems too 'expensive' in terms of sending data back and forth and the number of api calls the app would have to make. Also in terms of how much it would cost to use an api to geocode that many addresses so often. This approach would mean that every venue address would have to be geocoded for every single request from a user. 

I think a better solution may be to store the lat-long values in the database when we add a venue. We could make the api call to get the lat-long value once the venue has been created and save them with the rest of the info. This way the user experience would not be effected and we would only have to make the API call to geocode the address once per address. 
(Found [this](https://postcodes.io/) awesome API that batch geocodes postcodes for the uk. We could use this to get the lat-long values for all the address currently in the db if we decided to go this route)

Once we have the lat-long values stored, we can use them to calculate the distance from one to the next. The math is not the most straightforward thing I have ever seen...
```
Haversineformula: | a = sin²(Δφ/2) + cos φ1 ⋅ cos φ2 ⋅ sin²(Δλ/2)
-- | --
c = 2 ⋅ atan2( √a, √(1−a) )
d = R ⋅ c
where | φ is latitude, λ is longitude, R is earth’s radius (mean radius = 6,371km);note that angles need to be in radians to pass to trig functions!
```

but I have seen it converted into js and we should be able to replicate something like this...
```javascript
var R = 6371e3; // metres
var φ1 = lat1.toRadians();
var φ2 = lat2.toRadians();
var Δφ = (lat2-lat1).toRadians();
var Δλ = (lon2-lon1).toRadians();

var a = Math.sin(Δφ/2) * Math.sin(Δφ/2) +
        Math.cos(φ1) * Math.cos(φ2) *
        Math.sin(Δλ/2) * Math.sin(Δλ/2);
var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));

var d = R * c;
```

The downside with this is that we would still have to withdraw all the data from the db before filtering. Upside is no api calls.

Ideally, if we had the lat-long values in the database, we would be able to make the db do filtering for us. The answer to [this](https://stackoverflow.com/questions/1006654/fastest-way-to-find-distance-between-two-lat-long-points) SO question has an example of using SQL db to filter by lat-long.

**Comment by RobStallion** [comment]
@nelsonic @Cleop  If either of you have any thoughts on the approaches mentioned or if you have done something similar in a different way then please let me know 👍

**Comment by RobStallion** [comment]
@nelsonic Thanks for the above.

> The Lat/Lon for all UK postcodes is publicly available:
https://github.com/dwyl/uk-postcodes-latitude-longitude-complete-csv

That is AMAZING!!!

**Comment by RobStallion** [comment]
@nelsonic Since you mentioned on the stand up that we should download the file from the original repo with a script I have seen the following in elixir...

```elixir
System.cmd("curl", ["--output", "postcode.zip", "https://raw.githubusercontent.com/dwyl/uk-postcodes-latitude-longitude-complete-csv/master/ukpostcodes.csv.zip"])
```

This creates a file called postcode.zip

We can then unzip that file with 

```elixir
:zip.unzip('postcode.zip')
```

I can currently get the file with the above commands.

Still looking into this

**Comment by RobStallion** [comment]
saw [this SO](https://stackoverflow.com/questions/30267943/elixir-download-a-file-image-from-a-url) on how to clone a file and thought it could be used as an alternative to the `System.cmd` one above. 

```elixir
%HTTPoison.Response{body: body} = HTTPoison.get!("https://raw.githubusercontent.com/dwyl/uk-postcodes-latitude-longitude-complete-csv/master/ukpostcodes.csv.zip")

File.write!("postcodes.zip", body)
```

**Comment by RobStallion** [comment]
When I use the unzip command I get the following response...
```elixir
{:ok, ['ukpostcodes.csv', '__MACOSX/._ukpostcodes.csv']}
```

It creates the file we want but is also making a directory. Not a massive issue but not sure how to avoid this at the moment.

**Comment by nelsonic** [comment]
@RobStallion we should _avoid_ pushing a zip file into the client/project Git repository because it's an externally generated "blob" of data that does not _need_ to be version-controlled.

We should have a "post-install" script either in Elixir or Node that fetches the zip file and unzips it. 
Please let me know if you are OK to write this 1-2 line script or if you need some input from me.

**Comment by RobStallion** [comment]
I took a copy of the staging db and ran the lat long script with it to add lat long to venues in the db. The following postcodes were all not found in the csv file...

```
"MK401AY postcode not fount in ets"
"TT000TT postcode not fount in ets"
"EC18HX postcode not fount in ets"
" postcode not fount in ets"
"BL90PN postcode not fount in ets"
"W11AA postcode not fount in ets"
"OL11RA postcode not fount in ets"
"SK11SA postcode not fount in ets"
"EC3M1AB postcode not fount in ets"
"E16PP postcode not fount in ets"
" postcode not fount in ets"
"TQ25HD postcode not fount in ets"
"WR12BY postcode not fount in ets"
"DY101BY postcode not fount in ets"
"GL503FF postcode not fount in ets"
```

This means that the venue will have blank values for lat long. It will not cause any errors but it means that that venue will never appear with the nearby venue search as there is no way to calculate how far away the venue is.

I will take a copy of prod and repeat this test to see if the same happens.

**Comment by nelsonic** [comment]
@RobStallion we may need to remove spaces from the postcodes in ukpostcodes.csv and create a secondary lookup/index in ETS to ensure that people can type their postcode without the space.

**Comment by RobStallion** [comment]
The following postcodes in prod were not found in the csv file...

```
"OL11RA postcode not fount in ets"
"EC3M1AB postcode not fount in ets"
"DY101BY postcode not fount in ets"
"SK11SA postcode not fount in ets"
"GL503FF postcode not fount in ets"
"BL90PN postcode not fount in ets"
"WR12BY postcode not fount in ets"
"TQ25HD postcode not fount in ets"
"E16PP postcode not fount in ets"
"MK401AY postcode not fount in ets"
"EC18HX postcode not fount in ets"
"TT000TT postcode not fount in ets"
```

Will search the db to see which venues these postcodes belong to.

**Comment by ctrembath** [comment]
This comment also applies to this issue:

https://github.com/club-soda/club-soda-guide/issues/231#issuecomment-453489036

**Comment by SimonLab** [comment]
The "use my location" text changed to "searching" when clicked (haven't manage to get screenshot as the search results appear quiet rapidly on my machine)
