### ISSUE TITLE
Space for listing a sponsor on the home page

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#131]
As Club Soda, we may be able to get sponsorship of the site from a drinks company or another sponsor. We would then need to highlight the fact on the website home page somehow.

This issue may need some discussion, and possibly a bit of designer time as well to complete. This could be a banner image straight after the hero image/search bar?

**Acceptance criteria:**
- [ ] Site admins are able to upload an image (of a specified size) on the website home page
- [ ] Site admins are able to take down the image uploaded, leading to the page returning to its previous setup/design

**Comment by Cleop** [comment]
- [ ] Set up table in the DB to save the sponsor content
- [ ] Set up a page in the admin area  where the admin can add/edit the sponsor content
- [ ] Display the content as html

**Comment by Cleop** [comment]
@jussi-club-soda - where on the landing page should the sponsor content appear?

**Comment by Cleop** [comment]
I was going to use `Fields.HtmlBody` for the type of the body field however it was filtering out classes and ids when I wanted to style my html.

**Comment by jussi-club-soda** [comment]
Ooh good question about the location @Cleop !

How about between the "Great Places for Mindful Drinkers" and the nomination block? Just so it isn't at the very bottom where nobody will see it!

**Comment by Cleop** [comment]
See the how to add a sponsor as written in the readme to test

**Comment by jussi-club-soda** [comment]
Stupid question @Cleop : is there an easy way for me to upload an image to AWS so that I can use it here? Or what's the best way to do it?

**Comment by nelsonic** [comment]
@jussi-club-soda you can drag-and drop an image in to a github comment e.g: 
![image](https://user-images.githubusercontent.com/194400/53252414-b9c2a600-36b6-11e9-846e-97a8cf350445.png)
When you see the code:
```
![image](https://user-images.githubusercontent.com/194400/53252414-b9c2a600-36b6-11e9-846e-97a8cf350445.png)
```
Simply extract the hyperlink to the image, e.g:
https://user-images.githubusercontent.com/194400/53252414-b9c2a600-36b6-11e9-846e-97a8cf350445.png

GitHub uses AWS S3 as their image host so you use it as a "Free" CDN! 😉 
But there is also another way of doing it easily if you want to have "full control" over the image in your own S3 bucket. Use: https://cyberduck.io (FREE) and use your AWS credentials to view the S3 bucket as a "folder" which you can edit.
