### ISSUE TITLE
Drink brand pages

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#132]
Admins and drink brands need pages for all drink brands on the database, as in the wireframes. The page has more details if the brand is a paid-up member of Club Soda.

Cross-references: #46 leads here / #49 & #51 relate to these pages

**Acceptance criteria:**
- [x] Every drink brand on the database has a "profile page", based on the designs in the wireframes
+ [x] Each page contains:
  + [x] Logo photo area
  + [x] Short description
  + [x] Website
  + [x] Additional description area - long description, to include a fixed size photo as well
  + [x] Drinks section containing drinks cards for the drinks that belong to that brand (follows the same design pattern as venues drink section - note: _not_ split into drink types for now)
  + [x] Places that stock this brand section, including venue cards for 4 venues that stock the brand
  + [x] External links #49 #51 
  + [x] Social media links: Instagram, Twitter, Facebook
+ [x] The page has more details (longer description, additional image, external links) for brands that are members of Club Soda (this is indicated on the database). The following are hidden _in the UI_ for non-member brands (see #47):
  + [x] Logo photo - this should be a coloured background with the name of the brand centred in white (note: #48 is an extension of this but a separate issue)
  + [x] Additional description area + picture
  + [x] Venues that stock this brand
  + [x] External links
  + [x] Social media links: Instagram, Twitter, Facebook

**Comment by jussi-club-soda** [comment]
@iteles here's a starter - do you want more details?

**Comment by iteles** [comment]
@jussi-club-soda I have added a few more details to the acceptance criteria above if you could take a look? For now I have not included the following from the designs which are things that should really come from your users and testing:
+ '1,2,3' content shortcut area
+ Social media handles/links,
+ The split of drinks into drink types

What limitations can we impose on the additional brand picture for member brands (particularly in the light that you will be inputting these at first)?

For the more popular brands, it's conceivable that dozens of venues may stock them. At the moment, the designs (and what we also discussed for the homepage) uses 4 venue cards. How would you imagine your users would use this section? From the data you've had access to before, is the brand :arrow_right: venue user journey a popular one?
Shall we reconsider the limits here?

I have also proposed for now that all brand forms (for admins to fill in) are the same and then we control what the consumer sees based on the toggle of whether a brand is a member or not.

**Comment by Cleop** [comment]
@jussi-club-soda - please can you clarify what you would like included on this page following @iteles' comment above?

Also, I couldn't determine from the issue description whether:
- social media
- external retailers
- venues that stock a brand
were for members only or all brands (or following @iteles' comment whether social media handles should be included at all)?

**Comment by iteles** [comment]
If there is no photo uploaded, we currently have a bug:

![image](https://user-images.githubusercontent.com/4185328/49112991-431b3580-f28c-11e8-8242-133797c57071.png)

It _should_ look like this:
![image](https://user-images.githubusercontent.com/4185328/49113122-95f4ed00-f28c-11e8-89a5-9cf1887300a7.png)

I also couldn't find where retailers are added.

**Comment by iteles** [comment]
@jussi-club-soda Notes on how to set up brand pages and retailers for testing: https://github.com/club-soda/club-soda-guide#brand-pages

**Comment by jussi-club-soda** [comment]
Seems fine, I'll see how this works once we have some retailers added to the live site and have a bit more data there to test things.
