### ISSUE TITLE
Homepage search bar - simple version

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#133]
As a site user, I'd like to be able to search for drinks and venues from a search box at the top of the homepage.

**Acceptance criteria:**
- [x] A search bar at the top of the home page (under a descriptive bit of text)
- [x] Typing in text and pressing enter / clicking on search icon opens a new page with search results (see issue #135 )
- [x] The search algorithm only searches within the venue names and drink brands and names (ignoring longer descriptions of venues and drinks)
- [ ] Ideally the algorithm uses fuzzy search so typos etc won't prevent relevant results coming up
- [x] Styling

(Compare to #134 for the more complex alternative version of this issue - only 1 of the 2 is needed!)

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/50093144-cda9e180-0207-11e9-920f-290fc22cf21c.png)
<img src="https://user-images.githubusercontent.com/16775804/50093203-f4681800-0207-11e9-892f-b4b2548dc3b7.png" width=150px />

**Comment by Cleop** [comment]
Is the fuzzy search acceptance criteria lower priority @jussi-club-soda - can it be separated out into another issue?

**Comment by jussi-club-soda** [comment]
I guess it is a separate thing -especially if everything else here is already complete then let's open a new issue for it?
