### ISSUE TITLE
Importing venues with drinks data included

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#140]
As an admin, I will sometimes have venue data on spreadsheet where I also know the drinks served at each venue - if there are large numbers of venues to import, it would be good to be able to import the drinks data as well, linked to each venue so there's no need to manually input this info. See attached spreadsheet as an example of such data.

[First venue signups WITH DRINKS.xlsx](https://github.com/club-soda/club-soda-guide/files/2547994/First.venue.signups.WITH.DRINKS.xlsx)

**Comment by iteles** [comment]
@jussi-club-soda This functionality was completed for developers as we agreed and documented in the dev guide here: https://github.com/club-soda/club-soda-guide#importing-data

We've now written 3 different scripts to import venues and have successfully imported venues with drinks twice.
