### ISSUE TITLE
Temporary password wall for admins

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#158]
We have an append-only log in place which guarantees that no data is ever lost (changes are appended to the database rather than overwriting the original content) and ensures we can roll back the data to a previous version at any time.

In the longer term (once the application content and main functionality is completed), users functionality will be built out into the system. 

However, site admins would like a further guarantee that in the short term, they do not need to keep an eye out for data changes as their team does not have the capacity for it at the moment and would like a 'password wall' for site admin functionality (i.e. access to the master venue, drinks and brands data).

Note: this is a short-term version of #66

**Comment by Danwhy** [comment]
This will require:

- [ ] Adding an (optional) password to the user schema
- [ ] Manually adding admin users to the database
- [ ] listing all admin pages at an `/admin` endpoint
- [ ] Implementing an auth plug that can verify logged in admins
- [ ] restricting access to `/admin` and other admin pages
- [ ] conditionally displaying the 'edit this venue' buttons/links on the `show` venue page for admins only

**Comment by Danwhy** [comment]
Updated guide for how to use admin features: https://github.com/club-soda/club-soda-guide#user-admin-guide

How to create admins (locally or on heroku): https://github.com/club-soda/club-soda-guide#creating-admin-users

**Comment by iteles** [comment]
@jussi-club-soda In order to test this you will need:
+ To read the updates to the documentation on the admin setup: https://github.com/club-soda/club-soda-guide#user-admin-guide
+ The username and pw I will share with you now

**Comment by jussi-club-soda** [comment]
Seems to work fine in staging as far as I can see!
