### ISSUE TITLE
Drinks with same name causing problems

### ISSUE THREAD

**Issue by Danwhy** [club-soda/club-soda-guide#164]
If I select a drink with a generic name that multiple drinks have, eg. Ginger Beer:
<img width="300" alt="screen shot 2018-11-27 at 14 28 37" src="https://user-images.githubusercontent.com/8939909/49088166-953e6580-f250-11e8-89db-b8fe53640ad1.png">
It works fine, but if I then unselect that drink:
<img width="300" alt="screen shot 2018-11-27 at 14 29 48" src="https://user-images.githubusercontent.com/8939909/49088221-b010da00-f250-11e8-8205-c00d3f2fa3c2.png">
Every drink with that same name is now selected for that venue. I'll look into what's happening here.

**Comment by Danwhy** [comment]
The problem is in the add drinks form: https://github.com/club-soda/club-soda-guide/blob/dc957d0b52f875df66c74f3d16be1d58567c2660/lib/cs_guide_web/templates/venue/add_drinks.html.eex#L14

We're checking if the drink is currently selected using the name, rather than the unique entry id. So when we visited the form after selecting 'Ginger Beer', the form displayed that the venue stocked every drink named 'Ginger Beer'.

**Comment by jussi-club-soda** [comment]
I can't add drinks to any venue in staging at the moment (either existing venue or a new one I've just created): always end up with a 

Page not found

error message.

**Comment by Danwhy** [comment]
Ah sorry @jussi-club-soda, the links should have `/admin` at the start of them now. I'll fix those

**Comment by jussi-club-soda** [comment]
Ok, did a quick check and I think this is fine now!
