### ISSUE TITLE
Issues, bugs, questions from Jussi

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#167]
I'll try to make this into a list of issues, bugs and questions I have, so you all can see them (fao @nelsonic , @iteles , @Cleop , @Danwhy , @SimonLab ) - they may already have been raised elsewhere too!

- [x] I uploaded a bunch of drink images (bottles) to https://club-soda-guide-staging.herokuapp.com over the weekend, but they seem to have disappeared?
- [x] The venue images: what size do they need to be to work? 
- [x] The old site had images for most if not all venues - It doesn't look like they've migrated from there? 
- [x] The venue types are not showing either on the front page or on the venue profile pages? 

- [x] Random question: what would happen if I uploaded a venue that is in Ireland? I guess it would work fine, the only possible issues could come with geolocation/map? We actually have a couple of pubs in Dublin who would like to be listed already...

~- [ ] ABV on drinks - this field seems to want integer numbers only on the edit form? I tried to change a beer from 0.0 to 0.05 and get a "! Please enter a valid value. The two nearest valid values are 0 and 1" error message...~ Moved to https://github.com/club-soda/club-soda-guide/issues/107

~- [ ] Bug with adding new drinks/brands: I've added a new brand (Eisberg) but when trying to add a drink to it, get error message next to the brand box: "is invalid"~ Moved to https://github.com/club-soda/club-soda-guide/issues/181 to keep things neat and easy to prioritise

**Comment by iteles** [comment]
@jussi-club-soda Thanks for these.

We were expecting you to have added the bottle images to production rather than staging (apologies, I should have made this much clearer to you) so we deployed a new version and wiped the staging database. We'll still have the images themselves, so we're looking into them and pulling them out.


For the venue types, I still see them on the venues themselves, e.g. https://club-soda-guide-staging.herokuapp.com/
![image](https://user-images.githubusercontent.com/4185328/49099779-34bc2200-f26a-11e8-93e4-dc8952760038.png)

But not on the front page, we'll look into that too!

**Comment by iteles** [comment]
The venue types do show on the landing page, but the venues in staging that were on the landing page didn't have venue  types attached to them.

Adding a test venue exemplifies this:

![image](https://user-images.githubusercontent.com/4185328/49111870-4234d480-f289-11e8-8833-47850df3aa3c.png)

**Comment by SimonLab** [comment]
Concerning the images for the drink, I manage to see what has been upload into S3 and I could see that around 20 images was added for the drinks on last Sunday, does this number makes sense @jussi-club-soda ?

I manage to match the drinks to their image by first searching for the drink name then adding a new entry into the `drink_image` table with the id of the drink and the S3 id of the image.

The only drink I couldn't match is "Botonique Original" as the name "Original" is not unique (so I can't determine the id of the drink)
![image](https://user-images.githubusercontent.com/6057298/49127994-6f9d7480-f2c1-11e8-82b5-b9cafffdba1a.png)

**Comment by iteles** [comment]
@jussi-club-soda The redirect #156 has just caused an interesting issue: All of the venue images were coming from the clubsodaguide.com URLs we were given and these now no longer exist:
![image](https://user-images.githubusercontent.com/4185328/49165429-149f6800-f329-11e8-8232-a2c9afb5f6ab.png)

I will check with @nelsonic to see if there is a better solution here, but in the short term, do you still have access to your WP admin dashboard? Can you still access the data without having to undo the redirect?

**Comment by jussi-club-soda** [comment]
@iteles I seem to have lost access to the old site using 46.101.87.57 too...

**Comment by jussi-club-soda** [comment]
@SimonLab yes, 20 sounds about right! the last one I can match later

**Comment by jussi-club-soda** [comment]
@iteles it looks like the venue carousel isn't showing at all in production?

**Comment by iteles** [comment]
@jussi-club-soda The data in production doesn't have any pre-favourited venues!
You can either add these or let me know which ones you would like to be on the landing page and I'll do that for you 👍

**Comment by jussi-club-soda** [comment]
Ah @iteles I see! Have now favourited 4 venues and they are showing up :)

**Comment by iteles** [comment]
Agreed with @jussi-club-soda that CS will upload the venue images manually as this will be more efficient that a one-time script given that it is difficult to maintain the relationships between the images and the venues programatically across apps.

**Comment by Cleop** [comment]
@jussi-club-soda - re Ireland. Having done a bit of research into the Irish postcode system it appears that we'd have to adjust our current postcode validation or make postcodes optional. The format of Irish postcodes (or eircodes as they're called) is different to England. Here's an example: D02 H950.

**To see more examples look at:**
https://finder.eircode.ie/#/
**Here's an article on the system:**
https://www.thejournal.ie/postcode-ireland-system-eircode-addresses-1437443-Apr2014/

**Comment by jussi-club-soda** [comment]
@Cleop thanks, interesting about the Irish postcodes! we'll have to think about this some more I guess...
