### ISSUE TITLE
use Docker for development

### ISSUE THREAD

**Issue by SimonLab** [club-soda/club-soda-guide#170]
As discuss with @Danwhy I'll create a small PR which is going to make is easier to work on the application while using Docker for development

- [x] Create Dockerfile and docker-compose.yml file
- [x] Update the database configuration for development and test

see also https://github.com/dwyl/learn-docker#docker-and-pete-stack

**Comment by nelsonic** [comment]
Hi @SimonLab thanks for opening this `technical` issue. 🔧 👍 
As discussed in https://github.com/dwyl/learn-docker/issues/15#issuecomment-428129875 I _agree_ that Docker is _useful_ in certain cases and this is indeed one of them; keeping dev environments consistent.
_However_ I don't feel that **`learn-docker`** is in a "beginner friendly" state ... 😕 
_Most_ of the sections are _woefully_ out-of-date and need to be tidied up for 2018. 
Once you are finished with your _current_ CS tasks, please dedicate a couple of hours to tidying up the _tutorial_ to make it easier for new people to get started/up-to-speed.
Assign the PRs to me for review as soon as ready.
Thanks! ✨
