### ISSUE TITLE
Filter venue results by Club Soda Score

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#18]
As a customer on the venue results page,
I'd like to filter my results by Club Soda Score,
so I only see the best venues from the search results.

**Comment by iteles** [comment]
Linked to other filtering venue options: #19 #21

**Comment by jussi-club-soda** [comment]
@iteles I've put this as priority 2, as it feels really important to me for people to be able to easily find the best venues.

**Comment by iteles** [comment]
@SimonLab We'll need to remember that a lot of users won't know what 'score' means, so we'll need to change the title of the drop-down to `Club Soda Score` please

![image](https://user-images.githubusercontent.com/4185328/49510251-89b9f280-f87f-11e8-8e4a-5c7f2cb028f3.png)

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/49596928-55bff980-f973-11e8-8183-1933115b91c0.png)
