### ISSUE TITLE
Adding drinks to new brands causes errors

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#181]
Moved from https://github.com/club-soda/club-soda-guide/issues/167

From @jussi-club-soda:
Bug with adding new drinks/brands: I've added a new brand (Eisberg) but when trying to add a drink to it, get error message next to the brand box: "is invalid"

**Comment by SimonLab** [comment]
![image](https://user-images.githubusercontent.com/6057298/49240137-6bc23d00-f3fc-11e8-989e-77c08b42e907.png)

**Comment by jussi-club-soda** [comment]
Seems to work in staging now! :)
