### ISSUE TITLE
Links between types and styles

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#186]
Currently in our database we hold drink types `/drink_types` (e.g. wine, beer, soft drink) and drink _styles_ `/drink_styles` (e.g. red, white, seasonal) but we do not have a link _between_ them https://github.com/club-soda/club-soda-guide#user-admin-guide.

In order for our filters #37 https://github.com/club-soda/club-soda-guide/issues/38 to update automatically when new types/styles are added _and_ to allow filters to function in a more user-friendly way, we need to create a link between them.

This implies:
+ [x] Creating many-to-many relationships between types and styles in our database
+ [x] Updating the admin UI to allow styles to be linked to multiple types at once

**Comment by SimonLab** [comment]
A style can now be linked to multiple types via the admin page of the style

**Comment by jussi-club-soda** [comment]
Cool. @SimonLab - the existing links: are they derived from the database as it is? So everything should make sense?

**Comment by SimonLab** [comment]
I've written a script to create the links between types and styles for the existing items on the database. After than any new type/style will be saved in the database and displayed in the dropdown
