### ISSUE TITLE
Filter venues by drink types

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#20]
As a customer viewing my venue search results,
I'd like to filter venues by drinks,
so I can only see venues serving drink types I'm interested in

**Comment by iteles** [comment]
@jussi-club-soda I'm assuming that @ctrembath added the `awaiting-review` label originally because you weren't sure whether this was a requirement.

Now that the app has been in the hands of users for a while, has this been requested at all?
