### ISSUE TITLE
Replace the venue page placeholder image

### ISSUE THREAD

**Issue by Cleop** [club-soda/club-soda-guide#204]
The placeholder image on the venue page is currently one we've taken from online. We need to replace it with our own version.

![image](https://user-images.githubusercontent.com/16775804/49594287-6f5e4280-f96d-11e8-8631-29ec8c450655.png)

- [x] Replace the venue page placeholder image with our own version

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/49596212-bb12eb00-f971-11e8-93e5-9ff1b17ebaa6.png)

**Comment by nelsonic** [comment]
@Cleop thanks for opening this issue. 👍 
A potential enhancement from CS' perspective would be to use a "glass half full" (_or half empty..._)
as the placeholder image to be more "on brand". 
Fine for now though ... just if you happened to be "doodling" ... 😉

**Comment by jussi-club-soda** [comment]
Ok, let us have a think about what we'd like to see there!
