### ISSUE TITLE
Add "Brand" to search

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#214]
Problem: drinks search doesn't search in "brand" (just drink name and description?) - eg search for Seedlip on live site

acceptance criteria:

- [x] Drink search also searches for Brand

**Comment by Cleop** [comment]
Karma Cola is not in the drink name or description for the Orangeade but it appears in the search now due to brand:
![image](https://user-images.githubusercontent.com/16775804/50166013-061bef00-02de-11e9-9f7d-ae07abf7647a.png)

**Comment by jussi-club-soda** [comment]
Whoop!
