### ISSUE TITLE
Word 'STYLE' appears in certain drinks card information erroneously

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#219]
Drinks are showing the word "STYLE" where it shouldn't be (in the details side of the card): 
See:
+  https://www.clubsodaguide.com/brands/e25693cd-3eeb-4a91-9959-c52567fd9903 or 
+ https://www.clubsodaguide.com/brands/7e798eee-a85d-483d-979e-2ef3f4757393

**Comment by RobStallion** [comment]
@iteles are we just meant to remove this word?

**Comment by Cleop** [comment]
@RobStallion - yes 👍
