### ISSUE TITLE
Check that 'edit' links don't appear on the brand page

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#220]
As an admin
I don't want customers to see 'edit' links from venues or brand pages
So that they do not get confused when they don't have access to the links when they click on them.

Linked to #132 

![image](https://user-images.githubusercontent.com/4185328/49820881-001f8e80-fd71-11e8-8c23-f1f9b2b10e8e.png)

For brands that don't have descriptions or websites such as Budvar for example: https://www.clubsodaguide.com/brands/c64e4b6b-45ab-435e-974c-3d906d6cab15

Is there anything in particular you want to see here when there is no content for these fields?

**Comment by jussi-club-soda** [comment]
If there is no info for description, website etc, can we just have blank space there? I can't think of anything useful to display...

**Comment by iteles** [comment]
@jussi-club-soda Agreed, that's what we've gone with for now:
![image](https://user-images.githubusercontent.com/4185328/50238433-5450f100-03b7-11e9-99c1-4d82b121943d.png)


Just noticed a small but here as the 'earth' is still showing when there is no website, we'll get on it :+1:
