### ISSUE TITLE
Change drink brand URLs

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#222]
The current url for a drink brand is the internal ID ("asldkyualdjflsdjf"). 

Acceptance criteria:

- [x] Drink brand url's are in human readable format, based on the drink brand name, eg Big Drop Brewing would be clubsodaguide.com/big-drop-brewing
- [x] Spaces in URLs (which appear as `%20`) should be replaced by dashes

**Comment by iteles** [comment]
Example: https://club-soda-guide-staging.herokuapp.com/brands/Punchy%20Drinks

We may want to replace spaces with dashes @jussi-club-soda ?
