### ISSUE TITLE
Change venue URLs

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#223]
The current url for a venue is the internal ID ("asldkyualdjflsdjf").

Acceptance criteria:

- [x] Venue url's are in human readable format, based on the venue name and address

To be determined how to handle duplicates! (especially some pub names are very common, there are two Red Lions within a mile of each other in the City of London alone etc)

**Comment by iteles** [comment]
Agreed we would go with `venueName`-`firstPartOfPostcode`-`secondPartOfPostcode`

**Comment by Cleop** [comment]
Steps:
- [x] Change the existing url to venue name - postcode
- [ ] ensure that postcode spaces and venue spaces appear as dashes
- [ ] change existing get functions for querying the DB into get_by featuring the name/postcode

**Comment by Cleop** [comment]
Currently ampersands in venue names do not display in the urls as ampersands, e.g.

![image](https://user-images.githubusercontent.com/16775804/50773837-d4b59400-1289-11e9-86bb-85e0a63bbc60.png)

for Adam & Eve.

Is this a priority to change? Shall I open a new issue or resolve it in this issue? I think it will also apply to the brand urls too.

**Comment by jussi-club-soda** [comment]
Would it be easiest to just drop any special characters (not sure technically, but from a practical point of view at least)?

**Comment by nelsonic** [comment]
@jussi-club-soda it would be _easy_ to drop the special characters from venue names, but the venues which have those special characters would be "upset" because it's their _name_ ... 😞 
We are better off leveraging the work that @Cleop has done and having a "lookup" for the list of special characters that converts them to something that is URL-safe. 
as Cleo suggested, converting `&` to `-and-` would be the way to go for URLs.

**Comment by Cleop** [comment]
@jussi-club-soda -  unfortunately dropping special characters wouldn't work from a technical perspective. I've just scanned through the existing venue names to identify roughly how many characters we're talking about and it seems like the special characters that exist are:
- apostrophe `'`
- ampersand `&`
- comma `,`
- plus `+`

(There are also full stops but they display without alteration in the url)

**Comment by nelsonic** [comment]
@Cleop for the _punctuation_, it makes sense to _strip_ (_i.e. have a RegEx that removes them_) from URLs.
We should have a `:slug` column in the DB that converts names of venues/products into SEO-friendly unique URLs. We will need to have a _function_ that generates the `slug` and checks the DB for uniqueness. 

examples: 

| Venue Name  | `slug` |
|---|---|
| O'Briens Bar & Restaurant | obriens-bar-and-restuarant | 
| Slug & Lettuce | slug-and-lettuce |
| The Lion, Witch & Wardrobe Family Pub | the-lion-witch-and-wardrobe-family-pub |
| O'Briens Bar & Restaurant | obriens-bar-and-restuarant-2 | 

Notice how when there are ***identically*** named pubs we need to affix the **2** to the `slug`.
This will happen and we need to have a function (_with tests_) that creates the _unique_ `slug`

> Cleo, as you observed in our off-github-chat, StackOverflow removes common grammatical articles from slugs e.g: "the", "a", "and" ... this _could_ be a good option. But for now, let's just focus on stripping the URL-unfriendly characters and if it's later deemed that "The" is superfluous in a URL, the function can be updated.

**Comment by Cleop** [comment]
I have enabled the slug to be updated if the name or postcode of a venue changes. My concern with this though is that it means that old versions of the venue will still be accessible via the old slug. This would only occur if someone had saved the link and accessed it from favourites or browser autocomplete. @nelsonic do you have any thoughts on how this can be solved/ avoided?

**Comment by nelsonic** [comment]
@Cleop to be clear you are highlighting the scenario where someone changes the name of the venue (_unlikely_) or the postcode where the venue is located (_even more unlikely_) ... 🤔 
Have you written a _test_ on the branch for changing the name of the venue?
Please share a link to the test so I can understand what the issue is.
thanks.
