### ISSUE TITLE
Unable to log in to live site

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#227]
I can't log in to the live site today, getting an "Internal server error" message

**Comment by Danwhy** [comment]
@jussi-club-soda Could you try again now? I think the problem may have been that there were two accounts existing for your email address, which I've just cleared. 
The work to prevent this from happening has been done but not deployed to live yet, so for now, if you are adding a new venue, could you make sure to use a different email address or use the `/admin/venues/new` page

**Comment by jussi-club-soda** [comment]
Cool, working again!
