### ISSUE TITLE
Ensure 'Improve your score' CTA is only visible to Venue admins

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#235]
As a customer visiting a venue page,
I'd like to not see the  'Improve your score by adding more drinks to you stocklist.'
so that i'm not confused by what is expected of me on the page

## Acceptance Criteria
- [x] Viewing a venue page as a customer shouldn't show 'Improve you score' CTA
- [ ] As a venue admin, viewing my page should show me the 'Improve you score' CTA

**Comment by iteles** [comment]
Linked to #53
