### ISSUE TITLE
See venue primary details

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#25]
As a customer looking at a venue page,
I'd like to see a venues name, description, website URL, address, venue type, phone number, opening times, social media handles
so I can find out more details about the venue

## Acceptance Criteria
This page includes:
+ [x] Photo of venue
+ [x] Venue name
+ [x] Venue type **(required field)**
+ [x] Club Soda score #26 
+ [x] Venue description (no truncation for now)
~+ [ ] Map displaying location of venue~ Moved to https://github.com/club-soda/club-soda-guide/issues/197
+ [x] First line of venue address input
+ [x] City input
+ [x] Postcode **(required field)**
+ [x] Venue telephone number
+ [x] Website
+ [x] Add social media handles: Facebook and Instagram  (assets in https://projects.invisionapp.com/d/main#/projects/prototypes/15083747/assets)
~+ [ ] Opening hours #57~ Removed as per #119
+ [x] Stock list

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/46418702-395dd180-c724-11e8-912b-7432fbd86b89.png)

**Comment by iteles** [comment]
@Danwhy Just tested saving a venue without a type and it wiped the whole form (don't know if it actually saved - `Ye Old DWYL cafe` (in staging).

Final tasks for this appear to be:
+ Bug with having the form data disappear and not save when no type is entered
+ We need the required `*` to appear next to Type title to indicate required
+ Clicking on the 'Add a phone number' link must take you to the edit form (currently just refreshes the page)
![image](https://user-images.githubusercontent.com/4185328/48909808-25059d80-ee66-11e8-9d67-b144e60d3c7c.png)
