### ISSUE TITLE
Drink title should display in the centre of the card

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#251]
As a customer viewing a brands page
I'd like to see the name of the drink in the centre of the drinks card
so it is inline with the drinks card on the search results page

## Acceptance Criteria
- [x] Drink title on drinks card is aligned to the centre on the Brand page
- [x] Drink title on drinks card is aligned to the centre on a Venue page
- [x] Drink title on drinks card is aligned to the centre on the homepage

## Screenshot
![screenshot 2018-12-18 at 10 28 35](https://user-images.githubusercontent.com/8418748/50148255-ec63b300-02af-11e9-869c-bcd0c5694031.png)

**Comment by Cleop** [comment]
@ctrembath - are you able to share what device it is you are getting this bug? I've tried to recreate it on both my laptop and a monitor and can't see the titles as your screenshot shows:

Monitor:
![image](https://user-images.githubusercontent.com/16775804/50912021-0a44b380-1429-11e9-8a19-342e278a6957.png)

Laptop:
![image](https://user-images.githubusercontent.com/16775804/50911976-eb462180-1428-11e9-9dea-377c991ffbd5.png)

@SimonLab @Danwhy - are you able to reproduce this one?

**Comment by Cleop** [comment]
@ctrembath was this just happening to you on the brands page? I can't reproduce it on the landing page or search page but have now managed to sort of reproduce it on the brands page:
![image](https://user-images.githubusercontent.com/16775804/50912587-69ef8e80-142a-11e9-97fb-a3a859467826.png)

**Comment by ctrembath** [comment]
@Cleop - I'm on Google Chrome, window size is 1440px by 800px

![screenshot 2019-01-10 at 10 56 20](https://user-images.githubusercontent.com/8418748/50964166-7cb7a100-14c6-11e9-8752-ea8bc03919ee.png)

See 'Stryyk Not Rum'

**Comment by Cleop** [comment]
@ctrembath - what page are you viewing there? is it still happening on all pages still or just this one page?

**Comment by ctrembath** [comment]
Production.
Happening on all venue pages

https://www.clubsodaguide.com/venues/42d0f959-98e5-48c1-9ceb-83ab149f3ac6

**Comment by Cleop** [comment]
@ctrembath - sorry I should have clarified, the please-test label was for staging only. You will be able to test this on production once we've deployed to production 👍
