### ISSUE TITLE
Drinks cards on a brand page shouldn't display text STYLE after declaring the style

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#252]
As a customer viewing a brand page,
I'd like to see the style of a drink without the word STYLE
so I don't get confused by the information

## Acceptance Criteria 
- [ ] More details on a drink card shouldn't display the word STYLE
- [ ] More details on a venue card shouldn't display the word STYLE

## Screenshot
![screenshot 2018-12-18 at 10 35 14](https://user-images.githubusercontent.com/8418748/50148523-a529f200-02b0-11e9-927e-0223e8b391aa.png)

**Comment by Cleop** [comment]
I think this is a duplicate of: #219

**Comment by ctrembath** [comment]
Yes - you're right, I'll close the issue
