### ISSUE TITLE
If venue hasn't supplied a social handle - hide the icon

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#253]
As a customer viewing a venue page,
I'd like to only see social icons with links
So I know what social accounts the venue uses

## Acceptance Criteria
- [x] Hide a social icon if a venue hasn't supplied a url

## Screenshots
![screenshot 2018-12-18 at 10 39 41](https://user-images.githubusercontent.com/8418748/50148792-53359c00-02b1-11e9-835c-2245c32fae2c.png)

**Comment by jussi-club-soda** [comment]
Looking at https://club-soda-guide-staging.herokuapp.com/venues/rochester-castle-n16-0ny

I can still see an

Add venue instagram 

link even when not logged in?

**Comment by Cleop** [comment]
I've tested it on staging and I don't see it when I'm not logged in as an admin:
![image](https://user-images.githubusercontent.com/16775804/51470962-43581e80-1d6d-11e9-93a8-3d84d13ce5a5.png)

Are you sure you're logging out as an admin effectively? When you try to view the admin endpoints you should see this:
![image](https://user-images.githubusercontent.com/16775804/51471059-8c0fd780-1d6d-11e9-87fe-2d2e85e3c9b9.png)

I have noticed that the padding isn't removed on the div that contains the instagram link so I will ensure that doesn't show!

**Comment by iteles** [comment]
@Cleop You're right, I've just retested it in firefox (which I've never used for Club Soda) and don't see them either.
