### ISSUE TITLE
If venue websites URL is too long - truncate it

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#255]
As a customer viewing a venue page,
I'd like to see the website URL truncated
so it is still inline with it's 'Website' icon

## Acceptance Criteria
- [x] Truncate a website URL if it is above 44 characters
- [x] Display URL inline with icon

## Screenshot
![screenshot 2018-12-18 at 11 03 48](https://user-images.githubusercontent.com/8418748/50150002-a3fac400-02b4-11e9-9e9d-3f366727b690.png)

**Comment by SimonLab** [comment]
We can use the css property `text-overflow`: https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow
We need to make sure that a width is defined for the link and it is a block element.
With a width of 60%:
![image](https://user-images.githubusercontent.com/6057298/51247325-abc98900-1984-11e9-9409-2325daac2eea.png)
