### ISSUE TITLE
Venue 'Add Description' should be a large text field

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#259]
As a venue owner creating my page,
I'd like to see a large text area for my 'Description'
so I know how much copy to provide

## Acceptance Criteria
- [ ] 'Description' field on the 'venue edit' page should be a text area

## Screenshots
![screenshot 2018-12-18 at 13 52 55](https://user-images.githubusercontent.com/8418748/50158640-95200b80-02cc-11e9-9813-9bd609006fe0.png)

**Comment by iteles** [comment]
@ctrembath Closing this as a duplicate of #128 (looks like there's a regression there which I've logged as a bug, thanks for catching) 👍
