### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#260]
As an admin interested in the Club Soda Guide traffic
I'd like to log into Google Analytics
so I can see analytics about the guides users

## Acceptance Criteria
- [x] Add @jussi-club-soda GA code

**Comment by jussi-club-soda** [comment]
UA-56935445-6

**Comment by Cleop** [comment]
Script added, now awaiting review.
![image](https://user-images.githubusercontent.com/16775804/50291448-85d4c580-0466-11e9-9de1-77b0b319bda6.png)
