### ISSUE TITLE
The homepage hero image should be the background to the topbar

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#261]
As a customer landing on the Club Soda Guide,
I'd like to see the topbar ontop of the hero image
so I am immediately captivated

## Acceptance Criteria
- [x] The hero image on the homepage should spread underneath the topbar links

## Screenshot (from @harrygfox designs)
![screenshot 2018-12-18 at 14 20 07](https://user-images.githubusercontent.com/8418748/50159998-0c0ad380-02d0-11e9-985b-9a2452c3f9ec.png)

**Comment by iteles** [comment]
@ctrembath The readability of the navbar links isn't very good with the background image we have here - the  colour contrasts don't pass the accessibility standards for readability. We've opted for a white navbar for now with this TBD. We can try a few variations of a semi-transparent white to see if this works better for readability?

**Comment by ctrembath** [comment]
@iteles I've had a go experimenting in the console and I think if we could add div with a white background to cover the whole section, and then make it slightly transparent (I tried 0.1 opacity) then the readability of the links should be OK..

![screenshot 2018-12-20 at 09 42 16](https://user-images.githubusercontent.com/8418748/50277323-f9151200-043b-11e9-9f73-c6ea1dda67f9.png)

Let me know what you think

**Comment by iteles** [comment]
@ctrembath Happy to try it and run it though accessibility checkers until we get something that work :+1:

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/50644458-d2d99100-0f68-11e9-8d1c-51d6617e4ff2.png)
10% opacity on a white overlay

**Comment by Cleop** [comment]
Changing the navbar position has moved the flash message out of line, I am now going to correct this:

![image](https://user-images.githubusercontent.com/16775804/50910495-d3b96980-1425-11e9-8b9b-813198b011b3.png)

**Comment by ctrembath** [comment]
This looks great!

Thanks @Cleop
