### ISSUE TITLE
Venue type tags should be different colours

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#264]
As a customer viewing a venue page
I'd like to see different colour tags for the venue type
so I can easily decipher between the venue types

## Acceptance Criteria
- [x] Venues tags should all be different colours 
- [x] Venue tags should be inline with styleguide

## Screenshot from styleguide
![screenshot 2018-12-18 at 15 01 53](https://user-images.githubusercontent.com/8418748/50162314-f00a3080-02d5-11e9-8f0c-8746c0d6d282.png)

**Comment by SimonLab** [comment]
The four default colour for the venue type are now defined. The default dark backgound with white text is used for the other type of venues not defined by the style guide:

![image](https://user-images.githubusercontent.com/6057298/50845139-1adf2600-1364-11e9-8f4e-027cca1cbf0f.png)

**Comment by iteles** [comment]
@SimonLab For:
+ `Cafes` let's use the white background as per the 'Cocktail bar' example from the style guide (as we don't yet have any of those and these were just illustrative examples from Harry)
+ `Hotels` let's use either the black or the active (#2B7CDA) colour from the colour palette Harry put together (I'll leave it to you to determine which one looks best for a starting point, which one is different enough from the others to be told apart :+1:)
![image](https://user-images.githubusercontent.com/4185328/50846063-2b909b80-1366-11e9-8f54-cb71d2125a83.png)


Good call on defaulting a background for any other types not defined at this point :+1:

**Comment by SimonLab** [comment]
![image](https://user-images.githubusercontent.com/6057298/50853277-af07b800-1379-11e9-9cc6-241bddd41315.png)

The white background doesn't contrast enough so I used the navy background instead

**Comment by iteles** [comment]
Particularly fond of your venue name ✨

**Comment by SimonLab** [comment]
@iteles does the pills need to be clickable and direct to the search venue page with the selected venue type has filter?

**Comment by iteles** [comment]
Good question! This wasn’t part of the original requirements but might be a nice addition. Let’s open a separate issue for it so Jussi and Clare can evaluate.
