### ISSUE TITLE
Sprint Demo prep

### ISSUE THREAD

**Issue by Cleop** [club-soda/club-soda-guide#271]
**Landing page**
- No pink border on 'List a venue'
- New search bar
- Weighting on drinks carousel bug resolved
- Drinks don't have the word 'STYLE' on
- joinclubsoda link opens in new tab
- New footer

Action: perform a search in the search bar with the term 'beer'

**Results page**
- Has see all with filter still applied or go to the page without filter

**Drinks page**
- Drink type dropdown styling
- brands now show in search e.g. Karma Kola orangeade

**Venues page - Albero lounge**
- map, click to open in new tab

**Admin - retailers**
`/admin/retailers`
- Website validation
- Create new retailer

**Admin - static page**
`admin/static_pages`
- Add a new one and include it in the footer - mention that title in menu is needed for that

**Comment by nelsonic** [comment]
@Cleop please add links to the issues covered to assist @jussi-club-soda in signing off the stories. thanks! ✨

**Comment by Cleop** [comment]
Closing as demo now complete
