### ISSUE TITLE
Search by postcode in search bar

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#274]
As a customer on the Club Soda Guide homepage
I'd like to input my postcode in the search bar and see venues closest too me
So I know where near me if a great venue for AF drinkers

## Acceptance Criteria
- [x] Searching by postcode returns a list of venues ordered by distance to postcode
- [x] Searching a postcode returns no drinks

**Comment by ctrembath** [comment]
@iteles can you tell me what the status of this issue is?

**Comment by iteles** [comment]
@ctrembath This is as per https://github.com/club-soda/club-soda-guide/issues/276#issuecomment-453499410 😊

**Comment by ctrembath** [comment]
@iteles currently the postcode search only returns venues with the identical postcode.
The acceptance criteria was to return a list of venues ordered by distance to postcode, in the same way as the [HappyCow](https://www.happycow.net) postcode search works.

**Comment by SimonLab** [comment]
@ctrembath for the "postcode search" the application needs to have the full postcode for it to be able to find a specific latitude and longitude. For example if we search for "BS8 3PA" we will have the venues near this postcode:

![image](https://user-images.githubusercontent.com/6057298/52043340-5a4dfc00-2537-11e9-8f65-c85b73539220.png)


![image](https://user-images.githubusercontent.com/6057298/52043353-62a63700-2537-11e9-985c-810370883c1b.png)

When searching for a part of the postcode, for example "BS9" we are searching any substring in the postcode string value of the venues (search by text), and it will return the venues matching this first part of the postcode:

![image](https://user-images.githubusercontent.com/6057298/52043498-c597ce00-2537-11e9-8344-19eaa54dc9b7.png)

**Comment by ctrembath** [comment]
@SimonLab - thanks for explaining.

Are we storing all the searches that are being made in the homepage search bar? I remember there was some discussion around this - It would be helpful for us to see how users are interacting with the search bar.

**Comment by ctrembath** [comment]
@iteles OK amazing - I will get issueing

**Comment by SimonLab** [comment]
Google analytics should also gives an idea of the searches done as it tracks the search endpoint `/search/all` e.g `https://club-soda-guide-staging.herokuapp.com/search/all?_utf8=%E2%9C%93&term=london` when searching for `london`

**Comment by iteles** [comment]
@ctrembath This is a great way of checking for the searches already done in production ahead of #445 ⬆️ 

Shall we close this issue in favour of #445 ?
