### ISSUE TITLE
Search by location in Search Bar

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#276]
As a customer on the Club Soda Guide homepage
I'd like to input a location in the search bar and see venues closest to the location
So I know what venue to go to when I meet my friends in Shoreditch

## Acceptance Criteria
- [ ] Searching a location returns a list of venues ordered by distance to that location

**Comment by ctrembath** [comment]
@iteles can you tell me what the status of this issue is?

**Comment by iteles** [comment]
@ctrembath This wasn’t in the original scope as we discussed but is a very interesting idea and we’ve been doing some thinking about it. The trick is understanding what the user expects here and how we could differentiate between a search term and a location. i.e. If a user enters ‘ealing’ as a search term, how do we know they’re searching for a location (and therefore know to search for venues around the location vs searching for the word Ealing in addresses, brands and drinks). 
We’ll be writing up our thoughts once we’ve completed the production issues raised :+1:

**Comment by SimonLab** [comment]
Looking at what the Google API can provide: https://developers.google.com/maps/documentation/javascript/places-autocomplete#style_autocomplete

**Comment by SimonLab** [comment]
See #378 for more thought on the location search.
The main idea is to avoid sending requests to Google to keep the search fast and to not have to pay Google.
Instead we can use the same logic we use for postcodes and save a list of all the locations in UK with their latitude and longitude in the application cache. When a user will search for a term the application will be able to check if the search term match a location and if yes to return the venues near this location.

The challenge here is to create a list of locations. I found three main source we could user:

## Wikipedia 
Wikipedia has a list of all the locations: https://en.wikipedia.org/wiki/List_of_United_Kingdom_locations
However I haven't found a way to doanload the data. We could scrape the all the location pages (I found the following project which did that but I'm not sure it's up to date and it returns only the location name without the lat/long, https://github.com/balaclark/uk-locations)
example of one of the many locations tables in wikipedia:
![image](https://user-images.githubusercontent.com/6057298/51316537-e139a980-1a4c-11e9-8705-d967fa8c2c9e.png)

## The Office for National Statistics
The ONS provide a page where we can download some location: http://geoportal.statistics.gov.uk/datasets/a6c138d17ac54532b0ca8ee693922f10_0/geoservice?orderBy=place15nm&selectedAttribute=laddescnm
However the data dates back from 2016 and I'm not sure it's a better set of data compare to the one from Wikipedia (I try to find "Shoreditch" on the set but couldn't get the correct result, maybe I need to specify a bit more my request)
![image](https://user-images.githubusercontent.com/6057298/51316723-6ae97700-1a4d-11e9-9a47-49d0ba9dab17.png)

## The Ordonance Survey
The ordonance survey provide a set of locations (and much more, eg road/street name) which has recently been updated (10/2018) and we can doanload the data as csv files. This dataset seems to be the most complete, however I still need to find a way to extract the lat/long from other fields.
https://www.ordnancesurvey.co.uk/opendatadownload/products.html#OPNAME
![image](https://user-images.githubusercontent.com/6057298/51317004-4cd04680-1a4e-11e9-99cd-31d3e031b1d2.png)

So I think the best two solutions are Wikipedia and the Ordonance Survey data

**Comment by SimonLab** [comment]
I have now been able to extract and filter a list of locations based on the ordnance survey data (from 1.7GB to 2.5mb) with a bit more 42200 places:
[locationName.zip](https://github.com/club-soda/club-soda-guide/files/2769730/locationName.zip)
I now need to convert the east/north values to latitude/longitude

**Comment by SimonLab** [comment]
The search by location has been implemented with the following logic:
https://github.com/club-soda/club-soda-guide/issues/378#issuecomment-455219398
