### ISSUE TITLE
Drink weightings

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#279]
When I try to change a drink's "Weighting" to get them featured more prominently on the home page, I always get an "Internal server error" ... 

Both on staging and production versions

**Comment by SimonLab** [comment]
Relation with drink type error when trying to update a drink:
![image](https://user-images.githubusercontent.com/6057298/50339141-8cb71300-050e-11e9-918f-f260e2531dbf.png)

**Comment by iteles** [comment]
Upping this to a p1 as the type error is affecting the type buttons on the homepages both in production and staging

**Comment by jussi-club-soda** [comment]
This seems to be fine in production now!
