### ISSUE TITLE
Venue profile page header section contains a carousel of images

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#28]
As a customer looking at a venue profile page,
I'd like to see a carousel of venue images,
so I have an idea of what the venue looks like

**Comment by Cleop** [comment]
Linked to #317

**Comment by Cleop** [comment]
Adapting the elm code is not going to be straight forward as the carousel and carousel model are expecting the structure of drinks data and for a carousel of 12 items and the styling of 4 cards showing at a time, not one. So the switch is not going to be straight forward.

However as I feel swiping will be integral to the mobile designs (even on the radio button desktop version as the radio buttons may be too small to click on on mobile), I've looked into performing the swiping without elm and you end up recreating a large part of the elm logic (in vanilla js) so I don't think this is a good use of time/lines of code.

So I think I will pursue the elm option even though it has some complexity involved.

**Comment by Cleop** [comment]
**Still to do:**
- [ ]  Get the venue information using the slug in params for the `json_index` route (currently hardcoded)
- [ ] Do more styling on the slideshow
- [ ] Refactor to merge together reusable drinks/venues functionality
- [ ] Ensure the images show in the right order according to their photo number

A possibility if we need to use the inline styling background-image property: https://github.com/rtfeldman/elm-css

**Comment by iteles** [comment]
@Cleop Entirely agree that the white chevrons with a shadow (in case it's on a light background) is the best way to go.

I did a quick google search and we can use this for example?? https://180graus.com/assets/chevron-with-shadow-95cf05c5342a06f83cdc86b1bb2dc09caee7821a136770c3a8e4c2083c28bc2a.svg

**Comment by Cleop** [comment]
@Danwhy @SimonLab - I was wondering if either of you could help me with the first bullet point in my checklist above. I've currently been working on the feature by getting the image data using this hardcoded line: `Venue.get_by(slug: "all-bar-one-aberdeen-ab10-1bl")` in the venue controller `json_index` route.

What it consists of is:
![untitled_artwork 3](https://user-images.githubusercontent.com/16775804/52349662-ede36900-2a1e-11e9-91bf-e737750ce358.png)

I looked up this:
https://stackoverflow.com/questions/33561240/how-to-get-query-parameters-in-elm

But it suggests ports, and the weird thing is that it's my elixir controller that needs the value not my elm even though it goes via my elm. Unless I were to add a value in the model that comes from a port which is the slug. But that value would have to be set and then passed through with the json url to be of any use.

I'm going to push up my branch so you can take a look at the full picture of the code. I also get the following error at the moment which is not stopping the code from functioning (when I have my slug hardcoded in) but it's still displaying this error, so there's a chance it could be linked, I just don't fully understand it yet:

![image](https://user-images.githubusercontent.com/16775804/52349936-72ce8280-2a1f-11e9-9237-feca7094b72d.png)

**Comment by Danwhy** [comment]
@Cleop You could get the current page from the `conn`. It should be the 'referer' in the `req_headers`. 

I think passing it through as a param in the http call from elm would be an equally valid, maybe even better way of doing it though

**Comment by Cleop** [comment]
Awesome, thanks @Danwhy 
`{"referer", "http://localhost:4000/venues/all-bar-one-aberdeen-ab10-1bl"}`

I'll give this a go 👍

**Comment by Cleop** [comment]
Thanks @Danwhy that is working.

Another thing to fix now that there are multiple venue images:

- [ ] Ensure that on venue cards it is the first venue image which is shown (not 2,3 or 4)

**Comment by Cleop** [comment]
- [ ] Hide the carousel chevron images if there is only one venue image

**Comment by Cleop** [comment]
Ready for testing, to see the carousel arrows appear just make sure you upload more than one photo for that venue using the 'Upload Photos' button.
