### ISSUE TITLE
Run in production: Venues missing from admin panel & some details on front page

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#285]
At the moment in production I'm only seeing limited details about
The Old Ale and Coffee House
and
Charlotte's W5
 - just name, postcode and image showing (type and score missing)

When I look in admin, I can't find them on the list of venues at all...

**Comment by Danwhy** [comment]
After looking into this, it seems there are two problems at play:

The first is that some venues have lost their cs score and venue type. This looks to have happened on the 22nd of December, so I assume it was when the script to update the cs score was run. 

The venues affected are those which were using the score that was manually imported from the old site (ie. not calculated using the venues drinks), so it looks like the script updated the score to be "correct" based on the drinks the venues had (which was none for the most part). 

To fix this we can re-import the data for these venues, just taking into account the cs score and venue type. All these venues came from the same csv file originally (`venues_2` in the seeds).

The second issue is that venues without a venue type do not show up in the search or admin pages. This is just a small bug on the code that was filtering out retailers, and should be quick to fix.

**Comment by iteles** [comment]
Available for testing in staging

**Comment by jussi-club-soda** [comment]
Looks fine as far as I can tell! :)

**Comment by iteles** [comment]
Thanks @jussi-club-soda, leaving this issue open so  we can run this script in production when we get the green light to promote to production.

**Comment by SimonLab** [comment]
The application is now deployed and the script has been run.
see https://github.com/club-soda/club-soda-guide/issues/332
