### ISSUE TITLE
Venue profile page displays it's opening hours

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#29]
As a customer visiting a venue page,
I'd like to see the venues opening hours,
so I know when it opens and closes

**Comment by iteles** [comment]
Pulling down the priority as per https://github.com/club-soda/club-soda-guide/issues/57.
It was agreed that this was not required for now and should be hidden until requested as a feature: https://github.com/club-soda/club-soda-guide/issues/119
