### ISSUE TITLE
Upgrade postgres

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#301]
I'm getting warning emails from Heroku that the database is getting full:

> The database DATABASE_URL on Heroku app club-soda-guide is approaching its allocated storage capacity.
> 
> The database contains 7,691 rows. The Hobby-dev plan allows a maximum of 10,000 rows. If the databases exceeds 10,000 rows then INSERT privileges will be revoked, preventing more data from being written. INSERT privileges are automatically reinstated if rows are removed and the database once again complies with the plan limit.
> 
> To avoid a disruption to your service, migrate the database to a Basic ($9/month) or higher plan:

I thought this would be a simple thing to do, but it seems to require creating a new database, migrating data, and deleting the old one? Or have I misunderstood? This seems to be the process: https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases#upgrading-with-pg-copy

The next level ($9 / month) should be good for us for a while still?

@Danwhy - do you have the admin rights to do this?

**Comment by nelsonic** [comment]
@jussi-club-soda yeah, $9/month will be good for the foreseeable future and means that Heroku manages incremental backups of the data. 

@Danwhy if you can please apply the upgrade ahead of the festival. 👍

**Comment by Danwhy** [comment]
@jussi-club-soda Only the app owner can add new paid plan databases, but if you add a new database with the $9/month plan, which can be done from the dashboard, I can then transfer over the data and promote it to be the main app database.

To do this you just have to go to https://dashboard.heroku.com/apps/club-soda-guide/resources, type 'Heroku Postgres' into the `Add-ons` search box,

<img width="1238" alt="screen shot 2019-01-07 at 12 12 58" src="https://user-images.githubusercontent.com/8939909/50767662-931aee00-1275-11e9-9d0b-4154a86194d2.png">

 and provision a 'Hobby Basic' database.

<img width="1112" alt="screen shot 2019-01-07 at 12 12 40" src="https://user-images.githubusercontent.com/8939909/50767666-96ae7500-1275-11e9-9dfb-69bcb2e8410f.png">

**Comment by jussi-club-soda** [comment]
Thanks @Danwhy , just done that!

**Comment by Danwhy** [comment]
:+1: I've done the upgrade
