### ISSUE TITLE
Formatting for static pages

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#303]
Now that the base functionality for this has been created in #14, a test page has been created to determine next steps.

The CSS for the styling of these pages needs to be updated.
Note: there will likely be other elements to update, but the content in the FAQ page is a good starting point.

https://club-soda-guide-staging.herokuapp.com/Frequently%20Asked%20Questions
![screencapture-club-soda-guide-staging-herokuapp-frequently-asked-questions-2019-01-04-17_17_24](https://user-images.githubusercontent.com/4185328/50701171-b1e66e00-1044-11e9-8fa4-a82200061c25.png)

Mobile:
<img src="https://user-images.githubusercontent.com/4185328/50701194-c6c30180-1044-11e9-8312-59a726612963.png" width=200px />

### Three areas to consider formatting:
+ [x] URL (replacing the `%20` with dashes
+ [x] Body text
+ [x] Footer

**Comment by Cleop** [comment]
@jussi-club-soda - It looks like your html has been generated automatically somehow meaning you have some empty tags like this:

![image](https://user-images.githubusercontent.com/16775804/50895549-529aac00-13fe-11e9-94d9-8d57f117f734.png)

These will distort my new spacing slightly so you may need to go through and remove them manually where you notice slightly odd spacing.

**Comment by Cleop** [comment]
**This is the FAQs page with my new styling on desktop:**
![image](https://user-images.githubusercontent.com/16775804/50895691-b45b1600-13fe-11e9-84a9-609bc04e8ed3.png)

**Comment by iteles** [comment]
@cleop My only note is that it would make sense for the space _above_ the question to be larger than the space _below_ the question so that visually the question is easily linked to its answer (can just make the space between the question/h and the paragraph a little smaller, the white space above looks good)
