### ISSUE TITLE
Brand page images?

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#305]
Just checking whether this is still somewhere on the agenda and hasn't been lost: 

On the brand page, admins should have the ability to add two images: a logo banner (which replaces the generic "colour" image on top) and another image of the brand, as in Harry's designs.

**Comment by jussi-club-soda** [comment]
Am I missing something, but I can't find the "upload photo" button for brands? And when I click on link in @iteles comment above and try to upload, I get "Internal server error".

The other thing is that this only allows one image per brand? It was meant to be one for the banner, and another one further down?

**Comment by iteles** [comment]
@jussi-club-soda It's a bit of a confusing UX, but if you check the 'Use as cover photo' checkbox when you upload a photo, it will save as a banner photo (replacing anything that is already there) and if you don't check that checkbox, it will save as the one further down.

The 'Upload photos' button is on the brand page itself, so in this case I've made Black Castle a member brand on staging and if you go to the brand page, logged in as an admin, you will be able to see the button: https://club-soda-guide-staging.herokuapp.com/brands/Black%20Castle
![image](https://user-images.githubusercontent.com/4185328/50835720-5d4a3800-134f-11e9-9e0a-bf40db9a0481.png)

**Comment by jussi-club-soda** [comment]
Ah, this only works if they are a member? And you can upload two images, just select/not select the option?

**Comment by iteles** [comment]
Exactly that @jussi-club-soda 👍

**Comment by jussi-club-soda** [comment]
When I try to test this on staging, I still get an "Internal server error" whenever I try to upload an image...

@Cleop @iteles any ideas?

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/51398234-fab91f00-1b3a-11e9-9972-b75c49d9b7e1.png)

**Comment by SimonLab** [comment]
This is due to the wrong parameters passed to the `upload_photo` function:
https://github.com/club-soda/club-soda-guide/blob/b3dab1a8867b294ee71a49176a57753ed2f1aa3e/lib/cs_guide_web/controllers/brand_controller.ex#L158-L176

and especially the insert:
```
             BrandImage.insert(%{
               brand: params["id"],
               cover: String.to_existing_atom(params["cover"])
}),
```
`params["id"]` is used but it is not anymore defined as the route endpoint is using `name` instead of the default `id`:
https://github.com/club-soda/club-soda-guide/blob/b3dab1a8867b294ee71a49176a57753ed2f1aa3e/lib/cs_guide_web/router.ex#L61

The solution is to split the endpoint definition to keep the `name` params for the brand endpoint except for the `upload_photo` post endpoint

**Comment by ctrembath** [comment]
@iteles once I've uploaded a brand image I am unable to upload a new one. 

I uploaded a random image to test the functionality, but I'm now unable to change it. see : https://club-soda-guide-staging.herokuapp.com/brands/Heineken

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/52055122-6ac19f00-2556-11e9-87de-b13cad296448.png)

I've just tested this issue on staging on Heineken and it no longer appears to be an issue. As you can see I've changed the heineken cover image.

I am however going to push up changes to the social media links for brands as I noticed twitter is missing and the icons for them don't display correctly when the field is empty.

**Comment by Cleop** [comment]
@ctrembath - this is due to #421, @jussi-club-soda has changed the image upload bucket details on AWS but it's not working properly yet. I will change this label once that issue has been resolved.

**Comment by Cleop** [comment]
This is now ready to test 👍 @ctrembath

**Comment by ctrembath** [comment]
Hey @Cleop this is still appearing on Heineken page (staging)

**Comment by ctrembath** [comment]
@Cleop - I tried adding an image (see screenshot) - does the image need to be a specific size?

![screenshot 2019-02-01 at 18 01 31](https://user-images.githubusercontent.com/8418748/52140747-7e9afd00-264b-11e9-8b63-3ce871bb43fc.png)

**Comment by Cleop** [comment]
How strange @ctrembath - it's working fine for me on staging:

![image](https://user-images.githubusercontent.com/16775804/52201978-145da480-2865-11e9-84ed-f659940bee6b.png)

- **Size:** A screenshot on my computer is less than 500KB and I've just uploaded a files as big as 2.5MB and the largest we have on production is 4.2MB **so it doesn't sound like it's a size issue.** Although by all means check the size of the file you were using.
- **File type:** I've just tested uploading pngs, jpgs and TextEdit Documents (the file type I received the downloaded images from s3 in) and all of them worked. **Was the file type you were using something different?**
- Did you try the upload more than once and was the image not displaying every time? 
- Could you successfully upload and see any other files?
- Can you share a link to the page you saw that error on so I can inspect the page?
