### ISSUE TITLE
Close drink types/styles dropdown 

### ISSUE THREAD

**Issue by SimonLab** [club-soda/club-soda-guide#307]
Close the type and style drink dropdown on click outside of the dropdown of the clear pill filter (ie when the user click on any other part of the page)
![image](https://user-images.githubusercontent.com/6057298/50762587-47604880-1265-11e9-8988-51c741bd2001.png)

- [x] Add event listener on the body of the page to catch click event and check if the target of the click (or one of its parent) is not the dropdown or the pill

- [x] Update elm-criteria to expose a `close` function and call this function when the previous event listener is triggered

**Comment by jussi-club-soda** [comment]
I think this is fine.

On Staging the duplicate types seem to come to the drop-down too (eg "Beer" and "Beer"). Is there a way of finding out which we can delete on production, as they seem to appear there as well (though not on the drop-down, just in the admin panel).

**Comment by SimonLab** [comment]
On of the "beer" start with a space and this one can be deleted.
same for "Spirits & Premixed", one of the item start with a space

**Comment by ctrembath** [comment]
Relates to #336
