### ISSUE TITLE
Improving the UX of uploading pictures

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#317]
As discussed in https://github.com/club-soda/club-soda-guide/issues/305#issuecomment-452297961, this could do with some improvement and it would be good to build this out as a module that the community can improve ('for free') as it is used.

This will require some conversation, but is relevant to:
+ Venue image uploads
  + Requirement around multiple images to be discussed #58 
+ Brand image uploads
  + The requirement as per https://github.com/club-soda/club-soda-guide/issues/305#issuecomment-452297961 to upload both a cover image and a 'body' image for brands

Initially we should consider displaying the existing image to the user, having a feedback mechanism to let users know that the image is uploading  and splitting out the functionality for the two different types of brand image at a minimum https://github.com/club-soda/club-soda-guide/issues/305.

**Comment by Cleop** [comment]
By:
> display the existing image to the user

@iteles do you mean show the existing image for that page (if it exists) as opposed to show a preview of the image the user is about to add like this?
![image](https://user-images.githubusercontent.com/16775804/51977592-bbb29400-247f-11e9-9bb9-d1806e7278d6.png)

**Comment by Cleop** [comment]
@iteles - This is what I've drafted, let me know what you think:

**Requirements:**
- Images can be replaced (updated with a new preferred image)
- Users can see the existing image (if there is one, to help them be sure they want to replace that image if adding a new one)
- Users can see when their upload is in progress as the button changes to read 'uploading...'

**Nice to haves:**
- image compression

There isn't the need for the checkbox for 'cover image', you know which image you are updating/adding based on which button on the page to edit/upload you clicked on.

![untitled_artwork 2](https://user-images.githubusercontent.com/16775804/51984568-9c256680-2493-11e9-8c7e-d589a9bbb505.png)

**Questions:**
- How many images do we want to be able to have for instances with a carousel e.g. the venue page cover image? @jussi-club-soda ?
- I'm not sure from a technical perspective whether on the carousel examples it would be best to have one submit button per carousel spot or one for all photos in that carousel (as per the illustration)

**Comment by iteles** [comment]
@Cleop Looks good to me! @jussi-club-soda What are your thoughts on this?

The only change I would suggest is the addition of a title to the page so that the user *knows* that they are updating the cover image or the description image and there is no doubt. 
The only other question is whether it would be clearer to be able to update all the different types of image on a single page but I believe that with the addition of the carousel and multiple image uploads for the cover, this might get a little confusing.

@Cleop In answer to your questions, the venues should be able to upload up to 4 images https://github.com/club-soda/club-soda-guide/issues/58 (which I will update into #28 as well)

**Comment by nelsonic** [comment]
@Cleop I feel the question of "_which elements **can** be **modularised**_" should be flipped 
and instead we should ask "_which elements **cannot** be modularised_?".

To which the answer is: ***everything*** can (_and should_) be modularised into a **re-useable solution**. 
Which we then only need _minor_ customisation to make work for the client project.

Given the lower (_**`priority-4`**_) of this issue, and the _higher_ priority of the example issue: https://github.com/dwyl/image-uploads/issues/46 I suggest that you _temporarily_ shift your focus to working on the _generic_ example and then _apply_ the knowledge to the _client_ project. 

If you have _any_ questions, please ask them in: https://github.com/dwyl/image-uploads/issues
We _must_ build a _re-useable_ image upload solution including _amazing_ UX. 
Your sketches are _good_ and you are moving in the _right direction_.
All I would _encourage_ you to do is widen your perspective on _understanding_ how this problem can be _generalised_. Solve the _generic_ problem _first_ and then apply it to the _specific_ issue.

**Comment by Cleop** [comment]
**The venue page now has a carousel feature which occurs when there is more than one image uploaded for that venue. Clicking the arrows on desktop or swiping on mobile change which image you are viewing:**
![image](https://user-images.githubusercontent.com/16775804/52701003-16b0b480-2f71-11e9-9ebf-c54f6eaa3f31.png)

**The venue uploading process now has previous of the existing image and labelled images so you know which image you are uploading:**
![image](https://user-images.githubusercontent.com/16775804/52700821-c174a300-2f70-11e9-8c51-c5d9c6fea14a.png)
![image](https://user-images.githubusercontent.com/16775804/52700910-e9640680-2f70-11e9-84b7-2aa2309297aa.png)

On brand pages image uploading is done for one image by clicking on the place on the page where the image exists. This is either on the top cover photo area or next to the text:
![image](https://user-images.githubusercontent.com/16775804/52701348-f2090c80-2f71-11e9-9d8e-d7148345b16b.png)

![image](https://user-images.githubusercontent.com/16775804/52701340-eb7a9500-2f71-11e9-89a2-76c7475539fc.png)

**Comment by Cleop** [comment]
I am closing this as these requirements have now been met.
