### ISSUE TITLE
Drink cards on venue pages display more details

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#32]
As a customer on a venue page,
I'd like to click 'more detail' on the drink card and see more information about the drink,
so I can find out the dietary information / ABV and read a description of the drink.

**Comment by jussi-club-soda** [comment]
I think this is a low priority thing - the most important thing is to link these cards to the brand pages!

**Comment by iteles** [comment]
I believe this is now in place with the information on the back of the drinks cards!
