### ISSUE TITLE
Clickable venue type pill?

### ISSUE THREAD

**Issue by SimonLab** [club-soda/club-soda-guide#321]
ref: https://github.com/club-soda/club-soda-guide/issues/264#issuecomment-452613146

![screenshot 2018-12-18 at 15 01 53](https://user-images.githubusercontent.com/8418748/50162314-f00a3080-02d5-11e9-8f0c-8746c0d6d282.png)

Should the pills be links to the search venues page with the type venue selected matching the pill?

**Comment by jussi-club-soda** [comment]
nice to have? but lower priority
