### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#330]
We don't currently have a 404 page, which would be useful.

As a site admin
I would like to have a 404 page 
So that any visitors that come to a dead end on the site are easily able to make it to the page they were looking for.

@ctrembath @jussi-club-soda Any preferences on wording or content for this?

**Comment by ctrembath** [comment]
@iteles yes definitely want to have a 404 page.

Thinking it would be best if it used the hero homepage image.

The copy could be:

"Oops! That page could not be found."
[Return to Homepage] button

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/51032355-9d9bf700-1597-11e9-94b3-3d82bfd01080.png)
