### ISSUE TITLE
Clicking anywhere on a drinks card should show more details

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#334]
As a user viewing a drinks card
i'd like to click anywhere in the card to be shown more details
so it's easy to engage with the details

## Acceptance Criteria
- [x] Clicking anywhere within a drinks card shows more details

**Comment by SimonLab** [comment]
The current "More Details" link is using a checkbox and a label to apply the correct classes to the html element (ie hide or show the details div). We can reuse the same logic and apply the label to the all section of the drink card and not only to the link. This allow us to avoid using javascript or to add more state and messages to the Elm drink model.
![image](https://user-images.githubusercontent.com/6057298/51245940-082aa980-1981-11e9-86fd-07deff9a0a79.png)

**Comment by Cleop** [comment]
@SimonLab - I think you may not have applied these changes to all versions of the drinks cards. The drinks cards on the brand page (using the html template) cannot be clicked anywhere.

**Comment by Cleop** [comment]
I can fix this in the html only version using css so that you can click anywhere on the font of the card to flip it, however you cannot click anywhere on the back to turn it back to the front. Only if you click 'Close'.

**Comment by iteles** [comment]
@cleop Relevant commits for the _back_ of the card should be linked to _this_ issue: https://github.com/club-soda/club-soda-guide/issues/335

**Comment by Cleop** [comment]
Oh great, in that case this issue will be resolved with this commit 👍
