### ISSUE TITLE
Clicking the more details section should show front of drink card (Image)

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#335]
As a user viewing more details in a drinks card
I'd like to click anywhere in the 'more details' section and be shown the front of the drinks card
so I'm able to easy toggle between the front and back of the card

## Acceptance Criteria
- [x] Clicking anywhere in on the 'more details' card closes the card

**Comment by Cleop** [comment]
https://github.com/club-soda/club-soda-guide/issues/334#issuecomment-457229728

I don't think the back of the card on the html versions of the drinks card are clickable e.g. on the brands page.

@SimonLab - I can't determine from your changes which bits are controlling the back of the card clicking. Can you point them out or suggest anything?
