### ISSUE TITLE
Filter displaying duplicate drink type

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#336]
As a user filtering the drinks
I'd like to see the only only of each drink type in the menu
so I'm not confused by the filtering system

## Acceptance Criteria
- [ ] Opening the filter menu should only show one of each drink type to filter from

## Screenshot
![screenshot 2019-01-10 at 11 16 29](https://user-images.githubusercontent.com/8418748/50965391-bc33bc80-14c9-11e9-9ca3-f16a3bfe5bc5.png)

**Comment by SimonLab** [comment]
This is due to a typo, the first beer start with a space.
Admins can now edit/delete types and styles, see https://github.com/club-soda/club-soda-guide/issues/307#issuecomment-452675192

**Comment by jussi-club-soda** [comment]
Yep this should have disappeared after we cleaned the data!
