### ISSUE TITLE
Filtering Venues displays no venues

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#338]
As a customer viewing the venues page
I'd like to filter the venues by venue type
so I can see only one type of venue

## Acceptance Criteria
- [x] Filtering by venue type shows results of correct venue type

## Screenshots
![screenshot 2019-01-10 at 11 29 17](https://user-images.githubusercontent.com/8418748/50965805-fce00580-14ca-11e9-8bc0-53fa48b2e782.png)

**Comment by SimonLab** [comment]
This will be fixed with #333
