### ISSUE TITLE
Venue drinks should be ordered by type

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#340]
As a user viewing a venues drink offering
I'd like to see a heading for each drink type 
So I know what types of drinks the venue serves

## Acceptance Criteria 
- [x] Venues drinks are ordered by drink type
- [ ] Drink cards come under the correct drink type heading
- [ ] Title and icon appear as the heading

## Screenshot from @harrygfox wireframes
![screenshot 2019-01-10 at 12 17 21](https://user-images.githubusercontent.com/8418748/50968006-b510ac80-14d1-11e9-9556-c95f55fb0a3d.png)

**Comment by iteles** [comment]
@ctrembath Having this displayed in this way could create quite a lot of (unnecessary) scrolling, particularly on mobile. Would you prefer to use this as a starting point or shall we start with something like a coloured tag on the drinks card, having them all together as we have now but ordered by type?

**Comment by iteles** [comment]
@jussi-club-soda Any thoughts on the above?

**Comment by jussi-club-soda** [comment]
I think some ordering by type at least would be good - at the moment everything is just in a random list which isn't super neat...

**Comment by Cleop** [comment]
Now grouped by type.
