### ISSUE TITLE
Newsletter banner should be correct size / shape

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#341]
As a customer viewing the newsletter banner on the homepage
I'd like the shape of the banner to not be cropped
so the page looks the way it was designed

## Acceptance Criteria
- [x] Newsletter banner should look as it does in the wireframes (not be cropped)

## Screenshot from wireframe
![screenshot 2019-01-10 at 12 22 07](https://user-images.githubusercontent.com/8418748/50968247-5f88cf80-14d2-11e9-9b49-51bc2078dd65.png)

## Screenshot from staging-site
![screenshot 2019-01-10 at 12 22 48](https://user-images.githubusercontent.com/8418748/50968280-7cbd9e00-14d2-11e9-9533-4acad2241f15.png)

**Comment by Cleop** [comment]
This is to do with a set height on the `bg-newsletter` class. The issue only seems to occur on wider screens which I can replicate on my laptop by changing the viewing percentage of my browser. I will shortly be in the office where I will test it on a monitor and with a 15' laptop.

**Comment by Cleop** [comment]
This issue cannot be avoided at all pixel densities. @ctrembath - what device/monitor were you using?

I can change the height of the image at different breakpoints but this would be a lot of work to do on an infinite scale. I will paste a screenshot in here of what it looks like on a 15' 2000px laptop.

**Comment by Cleop** [comment]
at 1920px:
![image](https://user-images.githubusercontent.com/16775804/51613852-52c99a00-1f1c-11e9-8bdb-e146eeb6a20c.png)

**Comment by ctrembath** [comment]
@Cleop thanks for explaining. I'm using a 13inch macbook air with chrome
