### ISSUE TITLE
Description formatting on Venue Page

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#345]
As a venue adding my venue description
I'd like my description to have the correct background colour
so my venue page looks as good as possible.

## Acceptance Criteria
- [x] Venue description should have no background colour (inline with wireframes)

## Screenshot
![screenshot 2019-01-10 at 13 49 25](https://user-images.githubusercontent.com/8418748/50972448-949b1f00-14de-11e9-8d7e-8cb61c5a9655.png)

**Comment by Cleop** [comment]
Font size, line height and font family were already correct. The only thing that needed adjusting was the background colour which I've now done:

![image](https://user-images.githubusercontent.com/16775804/51027544-1a73a480-1589-11e9-8632-37585c62ae2e.png)

**Comment by ctrembath** [comment]
@Cleop - has this change been deployed to staging?

**Comment by Cleop** [comment]
@ctrembath - not yet, I'll pop into please-test once it has been.

**Comment by jussi-club-soda** [comment]
Cool!
