### ISSUE TITLE
Brand pages should be correctly formatted

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#347]
As a customer viewing a brand page
I'd like to see a page with a considered UX
so I know how to navigate the page

## Acceptance Criteria
- [ ] Non-member brand pages should contain 3 left aligned links inline with the description
- [ ] The links should be 'Drinks' 'Places that Serve' ' Where to Buy'
- [ ] Clicking the links should scroll you to the anchor point

## Screenshot
![screenshot 2019-01-10 at 14 01 25](https://user-images.githubusercontent.com/8418748/50973296-6e767e80-14e0-11e9-8aaf-f1c998a9416a.png)

**Comment by iteles** [comment]
@ctrembath We agreed this wasn't needed: https://github.com/club-soda/club-soda-guide/issues/132#issuecomment-438248371

**Comment by ctrembath** [comment]
@iteles thanks for updating me - I'll close the issue
