### ISSUE TITLE
'Venues Nearby' should show at the bottom of a venue page

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#348]
As a customer viewing a venue page
I'd like to see a 'Venues nearby' section
so I can continue to browse venues in the area

## Acceptance Criteria
- [x] Venues nearby should show 4 closest venues to the location of the venue page the user is currently on
- [x] Venues nearby should be inline with @harrygfox design
- [x] Title should be "Venues Nearby" instead of "Nearby Hotspots"

## Screenshot
![screenshot 2019-01-10 at 14 07 45](https://user-images.githubusercontent.com/8418748/50973568-2146dc80-14e1-11e9-9cde-cfcb689b647f.png)

## Question
@iteles this seems to have been missed out of all venue pages, OR is it within another card I've missed?

**Comment by iteles** [comment]
@ctrembath We had a bit of a debate over this functionality on one of our calls - I'll have a look in the backlog but we agreed to start without this for now as there were some questions about how venues would feel about having other venues 'advertised' on their page.

Happy to revisit this conversation next week but I'd suggest we lower the priority to a 4 or 5 for now 👍

**Comment by ctrembath** [comment]
@Cleop what is the maximum distance another venue has to be from the venue to be pulled into 'Nearby Venues' ?

**Comment by Cleop** [comment]
@ctrembath - at the moment this is set to 30km

**Comment by ctrembath** [comment]
@cleop - this should be limited to 4 venues - ordered by distance (inline with wireframes)

**Comment by Cleop** [comment]
@ctrembath - it should be limited to 4 venues already, can you share an example with me so I can debug this if it's not?

Re 'ordered by distance', again, this should be the case. Is this not working or are you saying that you would not like any limit placed on how far those venues can be so they could be over 30km away but they will still feature under the 'nearby' section?

**Comment by ctrembath** [comment]
@Cleop it happens on https://club-soda-guide-staging.herokuapp.com/venues/rochester-castle-n16-0ny

![screenshot 2019-02-01 at 17 49 29](https://user-images.githubusercontent.com/8418748/52140258-3202f200-264a-11e9-9095-0eef7ff9a6e5.png)
