### ISSUE TITLE
Create navbar

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#35]
As a customer visiting the Club Soda Guide,
I'd like to see a top-bar containing links to the Drinks page, Venues Page, 'List a Venue' CTA and Logo - which links to the homepage,
so I know what pages are available for me to browse

- [x] CS logo
- [x] Drinks
- [x] Venues
- [x] List a Venue

**Comment by jussi-club-soda** [comment]
The 'List a venue' could actually be 'For venue managers' or similar, since the link presumably takes you to the sign up/log in too?

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/46664922-39dde880-cbba-11e8-82b3-38b2dfed9e28.png)

**Comment by Cleop** [comment]
@jussi-club-soda - the text of the logo (pink on orange background) doesn't pass accessibility standards, do you have an alternative you'd like us to use?

I noticed this all black version:

![image](https://user-images.githubusercontent.com/16775804/46665058-97723500-cbba-11e8-8780-30be06bec2e4.png)

Although I know you wanted to give the pages a certain energy and feel, so please say/share any other colourful versions you wish to use.

**Comment by jussi-club-soda** [comment]
Yes, we should have an alternative logo - that one with the text doesn't really work here... It could even be in the updated homepage version from Laura (but will need to check that)

**Comment by iteles** [comment]
New logo from Laura:
![guide logo transparent](https://user-images.githubusercontent.com/4185328/47021374-3e267a80-d153-11e8-8bd2-2fa3b6a396d4.png)

**Comment by iteles** [comment]
@jussi-club-soda This is ready to test, but please note that #194 also captures the next evolution of this.

**Comment by jussi-club-soda** [comment]
All good, just one small UX question: the red box around "List a Venue" - this could be a bit confusing for users. We've already had one person wanting to nominate a venue actually fill in the listing form, thinking that was the thing they were meant to do. I know this comes from Harry's designs, but maybe worth a discussion?

**Comment by iteles** [comment]
@jussi-club-soda I entirely agree, this is great feedback form your users themselves 🙌 
I would suggest that we close this issue and open a separate issue focusing specifically on this navigation item with the `user-feedback` label 😊
