### ISSUE TITLE
Venue types should be singular, not plural

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#350]
As a customer on the homepage viewing a venue card
I'd like to see the venue types as singular ('restaurant', 'bar')
So the tags make sense

## Acceptance Criteria
- [ ] Venue type tags should be singular

## Screenshot
![screenshot 2019-01-10 at 14 14 38](https://user-images.githubusercontent.com/8418748/50973980-20fb1100-14e2-11e9-86be-0b4d9725b5fb.png)

**Comment by SimonLab** [comment]
On the admin drink types, the values of the type can be updated:
![image](https://user-images.githubusercontent.com/6057298/50974221-a54d9400-14e2-11e9-8dc1-98faa92de478.png)


![image](https://user-images.githubusercontent.com/6057298/50974270-c3b38f80-14e2-11e9-9d9c-d52b25c12328.png)

**Comment by iteles** [comment]
@ctrembath This data was imported from the data sent to us by Club Soda but as @SimonLab says, it can also be edited by admins at any time.

**Comment by ctrembath** [comment]
@iteles i've updated this in staging / production.
