### ISSUE TITLE
Visiting the drinks page displays all drinks from the database

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#36]
As a customer visiting the 'drinks' page,
I'd like to see all the AF and Low A drinks on the Club Soda Guide,
so I can discover new drinks and find out information about each drink

## Acceptance Criteria
+ [x] All drinks are displayed in the drinks page when loaded
+ [x] Default order of each filtered page in search is the highest weighted drink first

Note: Secondary sorting not necessary at this stage (can be random)

**Comment by iteles** [comment]
@jussi-club-soda What is the first set of drinks you would like added to the site as sample content?

**Comment by jussi-club-soda** [comment]
@iteles how many would you like to have? just of one type, or several?

**Comment by iteles** [comment]
@jussi-club-soda Several would be great - something that spans a few different categories and types would be ideal as we are then able to test with slightly more realistic data.

**Comment by iteles** [comment]
@Cleop @Danwhy Starter drinks data here, from Jussi: https://drive.google.com/drive/u/1/folders/1auziXzdfkRQO1MWJt7AzAZrdfBak6glM

**Comment by iteles** [comment]
There is a bug here where this only works at the endpoint `search/drinks?drink_type=`.

+ The default endpoint needs to be `search/drinks` - no filters should be selected and all drinks should display
+ [ ] The 'Drinks' link in the nav bar should link to this endpoint
+ [ ] The 'View Selection' link under the drinks carousel should link to this endpoint
