### ISSUE TITLE
Filtering drinks by type

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#37]
As a customer on the drinks page,
I'd like to filter the drinks by type,
So I only see the drinks I'm interested in

**Comment by iteles** [comment]
@jussi-club-soda This seems to me like it might be the most natural filter for people to use and is featured quite prominently on the homepage as well.

However:
+ There is no priority label on it
+ It appears to be the same as https://github.com/club-soda/club-soda-guide/issues/45 which is a `priority-5`

Could you please clarify the priority of this filter?

**Comment by jussi-club-soda** [comment]
Hmm, I think #45 was only about the search bar (i.e. type in "beer" to find beers) which is sort of pointless if we have a good filtering system? I'll prioritise this as higher. @iteles

**Comment by iteles** [comment]
Understood, thanks @jussi-club-soda! I'll update #45 to make it a little more obvious.
