### ISSUE TITLE
Reduce number of query to check venue slug

### ISSUE THREAD

**Issue by SimonLab** [club-soda/club-soda-guide#371]
When creating a new venue the slug is created and check for uniqueness in the database. This is done with :
 https://github.com/club-soda/club-soda-guide/blob/8aa221e95988f21435a96bd914a3d8dd383c89d6/lib/cs_guide_web/controllers/venue_controller.ex#L43-L44

We can reduce the number of queries to the database to 1 instead of calling `get_by` twice

**Comment by Cleop** [comment]
PR closed, feel free to close this if you're happy @SimonLab 😊
