### ISSUE TITLE
Drinks can be filtered further by style

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#38]
As a customer who has filtered drinks by type:#37,
I'd like to filter my results by style,
so I only see drinks I'm interested in

**Comment by jussi-club-soda** [comment]
A few notes:
If I select Cider as the subcategory in Cider, that selects the whole Cider top category?

If a category includes any drinks of a subtype, ALL drinks with that subtype get pulled in, even if their main category is something else? For example there are "mixers" and "cordials" in the "Spirits & Premixed" category. That's also again some database cleaning for us to do with the subcategories.

**Comment by SimonLab** [comment]
@jussi-club-soda yes this issue is similar to the other one. I've created #186 for dealing with the new database structure for style and types, so it's more a "technical" issue for me
