### ISSUE TITLE
Add city/town to venue cards

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#386]
On the home page and in https://club-soda-guide-staging.herokuapp.com/search/venues

under venue photo we currently have venue name/postcode/venue type, for example:

Cordero Lounge 
BA11 1BS
Bar

It would be good to add city/town as well, since the postcodes aren't always the most useful indicators of locations - so the above would become:

Cordero Lounge 
Bath
BA11 1BS
Bar

**Comment by SimonLab** [comment]
the city name will be added with the PR #387 (text search on postcode and city)

**Comment by Cleop** [comment]
Cordero Lounge doesn't have a city listed in the address but other examples that do are displaying on the `search/venues` page:

<img src="https://user-images.githubusercontent.com/16775804/51473436-44d91500-1d74-11e9-8bc9-eb49b05246e5.png" width=200px />

However I have noticed that venues showing on the landing page and brands page don't currently list the city for some reason so I'm just updating that now...

**Comment by ctrembath** [comment]
The cities of a venue aren't showing on a venue card on the homepage
![screenshot 2019-01-25 at 15 40 25](https://user-images.githubusercontent.com/8418748/51755864-8d1b6e80-20b7-11e9-8cab-6dcd2a9fcf2f.png)

**Comment by Cleop** [comment]
Adding that in now: 
![image](https://user-images.githubusercontent.com/16775804/51970503-ffe96880-246e-11e9-8602-f398331a01f6.png)
