### ISSUE TITLE
Filter drinks by brand

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#39]
As a customer viewing all drinks,
I'd like to filter drinks by brand/s,
So I only see the drinks by the brand/s i'm interested in

**Comment by Cleop** [comment]
@ctrembath - you can currently do this in the search input so typing in 'Dalston Cola' will show all 'Dalston Cola' drinks but are you referring to a dropdown?

**Comment by ctrembath** [comment]
@Cleop - when I wrote this issue I was referring to brand (see wireframe screenshot). @iteles is this feature in scope?

![screenshot 2019-01-25 at 15 42 14](https://user-images.githubusercontent.com/8418748/51756014-ef746f00-20b7-11e9-931b-d95f456cafbe.png)
