### ISSUE TITLE
Sprint demo prep

### ISSUE THREAD

**Issue by Cleop** [club-soda/club-soda-guide#397]
**Landing page:**
- 'Use my location' functionality
-  Perform a search using a postcode e.g. SW17 7EB or a city e.g. London
- Drinks carousel new chevron assets
- Whole drinks card is clickable to swap sides
- Venue card default image when another one hasn't been added
- Venue card displays city (if provided)

**Venue page:** - go to venue 'Agenda'
- New default cover image
- If there are cocktails show card with # of cocktails on 

**Brands page:** - go to brand 'Dalston Cola'
- New colour banner based on drink type
- Fixed uploading a photo for brand image
- Products related to section for drinks of the same type
- Retailers, new supermarket links (must be a member for most links)

**Admin Dashboard:**
- styling tidy up

**Discount codes:**
- Add a retailer ie. DryDrinker or WiseBartender
- Then add a discount code
- Then visit a brand that has ticked 'sold by DD or WB' to see the code on the brand page

**404 page:**
- go to `/blah` 

### Staging demo:
**Static page:**
- From the nav go to the FAQ page to view the new styling

A number of these things can't be set up on staging as that requires editing the DB and we have reached our row limit. We can demo these things locally though.

**Comment by Cleop** [comment]
Closing as now complete 👍

**Comment by nelsonic** [comment]
Nice work @Cleop 👍
