### ISSUE TITLE
Filter Beer, Wine, Cider and Spirits by ABV

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#40]
As a customer viewing all drinks,
I'd like to filter Beer, Wine, Cider and Spirits by ABV levels: 0.05, 0.5, 1-2.5 and 2.5 - 8%,
so I only see drinks I am comfortable drinking

**Comment by iteles** [comment]
From @jussi-club-soda: The ABV drop-down: "0.05%" doesn't return anything, should it be 0% instead?

**Comment by Cleop** [comment]
>  0.05, 0.5, 1-2.5 and 2.5 - 8%,

was listed in the acceptance criteria which is why it was added but it may be that there are no drinks with that value yet... so the choice is ours as to whether it should stay or go.

**Comment by jussi-club-soda** [comment]
@Cleop Ah, I missed the details in this issue... As it is, it would also miss anything between 0.5 and 1%.
Can we change this to:

<0.05%
0.05% - 0.5%
0.51% - 1%
1.1% - 3%
3.1% +
