### ISSUE TITLE
Venue "City" misplaced

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#400]
Some venues have all their address info (other than postcode) in the first line of address field - leaving the second line (city) field empty.

From a quick look, this only seems to be an issue for the batch of "Lounges" venues @Danwhy uploaded (the "Cosy Club" venues in the same upload seem fine).

Examples:
https://www.clubsodaguide.com/admin/venues/albero-lounge-mk40-1ay/edit
https://www.clubsodaguide.com/admin/venues/allegro-lounge-b31-2nn/edit
https://www.clubsodaguide.com/admin/venues/valero-lounge-cm8-2bd/edit

**Comment by iteles** [comment]
Apologies @jussi-club-soda I must have missed the notification for this.

@Danwhy Did we encounter this problem in the data for any other uploads?

**Comment by Danwhy** [comment]
I think it is the case for the Cosy Club venues too. All the venues in that file just had an 'address' field, as opposed to the others which had the address separated out into individual fields. I managed to extract the postcode from each one, but city names are too irregular to do that programatically

**Comment by Danwhy** [comment]
This is the case for all the recent new venues too

**Comment by jessyclubsoda** [comment]
Is there anyway to change this other than manually? @Danwhy

**Comment by iteles** [comment]
Afraid not @jessyclubsoda 😕
If there was some consistency around the city names (a comma before each one and that was the only comma in the address, or they were all in the same city for example) we could write a script to do this programmatically. This is the approach we took with the post codes which @Danwhy was able to extract.
Unfortunately, having looked into it, it would seem that there is no real pattern that we can pick up on!
