### ISSUE TITLE
Filtering CS scores - round down

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#402]
As a customer searching for venues
I want to be able to see all the venues in my search, including those that have 'half cup' scores
So that I make sure I have the full choice of venues available to me.

## Acceptance Criteria
+ [x] Any venues with a half cup score, should appear when filtering for the full cup below that score, i.e. when a customer filters for 2 stars, any venues with **2.5** stars should _also_ appear in that search

**Comment by Cleop** [comment]
Once change has been merged in:

![image](https://user-images.githubusercontent.com/16775804/51607177-dc24a080-1f0b-11e9-8bee-a62800c34437.png)
