### ISSUE TITLE
Link wholesalers/retailers with drinks/brands

### ISSUE THREAD

**Issue by Cleop** [club-soda/club-soda-guide#407]
As an admin
I want to be able to link wholesalers/retailers with the drinks/brands that they stock
so that customers know where they can buy those drinks

Using the same dropdown that are used to connect venues and drinks.

![image](https://user-images.githubusercontent.com/16775804/51668941-41839a80-1fbb-11e9-944a-9cf800c56330.png)

So if you are happy with this flow @jussi-club-soda, just like with a venue, you will create a retailer as before and then click 'show' to add which brands/drink that retailer is connected with. Just like how you create a venue and then click to add the drinks it stocks to it.

- [x] Link retailers and drinks
- [x] Link wholesalers and drinks

**Comment by ctrembath** [comment]
I'm having issues testing this - see : https://github.com/club-soda/club-soda-guide/issues/401#issuecomment-457601558
