### ISSUE TITLE
Filtering by soft drinks or flavoured mixers removes 'ABV' filter option

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#41]
As a customer on viewing all drinks,
When I am filtering by drink type "Soft Drinks, I want the 'ABV' filter to disappear,
because soft drinks ABV is a grey area, so we won't be storing this information.

**Comment by SimonLab** [comment]
This could be done but I'm wondering if hidding the "ABV" button only when "Soft Drinks" type is selected will add value to the user experience or if it will confuse users.

The way to implement the feature will also be based on the name of the type ie "soft drinks". If for any reasons an admin decide to rename the type to something else the feature will be broken.
