### ISSUE TITLE
Venues social links should open in new tabs

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#415]
As a customer viewing a venues page
I'd like to click on a link and for it to open in a new tab
so i'm not taken away from the Club Soda Guide

## Acceptance Criteria
- [x] Clicking on a venues website, facebook, instagram, twitter link opens in a new tab

## Screenshot
![screenshot 2019-01-25 at 14 03 38](https://user-images.githubusercontent.com/8418748/51750444-0a3fe700-20aa-11e9-8624-10b3b375c1e2.png)

**Comment by Cleop** [comment]
@ctrembath - which version of the site were you using where this wasn't occurring? It has already been done on staging but has not yet been deployed to production.

I am reviewing other third party links to ensure they open in a new tab and have found that the social media links do not open in a new tab on the brands page. So I will go ahead and make any of those changes where I can find them.
