### ISSUE TITLE
Alignment of 'Was your visit...' text incorrect on venue page

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#418]
As a customer visiting a venue page
I'd like to see the "Was your visit to Alcampo Lounge not what you expected?" in the correct place
so the page doesn't confuse me

## Acceptance Criteria
- [ ] The "was your visit" and "let us know" items should be right aligned and directly underneath the social handles

## Screenshot
![screenshot 2019-01-25 at 15 32 09](https://user-images.githubusercontent.com/8418748/51755614-04043780-20b7-11e9-8428-317370ae129a.png)

**Comment by Cleop** [comment]
I'm having difficulty replicating this on my 13' laptop at 1280px by rescaling it to 1680px: 
![image](https://user-images.githubusercontent.com/16775804/51987366-41dbd400-249a-11e9-8e1f-ac646e19965c.png)

@ctrembath - can you share what device/browser you were experiencing this bug on?

**Comment by iteles** [comment]
@Cleop I think this may have been related to something else that was fixed because I checked the bug when it was raised and now I no longer see it on my laptop or desktop screens! 👍
