### ISSUE TITLE
Incorrect images are showing for drinks in production

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#419]
Searching heineken in production is displaying a drink with an incorrect image
![screenshot 2019-01-25 at 15 51 00](https://user-images.githubusercontent.com/8418748/51756542-2f882180-20b9-11e9-9725-70073ce54258.png)

**Comment by iteles** [comment]
Looks like we're still coming up against #239 and this hasn't been resolved yet.

Closing as a duplicate but will add a comment in that issue too, thanks for raising @ctrembath  👍
