### ISSUE TITLE
Venues admin & listings page showing blank on  staging

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#420]
@SimonLab Could this be related to the data deleted this morning for #411 ?

Going to the admin venues page on  staging gives me an internal server error (https://club-soda-guide-staging.herokuapp.com/admin/venues)
![image](https://user-images.githubusercontent.com/4185328/51759511-4c742300-20c0-11e9-88d1-46f296d87699.png)

Clicking on the venues page gives me a blank page (looks like a slug issue):
https://club-soda-guide-staging.herokuapp.com/search/venues
![image](https://user-images.githubusercontent.com/4185328/51759552-631a7a00-20c0-11e9-8d7b-7c7e055c6001.png)

Searching for a venue from the search bar on the homepage also gives me a blank page. I searched for both 'Dishoom' and 'SW4' and got the same result.

**Comment by Cleop** [comment]
I think the same one has impacted Retailers admin view

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/51799732-f7015880-221c-11e9-9e20-813f0beff829.png)
![image](https://user-images.githubusercontent.com/16775804/51799735-ff599380-221c-11e9-910d-19c434a2ffac.png)
Fixed by @SimonLab 🎉 

Now we still need to rework the social media script that caused the issue and then rerun it again.

**Comment by Cleop** [comment]
I've found that where the social media urls were not being replaced/updated that the existing fields were being replaced by nil. This was because of a couple of missing `else` statements. I've added these and am now trying to test that there are no other outstanding bugs.

**Comment by Cleop** [comment]
The good news is that I've run my updated social media script on a copy of the latest staging data and it appears to be fine. Website urls and social media urls (existing or newly generated by the script) are appearing fine.

What appears to be breaking the `search/venues` page is the creation of retailers. I think this is also linked with issue #401 and wholesalers which is also erroring. I am going to look into this further now.

**Comment by Cleop** [comment]
The venue types table is showing two versions of each type (a plural and singular version):
<img src="https://user-images.githubusercontent.com/16775804/51843029-1c1fc500-230a-11e9-9453-fe22753ce4e6.png" width=160px />
I'm not sure what the reason for this is but I think it may be involved in the bug.

**Comment by iteles** [comment]
@Cleop That may well have something to do with the recent venues uploaded. Originally, the uploads all had the types as plural, see https://github.com/club-soda/club-soda-guide/issues/350

One to ask @Danwhy for confirmation please!

**Comment by Cleop** [comment]
@iteles - yes the creation of retailers uses the plural method but it's when I change the type from 6 to 9 or plural to single that it hides from the search/venues as it should be. So somehow the search/venues elm is expecting the single version not the plural.

@Danwhy @SimonLab - do you recall making any changes to this logic or area of the data?

**Comment by iteles** [comment]
@Cleop See @ctrembath's comment on https://github.com/club-soda/club-soda-guide/issues/350#issuecomment-453475419, she changed all the data on staging and production to be single.

**Comment by Cleop** [comment]
@iteles - do you think I should update the readme to indicate that certain types (I need to double check, it may be all venue types) shouldn't be edited by admins because this may break some of the logic on the site?

**Comment by iteles** [comment]
@Cleop Yes please. We should then look at how to prevent this in future.
