### ISSUE TITLE
Apply multiple filters on the drinks page

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#43]
As a customer on the drinks page,
I'd like to apply both the 'drink type' filter and the 'brand' filter,
so I can nail down the exact product I'm looking for

**Comment by iteles** [comment]
'Brand' filter is marked as a `priority-4` #39 so has not yet been built in, but this can be tested with the `Type` #37 and `ABV` #40 filters for now.

**Comment by ctrembath** [comment]
This feature is working great.
My only observation is that when a user has selected a filter the selection box should be coloured (see attachment) 

![screenshot 2019-01-25 at 13 40 20](https://user-images.githubusercontent.com/8418748/51749332-fe065a80-20a6-11e9-9502-1d3a84694088.png)

**Comment by Cleop** [comment]
By selection box @ctrembath - do you mean the 'drink type' box in this example?
![image](https://user-images.githubusercontent.com/16775804/51898908-d286b700-23a9-11e9-9c73-aafb01ba2e44.png)

Because colouring the 'beer' or 'wine' boxes as per examples may be misleading because ticking the broader category box means you want to include all results for that drink type, thereby making the ticking of a sub category like 'amber ale' redundant because it won't narrow or change the results whilst you still have the broader category ticked.

We can however colour the 'drink type' box. Should this just be when the dropdown is open or should it be once there is a filter selected for that dropdown?

**Comment by iteles** [comment]
@Cleop That's exactly it, it's about the user knowing which filters are in action and then the 'pills' will tell them what the filters are 👍

**Comment by Cleop** [comment]
Needs `bg-cs-navy`, `b--cs-navy` and `white` and to remove `b--cs-gray`, `bg-white`, `cs-gray`

**Comment by SimonLab** [comment]
@Cleop I've created a PR on elm-criteria which will allow us to apply some specific styles depending on the state open or close of the dropodown, see https://github.com/dwyl/elm-criteria/pull/19.
Once this version is deployed I'll update the styling

**Comment by Cleop** [comment]
Thanks @SimonLab and thanks for the call 👍

**Comment by SimonLab** [comment]
@Cleop I've open a PR for the drink type/style button : https://github.com/club-soda/club-soda-guide/pull/431

I'm not sure if the other "normal" dropdowns style need to be updated too?

**Comment by Cleop** [comment]
My assumption is that they do for consistency, however you wouldn't really be able to see it because of the way the dropdowns display:

<img src="https://user-images.githubusercontent.com/16775804/52043420-8e292180-2537-11e9-9605-e747a04af36f.png" width=300px />

What do you think @iteles?

**Comment by iteles** [comment]
@cleop @simonlab Agreed, it would need to be the same for consistency on all the drinks filters - you will see the blue background once the selection has been made. 

This does raise questions around the pills and the ABV but that’s not a blocker for now; I’ll have a look through the other issues and open an issue on it if necessary.

**Comment by Cleop** [comment]
@iteles - I think I understood the navy differently, @SimonLab has made it only appear when the dropdown is open. We thought the pills were the representation of the fact that that filter has been applied? Sorry @SimonLab perhaps you need to change this to be when a filter has been applied...

**Comment by iteles** [comment]
@cleop @simonlab Yes, sorry, I think we’ve understood the requirement differently. Let me have a think about it and confirm 👍🏻

**Comment by iteles** [comment]
I've had a look at the designs and run through the text above again and it would seem that the requirement is for the drop-down title to be dark blue when clicked as you suggest @cleop. 

I don't entirely see the use case for this when there are only 3 or 4 filters (or less) and there is not really a way to get confused about which one you have opened, but if it's a requirement as @ctrembath noted in https://github.com/club-soda/club-soda-guide/issues/43#issuecomment-457576202 then let's go ahead and get it done 👍 

We'll need to do this for:
+ Drinks page:
  + [ ] ABV filter
  + [ ] Drink type filter
+ Venues page
  + [ ] Venue type filter
  + [ ] Club Soda Score filter

**Comment by SimonLab** [comment]
The css rules to style dropdowns (option and select html tags) are basic and often done by the browsers.
We could use the property `focus` to apply some style to the dropdown but it's not really what we want and I don't think It's possible to apply css dynamically (when the dropdown is open/close) to the dropdown without using javascript.

I'm going to see how we could use javascript for adding the navy colour to the button when open

**Comment by ctrembath** [comment]
@iteles I think it would definitely be worth having all filter drop-downs as custom.
