### ISSUE TITLE
Fever-Tree brand page missing

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#435]
https://www.clubsodaguide.com/brands/Fever-Tree

gives an "internal server error" on production and staging - all other brands seem to be ok?

**Comment by Danwhy** [comment]
The problem was due to Fever-Tree having the hyphen in its name, the url being formatted with hyphens instead of spaces caused it to error. It's been fixed for now, but we need a better solution in case other brands with hyphens are added in the future.

**Comment by iteles** [comment]
@jussi-club-soda This can be tested in staging: https://club-soda-guide-staging.herokuapp.com/brands/Fever-Tree
The fix will be deployed to production when we deploy staging.

I  have opened #437 for a longer term solution.
