### ISSUE TITLE
Allow brands and venues to have hyphenated names

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#437]
As  per https://github.com/club-soda/club-soda-guide/issues/435#issuecomment-459426751, we need to be able to support hyphenated names for brands and venues.

## Acceptance Criteria
+ [x] A brand with a hyphen in the name will still have a brand page displayed (unlike the case in #435)
+ [x] A venue with a hyphen in the name will still have a venue page displayed (unlike the case in #435)
+ [x] A drink with a hyphen in the name will still have a venue page displayed  

~+ [ ] The hyphen will be treated as a space for purposes of the URL, e.g. `Fever-Tree`'s URL will end in `/Fever-Tree` and not `/Fever--Tree`~

@jussi-club-soda Will this be the case for drinks as well?

**Comment by jussi-club-soda** [comment]
I can't think of a drink with a hyphen in the name, but probably a good idea to future proof them as well!

**Comment by SimonLab** [comment]
- The url of the venue is using a slug so the hyphen isn't a problem in this case

**Comment by iteles** [comment]
@SimonLab I see what you're saying: we need to be able to use hyphens predictably so that we can use the  URL to get the name of the brand/venue from the URL. Currently we convert hyphens back to spaces, so if we were to have `Fever-Tree`, it would convert back to `Fever Tree` and would not be recognised as a brand name.

Agree with implementing underscores so that we know to convert these back to hyphens for now and we  can discuss with @jussi-club-soda when he's back 👍

**Comment by SimonLab** [comment]
We are now using slugs for brands
