### ISSUE TITLE
Update to Alog 0.5.0

### ISSUE THREAD

**Issue by SimonLab** [club-soda/club-soda-guide#450]
linked to: https://github.com/dwyl/alog/issues/30
and https://github.com/club-soda/club-soda-guide/issues/76#issuecomment-460216455

I have updated alog to the lateset release (version 0.5.0) unfortunately on the drinks page an error occurs `nil.name` doesn't exists. I've tested with the previous version of alog `0.4.1` and the page is ok.
This might be due to an issue related to Ecto and microseconds: https://github.com/dwyl/alog/issues/37
The newest alog version order items based on the `updated_at` value and not `inserted_at` we might have some conflicts in the date.

It can also be an issue with the links to one of the drink.

**Comment by SimonLab** [comment]
The error is due to a drink ("Lima") without a brand:
https://github.com/club-soda/club-soda-guide/blob/a7d95752c3144cacbcce800d5420d9bd210e52a8/lib/cs_guide/resources/drink.ex#L110

**Comment by SimonLab** [comment]
Solution:
So the error is not Alog (which is good!) but a few values of drinks with the a combination of `updated_at deleted and entry_id` which are not correct.

We can write a script (sql or elixir) to:
- find all the entry_id where a drink is deleted
- For each of these entry_id, find all the item with this entry_id but not deleted
- If the id of this non deleted item is lower than the id of the deleted item set the value for deleted to true

**Comment by SimonLab** [comment]
Now looking at fixing the tests on https://github.com/club-soda/club-soda-guide/pull/448

**Comment by nelsonic** [comment]
Version of Alog updated: https://github.com/club-soda/club-soda-guide/blob/434bd12d835e974d5182c76ea12ce5b3c8418586/mix.exs#L46
