### ISSUE TITLE
Discount codes not showing up on production

### ISSUE THREAD

**Issue by Cleop** [club-soda/club-soda-guide#451]
@jussi-club-soda - in order for discount codes to show for DryDrinker and WiseBartender you must first create those retailers in the admin section.

I did this on staging but do not have production admin login details:
![image](https://user-images.githubusercontent.com/16775804/52410780-6a368480-2ad1-11e9-89e7-6d1b2e98d2af.png)

Once the retailers exist then the codes will show up.

Please let me know if you'd like any more information/ help on how to do this on production.

**Comment by jussi-club-soda** [comment]
see #452 - some bug preventing setting these up...

**Comment by SimonLab** [comment]
error: 
![image](https://user-images.githubusercontent.com/6057298/52415377-b936e680-2ade-11e9-928e-0c06137992d5.png)

**Comment by Cleop** [comment]
@jussi-club-soda - have you set up the retailers in the `admin/retailer` section on production as I said above?

**Comment by jussi-club-soda** [comment]
Good point! Turns out I can't seem to be able to set them up either - press Save and nothing happens..

**Comment by Cleop** [comment]
Thanks, I will take a look into this

**Comment by Cleop** [comment]
I've got discount codes working on production for Heineken, however there are still a couple of bugs to resolve:

![image](https://user-images.githubusercontent.com/16775804/52420109-4a12bf80-2ae9-11e9-9622-205ffa37373f.png)

- Due to the way retailers and discount codes are set up, you will see a duplicate of wisebartender/drydrinker when you currently list a discount code. I need to remove this duplicate.
- There is also currently a bug on deleting a discount code, so the discount code on the bottom of the list on admin when clicked will show an internal server error, this is because I tried to delete it but it wasn't deleted successfully:
![image](https://user-images.githubusercontent.com/16775804/52420237-94943c00-2ae9-11e9-803f-c2daa5e7dc75.png)

**Comment by Cleop** [comment]
![untitled_artwork 4](https://user-images.githubusercontent.com/16775804/52425691-6cf6a100-2af4-11e9-8b13-1680ccf4dfb7.png)

**Comment by SimonLab** [comment]
@Cleop (and @jussi-club-soda ) I have a few questions to recap and help me to understand the user/admin flow

- 1 Are discount code only apply to retailers or can they also be applied to wholesalers or even venues?
- 2 Can a same discount code be applied to multiple retailers?
- 3 Can a retailer have multiple discount codes?
- 4 When a discount code is linked to a retailer does it applied to all the drinks of this retailer?
- 5 At the moment when we create a brand we can define where this brand is sold:
  ![image](https://user-images.githubusercontent.com/6057298/52472147-85b19600-2b8a-11e9-9a61-9d4d8c4fea5d.png)
  Are these checkboxes all retailers or wholesalers?

**Comment by Cleop** [comment]
1. Discount codes are only applied to DryDrinker or WiseBartender, no other retailers/wholesalers.
2. Currently no
3. Only one will display, so whichever is the latest one is what is displayed but in principal you could create lots in case you wanted to delete your latest one (e.g. a Xmas code) and use your regular code later.
4. A discount code is not applied to drinks, just a brand because it displays on the brand page.
5. The checkboxes are special columns for these popular brands in the brands tables e.g. `sold_sainsburys` = `true`, these are different to other smaller retailers that can be created at the admin/retailers endpoint where a retailer is a name, website and venue_type retailer.

**Comment by SimonLab** [comment]
Thanks @Cleop (some of the answers can be found at #217, I should have search for this issue first).
I think the error comes from the UI mixing different source of data: we have the "true" value for the "sold on Wisebartender" and also another type of data (Retailer) representing the link between brand a retailer and discount code.
So I think
- all the "sold on" values should be a retailer or a wholesaler and these values will be displayed dinamically instead of being hardcoded
- For each of the sold on value you can select if it's sold there but also if the discount code of the retailer applies to the brand

**Comment by Cleop** [comment]
If wisebartender has a discount code with club soda, it will apply to all brands that wisebartender sells through CS. So there's no need for:
> if the discount code of the retailer applies to the brand

**Comment by Cleop** [comment]
For your first bullet point:
> all the "sold on" values should be a retailer or a wholesaler and these values will be displayed dynamically instead of being hardcoded
- What would this look like on the backend? a table to link the brand id with the retailer id?

**Comment by Cleop** [comment]
The issue on production is now resolved:
![image](https://user-images.githubusercontent.com/16775804/52476245-f1e5c700-2b95-11e9-8b77-fdb45d68b14c.png)

Apologies, in my haste I somehow thought it was broken when it wasn't. I am going to update the docs to make sure it is clear how to add a retailer with a discount code.

There is a bug which is that it is possible to display WB or DD twice so I'm going to ensure this doesn't happen.

**Comment by Cleop** [comment]
Note: this is now suitable for testing on staging only (it has not been deployed to production)

**Comment by jussi-club-soda** [comment]
Cool, seems to be working! @Cleop just worth noting in the user guide, that even though the code is the same ("CLUBSODAVIP") for both DryDrinker and WiseBartender, we have to create two discount codes (one for each shop).

**Comment by Cleop** [comment]
Thanks for your comment @jussi-club-soda - I have updated the docs to make a note of this.
