### ISSUE TITLE
"Where to Buy" doesn't separate online and physical shops 

### ISSUE THREAD

**Issue by Cleop** [club-soda/club-soda-guide#452]
@iteles shared with me from @jussi-club-soda that 
> "Where to Buy" doesn't separate online and physical shops 

@jussi-club-soda please could you clarify for me how you'd like this section to look. This is how it currently looks:

### Staging Heineken:

![image](https://user-images.githubusercontent.com/16775804/52411043-49226380-2ad2-11e9-99db-383cfdf2290a.png)

This is what the invision designs looked like:
![image](https://user-images.githubusercontent.com/16775804/52410955-fea0e700-2ad1-11e9-8b0f-e9e334186439.png)

**I don't think we've discussed separating physical and online retailers yet**, especially **as some can be both online and physical.** We could amend the wholesaler / online & instore titles to look closer to the designs. I'm not sure if you want amazon/drydrinker and wisebartender in a separate part?

I think the key here is thinking about the average number of retailers (online and otherwise) for most brands. The designs look nice and divided up when there are a handful of results for each title, however I think it would look a bit empty to customers if there's only one thing under each title. 

This is why for the meantime I've not divided it up further. It tends to be the kind of thing that is better to implement at the point you think things are getting too busy, not before then otherwise things look over complicated for what they are and a bit empty.

**Comment by jussi-club-soda** [comment]
Thanks @Cleop I think you are right actually - I just had in my mind that they would be separated...

I tried to add a discount code, and got an "Internal server error" in production - any idea why?
