### ISSUE TITLE
Styling tweaks on backs of drinks cards

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#459]
The backs of the drinks cards are looking good (aside form the right margin bug) but I suggest a tiny bit more polish to take them to  the next level:

![image](https://user-images.githubusercontent.com/4185328/52423488-230bbc00-2af0-11e9-8ba7-cecdb4d1d07f.png)

## Acceptance Criteria
+ [x] Fix the grey area on the right of the card (the whole card should have a white background with no internal vertical grey lines) - this only appears to be an issue on desktop
+ [x] Adjust the line height to increase readability of longer texts
+ [x] See what can be done to guarantee a little padding  between types and sub-types in the rare situations where both the type and sub-type of drink are long, i.e.  `Spirits & pre-mixed` coupled with `pre-mixed drink` and `Tonics & Mixers` coupled with `Tonic Water` (this is in the screenshot above  and is only an issue in desktop, on tablets and phones, the words fall to the next line) - across standard desktop, tablet and phone size; note that it's probably preferable to have  a little bigger margin between them at all times than to risk having none
+ [x] Suggestion: Style the ABV text on the back of the card in the same way it is styled on the front - as we don't have the additional dietary information as had originally been considered in the designs for the cards, this suggestion is based on adding a little visual interest and breaking up the card
+ [x] Check ratio of height to width of drinks cards on tablet - these looked a little elongated to me but could do with some user testing when we're in the office!

**Comment by Cleop** [comment]
@iteles - remind me what device/browser you were using where it displayed the grey lines on the right?

This is what I see on my laptop on Chrome (one of these cards is scrollable, the other isn't):
<img src="https://user-images.githubusercontent.com/16775804/52490743-55cfb600-2bbd-11e9-8abd-5a831e9339da.png" width=200px />

**Comment by Cleop** [comment]
This is the narrowest it now goes on desktop before 'Tonics & Mixers' goes on to a new line: 
![image](https://user-images.githubusercontent.com/16775804/52558734-374f0200-2deb-11e9-8726-c155619fa7c5.png)
<img src="https://user-images.githubusercontent.com/16775804/52558804-6feedb80-2deb-11e9-9985-bf7f1695e876.png" width=200px />

**Comment by Cleop** [comment]
**Mobile:**
<img src="https://user-images.githubusercontent.com/16775804/52559952-c3aef400-2dee-11e9-897f-19cb2450b9a3.png" width=300px />
**Tablet:**
![image](https://user-images.githubusercontent.com/16775804/52560109-2bfdd580-2def-11e9-814e-f542e9535b04.png)
**Desktop:**
![image](https://user-images.githubusercontent.com/16775804/52560037-fbb63700-2dee-11e9-8fe3-b827828487da.png)

@iteles - are you happy with these ratios? (obviously they'll slightly differ according to device model)

**Comment by jussi-club-soda** [comment]
My only question on this is the scroll bars - most drinks don't have enough text that they are needed, but they show up on all of them (greyed out). How feasible would it be to lose them from drinks that don't need it?

**Comment by iteles** [comment]
@jussi-club-soda Which browser are you seeing the scroll bars in? (I no longer see them on Chrome on my Mac)

**Comment by Cleop** [comment]
@jussi-club-soda - I've never been able to reproduce the scrollbars bug. As @iteles said, more information on device/ browser would be really useful. I think it may be a default browser behaviour so we may not be able to do much about it...

**Comment by jussi-club-soda** [comment]
I have them on both Chrome and Firefox on a Windows laptop:

![image](https://user-images.githubusercontent.com/43003062/53351498-4bc9e900-3919-11e9-9d5c-e7c3788f57e1.png)

and on Laura's Mac/Chrome

**Comment by SimonLab** [comment]
I think the scroll appearance is linked to the browser type (user agent)
Instead of using `overflow-y-scroll` we can try `overflow-y-auto`

**Comment by nelsonic** [comment]
@jussi-club-soda thanks very much for sharing this screenshot, _very_ helpful! 👍 
@Cleop do you have access to a Windows machine to debug this? (_if not @SimonLab can you help?_)
(_the Y-scroll does not appear for any of us on Chrome Mac_)
![image](https://user-images.githubusercontent.com/194400/53409534-0b21ac80-39b9-11e9-912d-b9f1a59cb0c0.png)
Clicking "more details" on all of the drinks results in:
![image](https://user-images.githubusercontent.com/194400/53409587-30aeb600-39b9-11e9-863f-a73009a6658d.png)
(_no scroll bars..._)

So we need to debug/fix this on Windows.  e.g: add CSS [`overflow-y:hidden;`](https://stackoverflow.com/questions/3296644/hiding-the-scrollbar-on-an-html-page) to the card?

**Comment by SimonLab** [comment]
I've tested on my computer (linux firefox and chrome) and the scrollbar were displayed.
I think `overflow-y: hidden` will remove the scrollbar but also block completely the scroll.
I've created the following PR: #493 which I think solve the issue (at least on my computer) by using `overflow-y: auto` which only display the scrollbar when necessary.
the different values of the `overflow` properties can be found here: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow

![image](https://user-images.githubusercontent.com/6057298/53410831-d0ba0e80-39bc-11e9-9226-e0707c7025c2.png)

@Cleop if you can test my PR on your computer to double check that it works that would be great :tada:
