### ISSUE TITLE
Recognise carriage returns in venue description text

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#460]
As a venue manager, 
I would like to be able to have line breaks in my venue description text be recognised 
So that I can break up longer text and keep my readers interested in my content.

Description in the admin section contains a line break:
![image](https://user-images.githubusercontent.com/4185328/52429916-ded2e880-2afc-11e9-8607-b0194be8ebac.png)

Description on website does not (highlighting is mine, added in-browser for illustrative purposes):
![image](https://user-images.githubusercontent.com/4185328/52430100-3ec98f00-2afd-11e9-9e84-07604135b286.png)

**Comment by SimonLab** [comment]
Could we use https://hexdocs.pm/phoenix_html/Phoenix.HTML.Format.html to let Phoenix format the text to html?
> Two or more consecutive newlines \n\n or \r\n\r\n are considered as a paragraph and text between them is wrapped in p tags. One newline \n or \r\n is considered as a linebreak and a br tag is inserted.

**Comment by Cleop** [comment]
Thanks for sharing @SimonLab - I've had a play with the `text_to_html` fn but it is conflicting with our use of 'raw' for displaying ampersands as & not `&amp;`. I'm opening a SO question to go into more detail about the problem but if I don't get any SO responses my solution will be to filter and replace all instances of `\n` with `<br>`.

**Comment by jussi-club-soda** [comment]
Seems to work!
