### ISSUE TITLE
Bug: drinks cards don't flip over on mobile on the landing page

### ISSUE THREAD

**Issue by Cleop** [club-soda/club-soda-guide#465]
Bug: drinks cards don't flip over on mobile on the landing page drinks carousel (both on browser mobile inspection and on iPhone SE)

They do flip over on the search drinks page.

**Comment by SimonLab** [comment]
@Cleop this is due to the fact that the drink card is rendered for mobile and desktop:
```
    div [ class "relative" ]
        [ img [ src "images/up-chevron.svg", alt "left arrow", class "dn db-ns f1 b pointer absolute-vertical-center left-2 rotate-270 h1", onClick CarouselLeft ] []
        , div [ class "flex-ns flex-wrap w-90 center pv4-ns dn dib-ns" ]
            (renderDrinksCarousel model 3)
        , div [ class "flex-wrap w-90 center db dn-ns", id "carousel" ]
            (renderDrinksCarousel model 0)
        , img [ src "images/up-chevron.svg", alt "right arrow", onClick CarouselRight, class "dn db-ns f1 b pointer absolute-vertical-center right-2 rotate-90 h1" ] []
        ]
```
So we have a conflict in the ids of the drink card

**Comment by jussi-club-soda** [comment]
On my Android mobile now the cards flip over but the carousel isn't working - I can only see one drink on home page?

Also - we got rid of the chevrons here. How do people know that they can swipe to see more drinks?

**Comment by SimonLab** [comment]
@jussi-club-soda sorry I thought the carousel wasn't displayed on mobile, I'll add it back

**Comment by SimonLab** [comment]
@jussi-club-soda sorry I thought the carousel wasn't displayed on mobile, I'll add it back

**Comment by jussi-club-soda** [comment]
@SimonLab doesn't seem to work on my mobile yet?

**Comment by SimonLab** [comment]
@jussi-club-soda I've just tried on my mobile (firefox and chrome on android) and the drink card show the details section when clicked.
Could you try again on the landing page after refreshing the page? Which phone do you have? @Cleop do you mind checking on your iphone?

**Comment by jussi-club-soda** [comment]
Ok, working on staging now!

So production just needs a code update?

**Comment by SimonLab** [comment]
yes, we will need to deploy this fix on production :+1:
