### ISSUE TITLE
Production bug: New information on Old Mout brand not displaying

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#468]
**Production bug** from CS team:

Despite adding all the social media handles when editing the page info they don't reveal at all on the brand page when I save. The **option to add an image has also disappeared**, there is just text reading 'old mout' and no option to change the photo. 

The Heineken page seems to be functioning normally, so I'm not sure why this issue is occurring.

<hr/>

I looks like information that is _already_ being displayed on the page can be edited without any issues, but any of the new information doesn't show up.

**Comment by Cleop** [comment]
This is not a bug but I do need to update the documentation to explain this.

The member checkbox on the brands admin determines what displays for different brands:
![image](https://user-images.githubusercontent.com/16775804/52629535-c9b9d900-2eb1-11e9-8d72-36dc1538a8e5.png)

Old Mout is currently not a member and as a result the image and social media links do not display. However when I tick the member box it displays as usual:
![image](https://user-images.githubusercontent.com/16775804/52629509-ba3a9000-2eb1-11e9-926a-d0124c899476.png)

I have left Old Mout as a non member but feel free to change this if they are in fact a member.
