### ISSUE TITLE
Add buttons to CSV download options in dashboard

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#471]
As an admin
I would like to have the links on the dashboard that take me to actions look like buttons
So that there is a clear differentiation between these and the standard pages.

![image](https://user-images.githubusercontent.com/4185328/52586810-5b810200-2e30-11e9-9ef2-ea64f641a198.png)

**Comment by Cleop** [comment]
Opting for the mint coloured button:
![image](https://user-images.githubusercontent.com/16775804/52627898-4fd42080-2eae-11e9-9de4-b997f31c529e.png)

**Comment by Cleop** [comment]
@iteles - what do you think of these variations?

![image](https://user-images.githubusercontent.com/16775804/52630834-2f5b9480-2eb5-11e9-927e-821bd15a5305.png)
![image](https://user-images.githubusercontent.com/16775804/52631003-9c6f2a00-2eb5-11e9-9add-e37ce74dd47a.png)

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/52631401-9a599b00-2eb6-11e9-8947-4c3a1d872e02.png)

**Comment by iteles** [comment]
@Cleop Definitely this last one https://github.com/club-soda/club-soda-guide/issues/471#issuecomment-462718167, but adding a touch more description to the button names: instead of 'Download', 'Download brands' and so on 😊

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/52631562-02a87c80-2eb7-11e9-8a29-01192abe5c59.png)
To me this looks a bit more overwhelming? @iteles ?

**Comment by iteles** [comment]
@cleop I think you're right, it might be! Let's check with the Club Soda team 👍

**Comment by jussi-club-soda** [comment]
Hmm, I would almost have them the other way around: buttons for the admin pages, no buttons for the downloads - as the downloads are the less frequently used items?

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/53019181-12dad180-344c-11e9-96b1-42afd62afe5f.png)
