### ISSUE TITLE
Prepare staging database for scripts 

### ISSUE THREAD

**Issue by SimonLab** [club-soda/club-soda-guide#473]
The drinks page is not displaying correctly.
This is due to some testing drink element which don't have the correct information.

- [x] Create a copy of the staging database on localhost
- [x] Run the script `mix run priv/repo/change_social_media_handles_to_urls.ex` and logs the errors and ids of the drink
- [x] Update or delete the drink containing errors
- [x] Repeat the two previous steps with the script `priv/repo/add_brand_slug.exs`

- [x] Apply the same process with a copy of the production database (I have already tested this 2 scripts with this database but we need to make sure that it's still working properly)

**Comment by Cleop** [comment]
@SimonLab do you think this is also what is causing the drinks carousel on the staging landing page to break?
![image](https://user-images.githubusercontent.com/16775804/52628593-e9500200-2eaf-11e9-8f74-bfd8e8ee9a99.png)

**Comment by iteles** [comment]
Note: Using the search bar on staging or going to the drinks page on staging is also not working (presumably all linked to a drinks issue)

**Comment by SimonLab** [comment]
@Cleop I'm not sure, it's possible. Once the drink page is working we'll be able to see what are the errors with the carousel. At the moment I'm loading the data from staging in my localhost `pg_restore --verbose --clean --no-acl --no-owner -h localhost -p 5432  -U postgres -d cs_guide_dev ~/Downloads/cs-soda-staging` and run the migration. Now I'm going to run the script and log the errors. As it's staging I think it's ok to delete directly the faulty drinks.

**Comment by SimonLab** [comment]
I had to remove the "info" message on the console to see easily the script errors, otherwise it's difficult to spot. You can do this in `config/dev.exs` by replacing this line:
`config :logger, :console, level: :debug, format: "[$level] $message\n"` by
`config :logger, :console, level: :info format: "[$level] $message\n"`

And we have the following errors
```
{:error,
 #Ecto.Changeset<
   action: :insert,
   changes: %{drinks: [], venue_types: []},
   errors: [twitter: {"is invalid", [type: Fields.Url, validation: :cast]}],
   data: #CsGuide.Resources.Venue<>,
   valid?: false
 >}
{:error,
 #Ecto.Changeset<
   action: :insert,
   changes: %{drinks: []},
   errors: [
     twitter: {"is invalid", [type: Fields.Url, validation: :cast]},
     instagram: {"is invalid", [type: Fields.Url, validation: :cast]}
   ],
   data: #CsGuide.Resources.Venue<>,
   valid?: false
 >}
{:error,
 #Ecto.Changeset<
   action: :insert,
   changes: %{drinks: []},
   errors: [instagram: {"is invalid", [type: Fields.Url, validation: :cast]}],
   data: #CsGuide.Resources.Venue<>,
   valid?: false
 >}
{:error,
 #Ecto.Changeset<
   action: :insert,
   changes: %{drinks: []},
   errors: [twitter: {"is invalid", [type: Fields.Url, validation: :cast]}],
   data: #CsGuide.Resources.Venue<>,
   valid?: false
 >}
{:error,
 #Ecto.Changeset<
   action: :insert,
   changes: %{drinks: []},
   errors: [twitter: {"is invalid", [type: Fields.Url, validation: :cast]}],
   data: #CsGuide.Resources.Venue<>,
   valid?: false
 >}
{:error,
 #Ecto.Changeset<
   action: :insert,
   changes: %{drinks: []},
   errors: [instagram: {"is invalid", [type: Fields.Url, validation: :cast]}],
   data: #CsGuide.Resources.Venue<>,
   valid?: false
 >}
```

**Comment by SimonLab** [comment]
Staging is now up to date, @Cleop could you double check that the carousel and the drink pages are displaying correclty? thanks.

checking now the production database

**Comment by Cleop** [comment]
Staging drinks carousel now working 👍 thanks @SimonLab 
![image](https://user-images.githubusercontent.com/16775804/52638252-7a7fa280-2ec9-11e9-9eaf-33251c5d94b4.png)

**Comment by SimonLab** [comment]
scripts updated and tested in staging and production duplicate databases
