### ISSUE TITLE
More info on pills for venue score

### ISSUE THREAD

**Issue by SimonLab** [club-soda/club-soda-guide#477]
As a customer on the Club Soda website filtering my search results,
I would like the 'pill' for the Club Soda Score to show more information than simply a number
So that I know what it is referring to when many filtering options are available.

  ![image](https://user-images.githubusercontent.com/6057298/52632906-b95a2c00-2eba-11e9-8460-7483fd0df66d.png)

Instead of displaying just the number of the score in the pill we can add "Score: 2"

**Comment by SimonLab** [comment]
looking like:
![image](https://user-images.githubusercontent.com/6057298/52633148-6cc32080-2ebb-11e9-8a7b-1fb1ecd7b7b8.png)

**Comment by jussi-club-soda** [comment]
cool!
