### ISSUE TITLE
Bug: image upload page on brand pages is erroring

### ISSUE THREAD

**Issue by Cleop** [club-soda/club-soda-guide#481]
![image](https://user-images.githubusercontent.com/16775804/52701226-a2c2dc00-2f71-11e9-8a9d-694e6d02eca9.png)

I'll take a look at to why this might be but I may check with you @SimonLab as to whether any of the changes you were making to the brand urls could have affected this.

**Comment by SimonLab** [comment]
The name of the brand is not use anymore when creating the endpoint (see #463). The upload photo templates for the brand were still using the variable "name" instead of "slug"

**Comment by Cleop** [comment]
Fixed, thanks @SimonLab
