### ISSUE TITLE
Swap places and/or break list: retailers and venues in brand page view

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#483]
For example https://www.clubsodaguide.com/brands/heineken

now has hundreds of listed venues, so a user would need to scroll through a lot to see the retailers - so, could we please:

 - [x] swap "Where to Buy" to come before "Places that Serve" 
 - [x] move "Find One Near Me" to be at the start of "Places that Serve" list rather than the end
 - [x] break the venues list somehow, with a "See more" button after the first 40 venues or something?

**Comment by Cleop** [comment]
How does this look to you for the moving of the 'Find One Near Me' button @jussi-club-soda ?
![image](https://user-images.githubusercontent.com/16775804/53431343-3f609180-39e8-11e9-915c-377128d01284.png)

**Comment by Cleop** [comment]
Notes to self:
- [ ] change 'see more' btn to be custom checkbox for displaying and hiding.
- [ ] Refactor filtering of venues into a function with order so there are no repeats and so I am slicing/chunking at the right place.

**Comment by jussi-club-soda** [comment]
Thanks @Cleop that looks good!

And yes, maybe 20 is a nice number to show, I'm happy with that!
