### ISSUE TITLE
Lost Mother Kelly's

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#488]
the manager of Mother Kelly's set up their venue twice, since they didn't add all of their drinks at once, and came back later so had to start again.

I just deleted the second instance (which was identical to the first as far as I could see) and now both have disappeared - when I go to the URL (https://www.clubsodaguide.com/venues/mother-kellys-bethnal-green-e29le) I get an internal server error...

Any thoughts? Can we recover it?

**Comment by Danwhy** [comment]
I've recovered the original venue. The problem was that both venues having the same name and postcode, meant they had the same slug, so when we visited the url it tried to load the deleted one. I'll have a quick look to see why this happened.

**Comment by Danwhy** [comment]
It looks like we've already added some logic to prevent duplicate venues, it's just that this one was added before then. So this shouldn't be a problem again, unless there are any more pre-existing venues

**Comment by jussi-club-soda** [comment]
Thanks @Danwhy ! Not sure what else happened, but now when I try to access https://www.clubsodaguide.com/admin/venues
I get an internal server error!

**Comment by Danwhy** [comment]
@jussi-club-soda Sorry about that, it looks like there were a couple more old versions of that deleted venue still lurking around. Should be fixed now!

**Comment by jussi-club-soda** [comment]
Marvellous! Cheers @Danwhy
