### ISSUE TITLE
Create endpoint for email validation

### ISSUE THREAD

**Issue by SimonLab** [club-soda/club-soda-guide#495]
The idea to verify the emails is to:

- Create a unique token specific to the new created user/venue. For that we can use [`Phoenix.Token.sign/4`](https://hexdocs.pm/phoenix/Phoenix.Token.html#sign/4) function. The token will contain **encoded** (not encrypted) data specific to the user so we need to be sure to not create the token based on confidential user information. We could use the uid of the user for example.

- Create the endpoint to verify a token, eg `/verify/email/{token}`. Call the [`Phoenix.Token.verify/4`](https://hexdocs.pm/phoenix/Phoenix.Token.html#verify/4) function to validate the token passed as parameter in the url. The verify function will decode the token and if it's still valid (do we want a limit on the token lifetime? This can be added as an option in the verify function) we get back the uid of the user.

- Get the user by uid (or the information we used to encode the token) and update the value `verified` to true in the database.

- When the user is verified we can log the user directly to the application by reusing the same authentication logic

Are there any other consideration/requirement for this `/verify/email` endpoint?

see also:
- Phoenix Token documentation page: https://hexdocs.pm/phoenix/Phoenix.Token.html
- "Adding an Email Verification Flow With Phoenix": https://dockyard.com/blog/2017/09/06/adding-email-verification-flow-with-phoenix
- https://www.quora.com/How-do-I-create-a-verification-link-in-web-development-that-can-be-used-during-Sign-Up

**Comment by nelsonic** [comment]
This is now captured in https://github.com/club-soda/club-soda-guide/blob/master/lib/cs_guide_web/router.ex#L45
