### ISSUE TITLE
Update production code

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#496]
Would today (4 March) be a good day to update the production code? I think everything in staging has been tested and is good to go?

**Comment by nelsonic** [comment]
@jussi-club-soda yes, today is a good day for a release to Production. 👍 

@Danwhy when you get a chance, could you please add a "Deployment" section in/below the "Dev Guide" https://github.com/club-soda/club-soda-guide#dev-guide with step-by-step instructions for deploy from staging to prod (_preferably from a Web UI perspective. i.e. minimise CLI use_). Thanks! ✨

**Comment by Danwhy** [comment]
I've deployed to production, and will guide the guide written today

**Comment by nelsonic** [comment]
Thanks @Danwhy! You're a ⭐️

**Comment by jussi-club-soda** [comment]
Thanks all! Also noticed on the Heroku dashboard that we have a lot of "Memory quota exceeded" time - see screenshot below. How come, and is this something to be worried about?

<img width="960" alt="heroku warning" src="https://user-images.githubusercontent.com/43003062/53751104-6fee7280-3ea3-11e9-96ab-a6660adf800e.png">

**Comment by Danwhy** [comment]
@jussi-club-soda Nothing to worry about, we get a memory spike when we run post-migration scripts on the site (We had to run the script to add the slugs for brands this time). It might ever so slightly slow the site down while it's actually running but only takes about a minute, but won't have any effect beyond that

**Comment by nelsonic** [comment]
@jussi-club-soda Thanks for sharing this screenshot. 
Yes, this is something _we_ (_the developers_) should be concerned with, 
but you should not worry about it; it will be resolved shortly. Please see: https://github.com/club-soda/club-soda-guide/issues/498

@RobStallion is busy writing up a _comprehensive_ guide to the Postcode Lookup work and will be refactoring some of it to ensure that the Cache is smaller. (_Given that CS is paying for the database,  the Postcode data can be stored in Postgres and only the popular queries kept in ETS with a check on memory usage to flush the cache._)

Please confirm that the topic of _this_ issue ("Update production code") is resolved.
Thanks! 👍
