### ISSUE TITLE
Logout: Admins and Venues can Logout

### ISSUE THREAD

**Issue by nelsonic** [club-soda/club-soda-guide#508]
In order to _test_ registration & login effectively we need to be able to _logout_.
(_this functionality was not in the original scope as no user has requested it_)

# Technical Acceptance Criteria

+ [x] when the user is logged in to the website a Logout button should be visible in the main menu. 
![club-soda-menu-mobile](https://user-images.githubusercontent.com/194400/55079543-4a185000-5094-11e9-80c4-95a270fb6d86.png)

  + [x] add "logout" link to /templates/layout/app.html.eex with `/session/delete` resource.
+ [x] When the "logout" is clicked the session should be destroyed
+ [x] Redirect to homepage after logout.
+ [x] Add automated test for this. ✅ 

@RobStallion please estimate this (_apply a label_) and get started when you can. thanks!

**Comment by RobStallion** [comment]
![image](https://user-images.githubusercontent.com/15571853/55094207-d6833c80-50ad-11e9-9024-09036b7557ef.png)

**Comment by nelsonic** [comment]
Thanks @robstallion ✔️
