### ISSUE TITLE
If applicable brand page contains amazon affiliate links

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#51]
As a customer on a brand page,
I'd like to see a link to buy the products on amazon,
so I can use a online retailer I'm familiar with.

For Amazon, to search for Big Drop Pale Ale for example, the URL is

https://www.amazon.co.uk/s/ref=as_li_ss_tl?url=search-alias=aps&field-keywords=big+drop+pale+ale&linkCode=ll2&tag=clusod0c-21

to change the link, just replace the four keywords with any other combination (clusod0c-21 is our affiliate ID which is obviously the important bit!)

We would like to automate this as much as possible to save admin time.

Acceptance criteria:
- [x] when linking a drink/brand to Amazon, an affiliate link URL is automatically created using the formula above, based on the brand/drink name
- [x] the affiliate link URL is displayed for the brand on their profile page
- [x] this is displayed for ALL brands (not just members)

**Comment by iteles** [comment]
Linked to #49

**Comment by Cleop** [comment]
>  the affiliate link URL is displayed for the brand on their profile page

@jussi-club-soda - in your example the affiliate link contained the keywords for the brand name and the drink name. If the link appears on the brand page, should it _just_ contain the brand name? Otherwise, what do we do in situations where there are several drinks stocked by a given brand that are sold on amazon?

**Comment by jussi-club-soda** [comment]
We agreed on the call to just use brand names here.

**Comment by Cleop** [comment]
For brands to be associated with Amazon there will be a checkbox on the brands form that can be checked to say 'is sold on Amazon'.

@jussi-club-soda - how would you like us to deal with brands that already exist? Should we default them to be 'true' or 'false' for being sold on Amazon?

**Comment by jussi-club-soda** [comment]
Yep, false for now is good. We'll need to check what's actually available there!
