### ISSUE TITLE
Add Ocado as a retailer

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#513]
Would it be possible to add Ocado in as a retailer in the same way we have for the other supermarkets e.g. so it does a search on their website for the brand clicked on?

**Comment by Cleop** [comment]
I can add ocado like the other supermarkets so it's a checkbox when you create a brand. This would then autogenerate a link when it's ticked on a brand's page which when click would take the user to ocado with the brand name searched for.

Just to note:  if you have set Ocado up as a retailer yet under `admin/retailers` then you will have to delete it so you don't get duplicates as those supermarkets are not the same type of listing as those found under `admin/retailers`.

**Comment by jessyclubsoda** [comment]
That sounds great!
