### ISSUE TITLE
Pulling data on drinks styles/types

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#517]
Is it possible to add in the data on what types and styles the drinks are so that when we download the full database we can see it in the doc? So we can see which drinks we might need to change when editing styles/types

**Comment by SimonLab** [comment]
Hi @jessyclubsoda is this issue a duplicate of https://github.com/club-soda/club-soda-guide/issues/76#issuecomment-475677932 ?
If yes you should be already be able to test it on staging.

**Comment by jessyclubsoda** [comment]
Ah yes sorry about that!
