### ISSUE TITLE
Extra drinks get added to venues

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#519]
I added a drink (Fentimans Dandelion & Burdock) to a venue (https://www.clubsodaguide.com/venues/the-cosy-club-exeter-ex1-1sg), and another Dandelion & Burdock got added at the same time (Think Drinks Dandelion & Burdock). So I had to delete the second one.

Same thing happened when I added an "Alkoholfrei" beer - two different brands with the same drink name got added.

**Comment by iteles** [comment]
@jussi-club-soda We’re having some trouble reproducing this issue so far. Have you seen this in staging at all or only noticed it in production?

**Comment by jussi-club-soda** [comment]
Doesn't seem to happen in staging. My bug was in production.

**Comment by iteles** [comment]
@jessyclubsoda Now that staging has been deployed to production, could you please test whether this issue can be close **in production** as @jussi-club-soda's bug was only present in production originally?
