### ISSUE TITLE
Internal Server Error received when trying to update static page

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#521]
Hey,

I've just been trying to update our FAQs on the static page section and whenever I try and update, it gives me an Internal Server Error. Wasn't sure if this was because the Browser Title box was being left empty but it's not a required field so didn't think that would be the case? Any thoughts about what I might be doing wrong?

**Comment by nelsonic** [comment]
Hi @jessyclubsoda thank you for opening this issue to report the error. 👍 

Could you please share the **`URL`** you were attempting to visit
and if possible, include a screenshot so we can diagnose the error faster.
> 💻See: https://www.take-a-screenshot.org 
> 💡Tip: you can _copy_ the screenshot to clipboard and _paste_ it directly into a GitHub comment.

Thanks. ✨

**Comment by jessyclubsoda** [comment]
Trying to edit on this URL https://www.clubsodaguide.com/admin/static_pages/Frequently-Asked-Questions

So when I click edit here:
![image](https://user-images.githubusercontent.com/49029914/55320953-5b84a200-5470-11e9-9b57-8ea3df4c6e12.png)

I get taken through to this page here but when I try and make a change to the body of the page:
![image](https://user-images.githubusercontent.com/49029914/55321008-79520700-5470-11e9-9f42-fca83d218ae9.png)

I get taken to this:
![image](https://user-images.githubusercontent.com/49029914/55321019-7f47e800-5470-11e9-9d3c-8359fa6c105a.png)

**Comment by jessyclubsoda** [comment]
Looking at this more closely, the bug appears to be that of making edits to a Static Page. I am able to create a new static page fine but I can't go back and edit it afterwards without getting an 'Internal Server Error' page

**Comment by jessyclubsoda** [comment]
I am also unable to delete a static page

**Comment by iteles** [comment]
Thanks for all the details @jessyclubsoda 👍

**Comment by RobStallion** [comment]
I have tested the edit static page functionality locally and it is working as expected. 

When testing in staging I am getting the same error as @jessyclubsoda was above. 

Going to look at the heroku logs and see what is causing this error.

**Comment by RobStallion** [comment]
```
no function clause matching in Ecto.Changeset.cast/4
(ecto) lib/ecto/changeset.ex:408
```

This is the error that is being logged on staging. Will check the update action on the static page controller to see what arguments are being passed into the changeset function

**Comment by RobStallion** [comment]
I have taken a copy of the staging database and I have managed to recreate the error locally now. This should  make debugging what is going wrong a little easier. 

I have been able to create a new static page and edit this page without any issue. I can also edit the brands static page. I am getting the error when trying to edit the **Terms and Conditions** page or the **FAQ** page.

**Comment by RobStallion** [comment]
Problem is coming from this line...
```
static_page = StaticPage.get_by([page_title: page_title], case_insensitive: true)
```

This is currently returning `nil` because the incorrect `page_title` is being passed in. 

The reason I was able to edit the **Brands** page but not the other 2 is to do with how the spaces are being replaced in the `page_title` variable.

Need to update the variable and tests to ensure that this works as expected.

**Comment by RobStallion** [comment]
@jessyclubsoda This should be working in staging now. When you have a moment would you be able to test it out? Thanks
