### ISSUE TITLE
SITE_URL bug

### ISSUE THREAD

**Issue by RobStallion** [club-soda/club-soda-guide#523]
Small bug with the `@site_url` variable. At the moment the site url variable is being defined as a module attribute which means that its value is set at compile time. 

This means that if the value is ever changed after the application is deployed that the new variable will not be used until the app is redeployed. 

This is not an issue in most cases but it is here. The `SITE_URL` env value was not set in heroku at the time that the application was deployed. This means the `@site_url` is `nil` now, despite the fact the the env value has been added since. 

Update the places that this is used in the code so that it gets the value when a function is called rather than at compile time.

**Comment by nelsonic** [comment]
@RobStallion thanks for noting/opening this issue and PR to fix it. 👍
