### ISSUE TITLE
Login button for venues

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#526]
As a venue manager,
I would like to have a login button in the top navigation bar so I can see where to login

**Comment by iteles** [comment]
@jessyclubsoda Would you like us to add some copy to the login page so that consumers understand it’s not for them when they land there?

**Comment by jessyclubsoda** [comment]
@iteles  Something like "If you manage a venue listed on the Guide, please login here" And then also maybe a link to the Forgotten Password page below the login box?
