### ISSUE TITLE
Venue account sign up

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#53]
As a venue,
I'd like to sign up with my email address and password, 
so I can get listed on the Club Soda Guide and attract mindful drinkers to my venue.

**Acceptance Criteria**
- [x] As a Venue I would like to enter my email address into a field
  + [x] when a new venue is created, automatically login the new user
- [x] As a Venue I would like to create a password
- [x] As a Venue I would like to confirm my password
- [x] As a Venue I would like to receive an email asking me to confirm my email address
  + [x] Clicking the link to confirm email address should:
    + [x] take the user to a page where they can define a password 
    > see: [examples/forgotten_password/web/controllers/password_controller.ex](https://github.com/dwyl/learn-phoenix-framework/blob/94db757d710ffd9de83e54cd01420c6be0b46867/examples/forgotten_password/web/controllers/password_controller.ex)
    + [x] automatically login the user
- [ ] Opt-in consent is obtained and if this box #82 
  - [ ] Friendly error message is displayed if consent checkbox is not ticked and venues cannot sign up 

@iteles, speaking with @jussi-club-soda after our call - the venue sign up with email/password might be less of a priority given that we expect venues to create their listing and not necessarily log back in. We believe it would be more useful to be able to send venues personalised email notifications.
Without log in details can you see a way that venues could update their stocklist / images / description?

**Comment by iteles** [comment]
Note: GDPR opt-in consent needs to be taken into consideration for acceptance criteria.

**Comment by Cleop** [comment]
The proposed venue sign up process is:

login details (email/password) > basic venue details > done?

**Other elements of the flow are:** adding more detail at a later date e.g. venue description/photo etc and adding drinks that the venue stocks.

- Is this flow for both venues and the public or just one?
- Should venues be able to add more detail straight away (how?) or how do they do this? How does this part of the flow not put off people who just wanted to help out with the basics e.g. public customer who won't fill in the extra detail?

**The minimum fields needed for a venue sign up user sign up stage:**
- email
- password

**Proposed other fields:**
- password entered twice
- email confirmation email

**The minimum fields needed for a venue sign up details stage:**
- Venue name
- Venue address (to check for duplicates/ if the venue already exists on the system)

**Proposed other fields:**
- Type of venue e.g. bar, pub etc. (I wonder how important these fields are and where the lines blur, e.g. is brewdog a bar or pub? How often do people search by venue type?)
- Phone number (I wonder what the relevance of phone number is over e.g. website)

**Intitial implementation:**

I feel that for the initial user sign up the email confirmation is not necessary. As Suhail Doshi, the Mixpanel founder suggests, it will create a large drop off of sign ups. Until spam etc. becomes a problem, at an MVP stage I would not suggest this is a priority. Not including it will improve conversion rates and free up developer time. We can test whether users are opposed to sign ups without this but this is my preferred implementation.

As for the venues, I'd be interested to know why type of venue and phone number have been chosen as initial fields to include and whether they can be optional.

**Comment by Cleop** [comment]
gov.uk style guidelines for forms advises:

<img src="https://user-images.githubusercontent.com/16775804/46301240-b4e14680-c59d-11e8-90ae-56e60c3184a2.png" width=400px />

The gov.uk guidelines are created with meticulous attention to accessibility and good UX.

We may wish to consider substituting the use of asterisks on mandatory fields for the wording 'optional' on non-mandatory fields.

**Comment by Cleop** [comment]
https://github.com/dwyl/the-book/issues/86#issuecomment-470929677
> We need to capture the full auth workflow for CS and that requires comprehensive wireframing.:

- registration
- email confirmation
- password set/reset
- login
- logout
- "delete my data" (GDPR Compliance)

**Comment by Cleop** [comment]
### Flow 1 - sign up
- **Registration** via email already exists. A user clicks 'List A Venue' and then inputs their email on adding the venue.
![image](https://user-images.githubusercontent.com/16775804/54277326-73f75000-4587-11e9-840a-99904b8bb872.png)
- Next the user receives an **email confirmation**, something along the lines of 
'Thank you for creating a new venue on Club Soda. So that you can add more details to your venue or keep it updated in the future, you will have a user login. Please now follow this link to set a password for your user login: http://.......' Exact wording tbc by @jussi-club-soda.
- Clicking the link takes a user to **password set** which would look like this:
![image](https://user-images.githubusercontent.com/16775804/54277759-a190c900-4588-11e9-92ef-0702037d3ecb.png)

### Flow 2 - existing users
- For **logging in/ out** there will be a new title on the navbar which will either display as 'Venue Login' or 'Logout' depending on whether the user is currently logged in. Exact wording tbc by @jussi-club-soda. When logout is clicked you will be logged out and redirected to the landing page. When login is clicked you will go to a login page ->
- Login page (exact wording tbc)
![image](https://user-images.githubusercontent.com/16775804/54278288-e23d1200-4589-11e9-968b-12e0725870ae.png)
- The 'forgot password?' link on the login page will send an email to the user which will get them to create a new password using the same steps as on initial set up.
- 'delete my data' will appear as a link in the footer, clicking on it will open up a text based page (that @jussi-club-soda can create using the static page creator). The page will describe what the policy for using people's data is and what people need to do to have their data deleted.)

@nelsonic - Do we need somewhere for logged in users to be able to click to have their data deleted automatically or is this more like an email request they will send to Jussi for the CS to perform? What do you think of my outline, is this what you had in mind?

**Comment by nelsonic** [comment]
@cleop this outline is good. In the first instance we don’t need to *build* anything for deleting data, as you suggest, simply having a static page informing people of how their data is protected and used (for improving the app/site) and an email address for requesting deletion is fine. 👍🏻

**Comment by RobStallion** [comment]
@jussi-club-soda If you would like venue owners to be sent an email allowing them to confirm their email address, we will need to set up AWS Simple Email Service (SES). 

I have logged in with the IAM user details you provided @Cleop previously but it appears that we do not have the permission needed to set this up. 

Would you be able to update our permissions, or if you like you can follow these steps...

### Amazon SES Setup

First you will need to sign in to your amazon account [here](https://console.aws.amazon.com/ses/).

Once you are signed in you should see a nav bar on the left of the screen.
Click on SMTP settings in the nav bar.

<img src="https://cloud.githubusercontent.com/assets/15983736/23793390/d9b88248-0582-11e7-9e89-15d6c84f688c.png" />

From this page make a note of your `Server Name` and `Port`.

Then click <img src="https://cloud.githubusercontent.com/assets/15983736/23793405/eb56697a-0582-11e7-8d27-27d07225250f.png" />

You may then choose a username, or go with the default name. On the
bottom right of the screen click "Create".

Click "Show User SMTP Security Credentials" and make a note of your "SMTP
Username" and "SMTP Password"

Next we need to authorise an email address for testing. Return back to the
[SES dashboard](https://console.aws.amazon.com/ses/).

Click on "Email Addresses" under "Identity Management" on the nav bar on the
left.

<img src="https://cloud.githubusercontent.com/assets/15983736/23793419/fd6c22a8-0582-11e7-9d79-42afd0521133.png" />

Click <img src="https://cloud.githubusercontent.com/assets/15983736/23793429/0c8d2188-0583-11e7-9c1e-8f4f41cee20b.png" /> and type in a real email address which you will use for testing your application

Check your email and click the validation link. If this has not shown up
immediately, double check you input your email correctly. It may take some
time but it is usually immediate.

Great! You are now ready to start building the application.

Before continuing, you should have made a note of the following:

* Server Name
* Port
* SMTP Username
* SMTP Password
* The validated email address

**Comment by jussi-club-soda** [comment]
All cool @RobStallion have set up the account - how do you want me to send you the details?

**Comment by RobStallion** [comment]
@jussi-club-soda Thanks for setting that up. I would move it to Europe yes. With regards to sending the details, you can send them to my dwyl email address.

**Comment by jussi-club-soda** [comment]
Done @RobStallion details in the google doc!

**Comment by RobStallion** [comment]
@jussi-club-soda When you have a spare couple of minutes, would you please read [this link](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html). It is instructions on how to upgrade your SES account from the "sandbox" (the sandbox is like a testing area that they give you initially but you can only send to verified email addresses using the sandbox). 

In order for us to be able to send emails to any venue owners we will need to complete this. 

After your case has been approved by Amazon, you will need to update the `SMTP_USERNAME`, `SMTP_PASSWORD` and `SES_SERVER` in the [google doc](https://docs.google.com/document/d/1DSEAL1gK820kaaggDeMPYEEt3Y9n3TV4-3Uj02AcQ60/edit).

Could you please also add the `verified email` to the google doc? This is the email address that will be sending the emails out.

**Comment by jussi-club-soda** [comment]
Thanks @RobStallion have just put in the request to AWS!

**Comment by RobStallion** [comment]
@jussi-club-soda @jessyclubsoda This issue can be tested now. 

Currently, until we get the new credentials for SES it is using a sandbox version that only allows for emails to be send to verified email address. 

If you wish, you can add any email addresses that you wish to test with to [this google doc](https://docs.google.com/document/d/1DSEAL1gK820kaaggDeMPYEEt3Y9n3TV4-3Uj02AcQ60/edit) which Jussi has access to. I will then add them to the verified list in SES to allow for testing.

I have also done a short screen recording to try and help with testing the feature. The file is on drive and I have shared it with @jussi-club-soda.

**Comment by jussi-club-soda** [comment]
Message from AWS:
Your new sending quota is 50,000 messages per day. Your maximum send rate is now 14 messages per second. We have also moved your account out of the Amazon SES sandbox.
This takes effect immediately in the EU (Ireland) region. You can view the current sending rate and sending quota for your account on the Sending Statistics page of the Amazon SES console, or by using the GetSendQuota API.

Have also just updated the credentials in the Google doc!

cc @RobStallion @jessyclubsoda

**Comment by RobStallion** [comment]
@jussi-club-soda Thanks for updating the doc with the info. I have just tested locally and they seem to be working as expected.

Update the staging area now so it should all be working now.

@jessyclubsoda you should now be able to go to the [forgotten password path](https://club-soda-guide-staging.herokuapp.com/password/new) and get an email sent to your address. 

Let me know if you have any problems or questions.

**Comment by jessyclubsoda** [comment]
All working for me!

**Comment by jessyclubsoda** [comment]
@RobStallion Will all new venues have to go down the Forgotten Password path to get a password or will it be an option to set up a password when you sign up?

**Comment by RobStallion** [comment]
@jessyclubsoda When a new venue signs up, they will be logged in automatically so that they can use the site as you would expect. They will also be sent an email at that time to confirm their account, which will take them the page to set a password. 

The only reason you had to go to the forgotten password path was because you had a venue set up before the email functionality was working properly (so you never received the email when your venue was created)

**Comment by jessyclubsoda** [comment]
@RobStallion Is the email confirmation to set up password all good to go too?

**Comment by RobStallion** [comment]
@jessyclubsoda Yeah that functionality is working and you should be able to test it in staging. I know you tried yesterday and didn't receive the email but it was before the credentials were changed. 

If you try setting up another venue now with a different email address you should receive the email to confirm your account 👍 

However, at the moment is the opt-in consent which is part of the acceptance criteria for this issue still needs to be completed. I know that this is being worked on at the moment in #82.

**Comment by jessyclubsoda** [comment]
Sorry one more question @RobStallion Will there be a login button at any point?

**Comment by nelsonic** [comment]
@ctrembath is there an issue, acceptance criteria or design wireframe indicating _where_ the Login button should be?

**Comment by jessyclubsoda** [comment]
@nelsonic No it doesn't look like we do. Can we just place it in the same place as where the 'Log out' button goes once someone is logged in?

**Comment by nelsonic** [comment]
@jessyclubsoda we _agree_ that placing the _login_ button in the Top Nav could be a good option.
It's worth having a dedicated issue for the Login button (_rather than including new requirements in the comments of this issue..._)
