### ISSUE TITLE
Duplicate venues in 'Venues Nearby' section

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#530]
Having some issues with duplicate venues. 

We had two versions of The Telegraph, deleted one but two still are coming up on a 'Venues Nearby' banner

![image](https://user-images.githubusercontent.com/49029914/55620775-9d288c00-5793-11e9-98b2-5712b4de9215.png)

Even though only one comes up if you search normally. Both links take you to the same page

![image](https://user-images.githubusercontent.com/49029914/55620760-8da94300-5793-11e9-83e8-8dcccbd54144.png)

Then with The Gable, there were also two, so deleted one. Again now only one comes up on the search. But similarly two options still come up on 'Venues Nearby'

![image](https://user-images.githubusercontent.com/49029914/55621251-e3cab600-5794-11e9-9348-d21f6e365a55.png)

Yet with this one, if I click on one of them (I assume the one I deleted) it gives me an Internal Server Error, whilst the other one takes me through to the normal page.

Any idea what might be going on here?

**Comment by jessyclubsoda** [comment]
We've also noticed similar duplicate venues for 'Slug and Lettuce St Mary Axe' and 'Yates Sheffield'

**Comment by RobStallion** [comment]
```ex
  defp venues_within_distance(distance, lat, long) do
    query =
      __MODULE__
      |> where([venue], venue.deleted == false) # this line is actually causing the issue as it filters the deleted venue entry allowing for a previous version of that venue to be returned to the user.
      |> where(
        [venue],
        fragment(
          "? @> ?",
          fragment(
            "earth_box(?, ?)",
            fragment("ll_to_earth(?, ?)", ^lat, ^long),
            ^distance
          ),
          fragment("ll_to_earth(?,?)", venue.lat, venue.long)
        )
      )
      # filters veunes that are within the given distance
      |> select([venue], %{
        venue
        | distance:
            fragment(
              "? as distance",
              fragment(
                "? <@> ?",
                fragment("point(?, ?)", ^long, ^lat),
                fragment("point(?, ?)", venue.long, venue.lat)
              )
            )
      })
      |> order_by([v], desc: v.updated_at)
      |> distinct([v], asc: fragment("distance"), asc: :entry_id)

    CsGuide.Repo.all(query)
  end
```

`Alog`'s approach is to use the main query as a subquery, and then filter out the deleted venues from that subquery. So something like this...
```ex
    query = from(m in subquery(sub), where: not m.deleted, select: m)
```

However, this is causing the following error...
```
ERROR 42601 (syntax_error): syntax error at or near "AS"
```
![image](https://user-images.githubusercontent.com/15571853/55810620-ccb2fd80-5adf-11e9-80e1-32050003022e.png)

I am going to remove the subquery aspect of this and simply filter the deleted results with the enum.filter function. 

This should have the exact same result.

**Comment by jessyclubsoda** [comment]
So thought this had debugged because it had for those venues but just had a look and we're still getting the same issue for Slug and Lettuce St Mary Axe

![image](https://user-images.githubusercontent.com/49029914/56031852-7e3c7380-5d18-11e9-9bee-f955a200273a.png)

Where it's coming up as a Venue Nearby even though when you click through that link it takes you back to the same page

![image](https://user-images.githubusercontent.com/49029914/56031892-99a77e80-5d18-11e9-9391-70ae99a7bf85.png)

Thoughts @RobStallion ?

**Comment by RobStallion** [comment]
@jessyclubsoda I will take a look at that asap. Just on another issue at the moment but I will update this to let you know what I find

**Comment by RobStallion** [comment]
I looks like there are to versions of `slug and lettuce, st mary axe`. Both are not deleted so that appears to be why it is displaying on the nearby venue list. However they both have the same slug so they will both link to the same venue view. 

```
===> : "slug-and-lettuce-st-mary-axe-ec3a-8aa"
===> : "slug-and-lettuce-st-mary-axe-ec3a-8aa"
===> : "5c71e7c0-e324-4343-90f5-fc3fef002ce2"
===> : "62fb08e1-95d0-4f8a-ae36-4a071f8edd60"
```

This also may be the reason that only one version shows up on the venue search page 

![image](https://user-images.githubusercontent.com/15571853/56213979-ec54a380-6054-11e9-98e7-142d4d11d341.png)

Looking into this in more detail now

**Comment by RobStallion** [comment]
@jessyclubsoda I deleted the venue and it appears to have solved the issue. 

![image](https://user-images.githubusercontent.com/15571853/56218843-8caec600-605d-11e9-80e2-b785ca727149.png)

Going to look into how two venues were created that had that same slug. Wondering if it has anything to do with the `,` (comma) that is in the name of the venue on the right.

**Comment by RobStallion** [comment]
@jessyclubsoda Can this issue be closed now as the issue was to do with duplicate venues. 

I will open a separate issue for capturing my thoughts on the duplicate slugs.

**Comment by jessyclubsoda** [comment]
Yes sure thing! I think @Cleop did some work so that slugs will no longer duplicate but I think we have a number of remaining ones on the Guide. I assume I can just delete the duplicates?

**Comment by RobStallion** [comment]
@jessyclubsoda Yeah that seems to be working as expected. That was how I resolved the issue locally 👍
