### ISSUE TITLE
Cookies pop up on landing page

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#534]
As a site admin
I would like there to be a cookies pop up on the home page for users to accept when using the website

As discussed here #82 I have now written a privacy policy, cookies policy, and Ts and Cs which I'll add to the website once the static pages bug has moved off of staging. However on top of this, would it be possible to add a simple pop up on our homepage for users to consent to? 

![image](https://user-images.githubusercontent.com/49029914/55726679-4a0b3f00-5a08-11e9-86af-d7de6b2195dd.png)

Something like this would be great

### Technical acceptance criteria

- [x] when pop up is clicked, add `cookie_accepted` to the session
- [x] Create plug which checks if there is a `:cookie_accepted` value in the session. 
  - [x] If so, hide the pop up
  - [x] if not, display the pop up
- [x] if user is logged in, check to see if user has been verified.
  - [x] If user is not verified, check `:cookie_accepted` value and follow steps above
  - [x] If user is verified, hide pop up

**Comment by iteles** [comment]
@jessyclubsoda I think the one in the screenshot below - with a 'learn more' link pointing to the cookie/privacy policy page you're writing for #82 - would actually be a little more elegant and easier to spot (the 'learn more' link is also a nice addition for GDPR).

We definitely need to update ours!

What would be your preference here?

![image](https://user-images.githubusercontent.com/4185328/55739120-58655500-5a20-11e9-84bf-c3e7154ff7d5.png)

**Comment by jessyclubsoda** [comment]
Yep that looks good! @iteles

**Comment by nelsonic** [comment]
@iteles / @jessyclubsoda is this story sufficiently captured for us to start work on it?
(_can the issue be prioritised_)

**Comment by jessyclubsoda** [comment]
I'm happy @nelsonic

**Comment by RobStallion** [comment]
@jessyclubsoda Are you happy with how this looks...

Desktop
![image](https://user-images.githubusercontent.com/15571853/56286378-75c9ab80-6111-11e9-85b5-50211f98d98f.png)

Mobile
![image](https://user-images.githubusercontent.com/15571853/56286413-8da12f80-6111-11e9-97dd-b99d04158b8e.png)

**Comment by jessyclubsoda** [comment]
Looks great!
