### ISSUE TITLE
HTML restrictions

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#535]
I'm aware there are some restrictions that have been placed on HTML within the back end - would I just be able to clarify what those restrictions are?

**Comment by iteles** [comment]
@jessyclubsoda We need to make this a little clearer in [our documentation](https://github.com/club-soda/club-soda-guide#user-admin-guide), we'll get it into its own section and add a little more detail.

At the moment we have this:
![image](https://user-images.githubusercontent.com/4185328/55736049-7b8d0600-5a1a-11e9-97f2-12fcee69b073.png)

In addition to standard font and styling HTML tags, you can also add in image tags `<img>`.

All other tags, such as `script` tags (which can often be malicious) and `iframe`s are sanitised out to prevent script injections.

Note that this is only for the static pages created by admins.
For all other input fields in the application such as venue description fields, we have disallowed HTML tags to ensure consistent styling across the board (there have been some subsequent tweaks to this, such as https://github.com/club-soda/club-soda-guide/issues/460).

**Comment by jessyclubsoda** [comment]
@iteles Thanks for this. Would it be possible to expand some of the styling HTML options whilst keeping out potentially malicious tags? For example if I want to build drop down menus/tables/number or bullet lists on my static pages?

**Comment by iteles** [comment]
@jessyclubsoda You should already be able to add in lists (bulleted and numbered) into your static pages but you'd have to style them yourself.

We didn't have tables as a requirements but could you try out a table and drop a screenshot into this issue please?

Lastly, with drop-down menus, I'm not sure I understand what the use-case would be for these within the body of a page, could you please give me an example use case?

**Comment by jessyclubsoda** [comment]
Bullets and lists doesn't seem to be working for me. I'm pretty new on doing code stuff but it seems to work here 
![image](https://user-images.githubusercontent.com/49029914/55739471-07099580-5a21-11e9-82ff-45d5a8517e0f.png)
But not here
![image](https://user-images.githubusercontent.com/49029914/55739498-14bf1b00-5a21-11e9-893c-51bfa472f434.png)

Not sure if this is me just missing something?

Tables not necessarily so useful but just thought it might be good for listing Cookies used. I can give that a go in a bit

Drop down menus I thought would be useful for our FAQs to have them as drop down depending on what kind of user you are, rather than having a longer page with large amounts of info not relevant to everyone

**Comment by iteles** [comment]
@jessyclubsoda Ah yes, it would make total sense for you to be able to use ordered and unordered lists, we’ll add that in as it’s a smallish change. 

For collapsible section (or accordion sections as they’re also known) the mechanism is considerably more complex as this is not just a case of allowing specific tags, there’s a fair bit of CSS or JavaScript that would have to be allowed for these which requires a rethink in how we have set things up altogether. 

I recommend you open and. Separate issue on the accordions for static pages and that is built separately as an upgrade once you feel your FAQ page size warrants it given user feedback 😊

**Comment by iteles** [comment]
@robstallion Assigning to you to build in:
+ [ ] Support for ‘<ol>’ and ‘<ul>’ tags on static pages
+ [ ] Default styling for these tags consistent with the site
+ [ ] Updating documentation accordingly

**Comment by jessyclubsoda** [comment]
I also seem to only be able to hyperlink mailto email addresses rather than any website. Is it possible to be able to use <a href> tags indiscriminately? @iteles

**Comment by RobStallion** [comment]
@jessyclubsoda `<a>` tags should work. 

```
<a href="https://www.google.com/">
Google
</a>
```

I'll try adding the above to one of the static pages on staging now

**Comment by jessyclubsoda** [comment]
Ah think this was actually a problem with copying and pasting my code! Ignore

**Comment by RobStallion** [comment]
I just added it to the link a link to google on the bottom of the FAQ page (I feel like there is a pun in there some where). Feel free to delete it if you're happy with it 👍

**Comment by jessyclubsoda** [comment]
The <ul and <li> tags seem to be changing the font-family embedded within the page

![image](https://user-images.githubusercontent.com/49029914/56129965-8c3dfe80-5f7b-11e9-9521-d15ee3d01bbd.png)

**Comment by RobStallion** [comment]
@jessyclubsoda Here are a couple screenshots of the updated styling to the `ul`/`ol` elements. Thought it may be more straightforward if I just show you a few shots and you can pick the one you prefer

The first has the exact same styling as the `p` tags...
![image](https://user-images.githubusercontent.com/15571853/56574286-c54d2300-65ba-11e9-8bda-59b04edffd01.png)

The second does not have as much spacing between the elements above and below it...
![image](https://user-images.githubusercontent.com/15571853/56574716-d8acbe00-65bb-11e9-8bbc-28c717db4bfb.png)

The third is with the bullet points shifted over to the right to be inline with the above element
![image](https://user-images.githubusercontent.com/15571853/56574769-f9751380-65bb-11e9-8d9a-d33fe35ce460.png)

I have only these changes locally at the moment. If you let me know which you prefer I will put that in staging for you.

**Comment by jessyclubsoda** [comment]
Third one looks best to me! Thanks @RobStallion
