### ISSUE TITLE
Admin ability to edit associated venue email addresses

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#545]
As an admin,
I would like to be able to add or edit the email address associated with a venue account
-----------------------------------
To set up logins for venues that are already on the Guide, we might need to add email addresses to venues that don't currently have them associated. In future, we also might need to edit the email addresses associated with venues in case of change of management/ownership etc.

**Comment by RobStallion** [comment]
I have been trying to solve this issue using `autoform` but I am currently having an issue. 

In the `venue_controller` the `edit` action currently looks like so...
```ex
  def edit(conn, %{"slug" => slug}) do
    venue = Venue.get_by(slug: slug) |> Venue.preload([:venue_types])
    changeset = Venue.changeset(venue)
    render(conn, "edit.html", venue: venue, changeset: changeset)
  end
```

If I update the `venue` variable to `preload` `:users` also, I can use `autoform` to add the email field to the form on the front end. 

The problem however is that the form is not loading the associated data. What I mean by this is if a venue has an owner and I go into the edit form the field email is left empty...

### venue controller 
```ex
  def edit(conn, %{"slug" => slug}) do
    venue = Venue.get_by(slug: slug) |> Venue.preload([:venue_types, :users]) # preloading users
    IO.inspect(venue.users, label: "====>")
    changeset = Venue.changeset(venue)
    render(conn, "edit.html", venue: venue, changeset: changeset)
  end
```

### log of venue users 
(removed most of the data in this log as I'm only interested in the email field in this case)
```
  users: [
    %CsGuide.Accounts.User{
      email: "rob+venue@dwyl.com",
      role: :venue_admin
    }
  ]
```

### Screenshot of the website with this info...
![image](https://user-images.githubusercontent.com/15571853/55951865-318d6580-5c50-11e9-8ab1-d67f0ca9ae27.png)

As you can see the email field is empty despite the fact that there is an associated user `rob+venue@dwyl.com`. 

Another issue is that `autoform` only appears to render the exact amount of inputs as the number of associated users. This means that we will never be able to add a more than the current number of associated users to the list without manually writing an input field. `autoform` does accept html to be given as an argument but this may involve more work, and be less understandable, than simply creating the form with [Phoenix.HTML.Form](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html).

**Comment by RobStallion** [comment]
I decided to take a different approach as I thought that the above would become confusing to users.

I decided to create new actions in the venue controller to handle adding and removing venue owners. 

## Technical acceptance criteria

- [ ] create route for viewing venues owners
- [ ] create route for removing the association between a venue and a user
- [ ] create route for adding user as a venue admin
  - [ ] check if email is a valid format
  - email is valid format
    - [ ] if email is valid check if user exists
    - user exists
      - [ ] check if they are already an admin of this venue.
      - [ ] if user is already venue admin do nothing
      - [ ] if user is **not** already this venues admin, create the association.
    - user doesn't exist
      - [ ] create new user
      - [ ] send user an email to let them know that they are a venue admin and to confirm their account
      - [ ] create association between new user and venue
  - email is invalid format
    - [ ] if email is not valid return error to admin
