### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#552]
As a sub issue of #548 

Our pages need meta tags and descriptions to make them amenable for SEO

**Comment by jessyclubsoda** [comment]
I've written meta-descriptions for some of our key pages 

<h2>To Do</h2>

- [ ] Add into <head> of .html

- [ ] Create pull request

@nelsonic Where can I find the code for the different pages?

**Comment by nelsonic** [comment]
@jessyclubsoda can you please clarify which pages you are attempting to update?
(_e.g: please list the `URL` and the `meta-description` here in the issue and I can help determine where each update needs to be made, that will also make it easier to maintain in future..._) 🌻

**Comment by jessyclubsoda** [comment]
URL | Meta description
-- | --
https://www.clubsodaguide.com/ | The Club Soda Guide is the UK’s first directory for low and no alcohol drinks, and the best places to find them.
https://www.clubsodaguide.com/search/drinks | Search from over 750 low and no alcohol drinks, including wines, beers, and spirits
https://www.clubsodaguide.com/search/venues | Find the best UK venues for low and no alcohol drinks near you and see what they stock
https://www.clubsodaguide.com/users/new | Sign up your venue to the Club Soda Guide to get your Club Soda score and allow our members to start finding you.
https://www.clubsodaguide.com/brands | Search for the best low and no alcohol brands, including wines, beers, and spirits
https://www.clubsodaguide.com/Contact | Get in touch with us by email or on social media
https://www.clubsodaguide.com/About-Us | Club Soda is a mindful drinking movement of individuals, drinks, and venues.
https://www.clubsodaguide.com/Frequently-Asked-Questions | Find out more about the Club Soda Guide, the UK’s first directory for low and no alcohol drinks, and how you can get involved.
https://www.clubsodaguide.com/brands/heineken | Heineken 0.0 is twice brewed and fermented with Heineken's unique A-yeast from natural ingredients with gentle alcohol removal and blending to achieve a fruity flavour and slight malty notes.
https://www.clubsodaguide.com/brands/old-mout | Old Mout Alcohol Free Berries & Cherries is a special blend of strawberry and raspberry with notes of blueberry.
https://www.clubsodaguide.com/brands/punchy-drinks | PUNCHY are an independent start up who make alcohol and non-alcoholic punch, and believe that whether you're drinking or not, you shouldn't have to miss out.
https://www.clubsodaguide.com/brands/shrb | /shrb... for the perfect non-alcoholic drink. The vinegar base gives it an alcohol-like kick, a rich flavour bouquet and very low sugar.
https://www.clubsodaguide.com/brands/genie-living-drinks-co | Genie Living Drinks produce delicious natural & vegan drinks that celebrate the brilliance of bacteria for a healthy gut.
