### ISSUE TITLE
Footer spacing

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#554]
As we add more static pages to the footer, the spacing goes a bit funny on both the desktop and mobile versions of the Guide

Desktop:
![image](https://user-images.githubusercontent.com/49029914/56577968-51b01380-65c4-11e9-96e6-6afe7ecaf9b1.png)

Mobile:
![Image-1](https://user-images.githubusercontent.com/49029914/56578026-7efcc180-65c4-11e9-900a-dcd8a9124dbc.jpg)

Is it possible to make this styling more consistent as more pages get added?

**Comment by RobStallion** [comment]
@jessyclubsoda how's this?

Mobile
![image](https://user-images.githubusercontent.com/15571853/56671252-391b2880-66ac-11e9-8023-b69abe466393.png)

Desktop
![image](https://user-images.githubusercontent.com/15571853/56671294-47694480-66ac-11e9-98a6-4d11ee6ef6bf.png)

**Comment by jessyclubsoda** [comment]
Looks great @RobStallion Cheers!
