### ISSUE TITLE
Recreate brands page so it is no longer a static page

### ISSUE THREAD

**Issue by RobStallion** [club-soda/club-soda-guide#557]
![image](https://user-images.githubusercontent.com/15571853/56659405-ed10b980-6694-11e9-8e1c-5cd981efb216.png)

There is currently a static page created for `/brands` on the staging site [here](https://club-soda-guide-staging.herokuapp.com/Brands).

Recreating this page so that it does not have to be manually updated.

**Comment by nelsonic** [comment]
@RobStallion can you remove the `/Brands` static page from staging to dedupe:
![image](https://user-images.githubusercontent.com/194400/56666528-00775100-66a4-11e9-8803-7054ac213687.png)
Thanks.

**Comment by RobStallion** [comment]
@nelsonic Done 👍

**Comment by nelsonic** [comment]
@RobStallion thanks for updating. 👍 

@jessyclubsoda please see: https://club-soda-guide-staging.herokuapp.com/brands

When viewed (logged in) as "Site Admin" you will see:
![image](https://user-images.githubusercontent.com/194400/56688846-9ecddb80-66d1-11e9-9aa5-7d41f9e96d60.png)

But when logged out (in an incognito window) you will see:
![image](https://user-images.githubusercontent.com/194400/56688916-c9b82f80-66d1-11e9-940e-00c96ec87799.png)

Having this page automatically generated by the database means it never needs to be _manually_ updated and is always up-to-date and alphabetically ordered. 

If you are happy with this page, please comment below and it will be included in the next release.

**Comment by jessyclubsoda** [comment]
This is great thanks guys!
