### ISSUE TITLE
Adding images to member brands

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#560]
I need to add images to our new member brands. On staging it gives me the option to upload an image on a member brand like so 
![image](https://user-images.githubusercontent.com/49029914/56676387-13931c80-66b6-11e9-9dcd-aefe857c3857.png)

But I can't do this on the live site even though this isn't a new piece of functionality that wouldn't have been moved from staging yet
![image](https://user-images.githubusercontent.com/49029914/56676455-3b828000-66b6-11e9-8ff6-a48c935493c1.png)

Any ideas where this functionality might have gone?

**Comment by iteles** [comment]
@jessyclubsoda Could you please give us a screenshot of the option you're seeing in staging that you're not seeing in production and the URL (web address) on which you're seeing it?

**Comment by jessyclubsoda** [comment]
The option is in the screenshot above - it's the 'Upload Photo' button in the top right hand corner in staging. It's not there in production. 

The relevant URLs are
Staging: https://club-soda-guide-staging.herokuapp.com/brands/heineken
Production: https://www.clubsodaguide.com/brands/heineken
