### ISSUE TITLE
Deployment of Latest Changes?

### ISSUE THREAD

**Issue by nelsonic** [club-soda/club-soda-guide#577]
Hi @jessyclubsoda given all the latest changes that have been made for image performance, etc.
Do you feel sufficient testing has been done on staging to promote the changes to Production?

Laura sent out an email: "Save the Date - Summer Mindful Drinking Festival in July"
![image](https://user-images.githubusercontent.com/194400/56972101-4c257100-6b62-11e9-9e32-3dc1422c0668.png)

It has links to the guide in it 
![image](https://user-images.githubusercontent.com/194400/56972437-e84f7800-6b62-11e9-95ed-4c5de8d88a3d.png)

and it might be good for those links to open as quickly as possible for people on Mobile ... 🤔 

LMK your thoughts/priority.
Standing by to deploy (_already took DB backup_)
https://data.heroku.com/datastores/a870534e-1277-4b9a-a487-0f10d551b7f3#durability
![image](https://user-images.githubusercontent.com/194400/56972390-cc4bd680-6b62-11e9-9287-6f06a6c9231f.png)

# Todo

+ [ ] Deploy latest changes (_including image optimisations and perf enhancements_) to production.

**Comment by jessyclubsoda** [comment]
@nelsonic Yep all good with me!

**Comment by nelsonic** [comment]
Done. ✅ 
![image](https://user-images.githubusercontent.com/194400/56972759-788dbd00-6b63-11e9-859f-1d71aa241e66.png)
![image](https://user-images.githubusercontent.com/194400/56972771-7e839e00-6b63-11e9-8a47-1eabc31d988f.png)

For anyone following along, see: [dev-guide.md#deployment](https://github.com/club-soda/club-soda-guide/blob/master/dev-guide.md#deployment)
