### ISSUE TITLE
Infinite scroll on drinks and venues page?

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#581]
As part of reducing our loading times for our venues and drinks pages I just wanted to check whether we have an infinite scroll on our drinks and venues page? In my browser it does look like it is continuously loading as I scroll down but wanted to check

**Comment by iteles** [comment]
@jessyclubsoda We implemented lazy rendering as part of [this issue](https://github.com/club-soda/club-soda-guide/issues/239#issuecomment-458932782) specifically to improve performance and deal with any problems that could have arisen so this is covered :+1:
