### ISSUE TITLE
Email addresses associated with venues

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#582]
Now we have log-in functionality, we need to make sure that there are email addresses associated with venues already on the Guide so that they can set up passwords

@iteles I know you're looking into this but just thought I'd make it an issue so we can all stay in the loop

**Comment by iteles** [comment]
@jessyclubsoda Rob and Nelson will be looking into this this week - can you provide us with the spreadsheets you made mention of in your email with the email addresses please?

**Comment by iteles** [comment]
@nelsonic @RobStallion Data for this issue:
https://drive.google.com/drive/u/1/folders/19rNmMgzb7EgL_r4UyZoWnNfgTyPZZmTb

**Comment by RobStallion** [comment]
Starting work on importing the email addresses from the csv files.

The Venue names for the cosy club venues is not correct on the csv file...
![image](https://user-images.githubusercontent.com/15571853/58031608-a9d12b80-7b18-11e9-8cf7-2ad6629e007d.png)

![image](https://user-images.githubusercontent.com/15571853/58031657-bd7c9200-7b18-11e9-90f7-a7c65f2c25ee.png)

They should have the location (town name) on the end. I will write a function to update the venue names with the town name. 

On my first pass over it, the information for the lounges looks good.

**Comment by RobStallion** [comment]
Going to start with the lounges first.

Followed the steps in the dev guide up until step 7. When I tried to run the script, it ran for a while and added 30 or so users then I got the following error...
```
(KeyError) key :postcode not found in: %{address: "34 Market Square, Witney, Oxfordshire 0X28 6BB", description: "Como Lounge is in a lovely spot, right on the beautiful market square opposite the historic Buttercross. We’ve full width windows (that open right out), so we’re a perfect spot for watching the world go by, rain or shine. We serve a great range of food and drinks (including full kids, gluten free and vegan menus) in a really lovely relaxed, welcoming space. Our jewel in the crown is something of a hidden gem, in our rather splendid roof terrace out the back. Oh, and see if you can find out the link between Witney, our stripy terrace walls and our hand-painted Native American Man. Clue: It’s not duvets.", drink_1: "Budvar B:Free", drink_2: "Brewdog Nanny State", drink_3: "Fentimans Sparkling Elderflower", drink_4: "Fentimans Rose Lemonade", drink_5: "Fentimans Ginger Beer", drink_6: "Fever-Tree Mediteranean Tonic", email: "como@thelounges.co.uk", facebook: "", phone_number: "01993 773 852", twitter: "https://twitter.com/LoungeComo", venue_name: "Como Lounge", website: "https://thelounges.co.uk/como/"}
```

It says that the error is coming from the following line...
```
(cs_guide) priv/repo/script_helpers.ex:53: CsGuide.ScriptHelpers.get_address_and_postcode/1
```

This is the get_address_and_postcode function...
https://github.com/club-soda/club-soda-guide/blob/6c2fc02cae68508363a821d50ad61c2a98721811/priv/repo/script_helpers.ex#L47-L54

I put a log in here of...
```ex
    IO.inspect(extract_postcode(venue.address))
```
to see which venue was causing the error and got the following...
```ex
["34 Market Square, Witney, Oxfordshire 0X28 6BB"]
```

This is a little hard to see but the error is being caused because `extract_postcode` is failing because the postcode is incorrect. It should be `OX28` but there is a typo of `0X28` (a zero instead of the letter in error). 

I will update this in the csv to resolve the error and run the script again

**Comment by RobStallion** [comment]
Got another error similar to above. `S014 3LG` should be `SO14 3LG`. Updating in the csv.

**Comment by RobStallion** [comment]
After changing the two postcodes everything appeared to run as expected against a copy of the database. Going to check the number of inserted records to ensure that it matches up with the number we were expecting from the csv.

**Comment by RobStallion** [comment]
All users look like they were created for the lounges. 116 new entries in the db match the number of records in the csv minus the headers. 

Moving onto the cosy club data

**Comment by RobStallion** [comment]
After creating a function to update the venue names from the cost club csv file, the function runs with no errors. Correct number of users added to the db.

### Next step

Run the files on production.

**Comment by RobStallion** [comment]
@jessyclubsoda Those users have been added to production now. You should be able to see them if you sign in as an admin and navigate to [this page](https://www.clubsodaguide.com/admin/users)
