### ISSUE TITLE
Venues can set a primary image

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#59]
As a venue creating my listing,
I'd like to choose my primary image,
so I feel happy with the image displayed in my venue card.

**Comment by Cleop** [comment]
Once https://github.com/club-soda/club-soda-guide/pull/454 has been merged we will have this on staging:
![image](https://user-images.githubusercontent.com/16775804/52481924-c8359b80-2ba7-11e9-866f-7ed17d76d597.png)

So users have the ability to upload up to 4 images, the first image they upload in the carousel is the one which will be used for their venue card.

**Comment by jussi-club-soda** [comment]
Great @Cleop ! And I think this also answers the question I was about to ask about *removing* venue images - a new one will override the old one?

**Comment by Cleop** [comment]
Yes @jussi-club-soda - new ones automatically update old ones.
