### ISSUE TITLE
Prioritising our member brands through our brand page

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#593]
As an *admin*, I would like to be able to make sure that our member brands stand out on our [Brands page](http://www.clubsodaguide.com/brands)

Here is a [simple wireframe](https://wireframe.cc/Awnly3) of how this page could look. 

**Requirements** for this issue

- [x] Ability to add names of member brand boxes

- [x] Ability to upload an image of member brand boxes

- [x] Ability to hyperlink member brand boxes

- [x] Ability to add and remove boxes dependent on member status

**Details** for this issue

- Four boxes across the brand page

- White Opens Sans text for brand name

- Non-member brands listed and hyperlinked below in columns as plain text

**Comment by iteles** [comment]
@jessyclubsoda Asking for a little clarification here:
When we first spoke about this, I thought you were talking about a public-facing Brands page, like we currently have on the [Venues](https://www.clubsodaguide.com/search/venues) or [Drinks](https://www.clubsodaguide.com/search/drinks) page. But what you've linked to here is your internal admin page.

Would you like the member brands to be highlighted in your internal admin area or is this issue more about creating a new Brands page for the visitors to the website (under https://www.clubsodaguide.com/search/brands for example) and bubbling member brands to the top of that page?

**Comment by jessyclubsoda** [comment]
@iteles So currently the URL linked to offers both an internal admin view and a public external view

![Non-admin brands page](https://user-images.githubusercontent.com/49029914/58897461-42a6a000-86f0-11e9-909a-21514de29f13.PNG)

This is how it looks if you're not logged in as an admin.

I guess from here we have two options

1. Create a separate public-facing Brands page akin to Venues or Drinks, and leave the existing one the same

2. Transform the existing Brands page and remove the internal admin functionality

I think my preference would be the latter. Any *admin* would have the ability to go into the back end and view a list of brands, and to any *user* the current brand listing is not particularly attractive or user friendly. Therefore, there doesn't seem to be that much value in having a brand page which can toggle between a user or admin view depending on if you are logged in. So it makes more sense just to have an attractive brand listing aimed at users of the Guide, rather than admins.

**Comment by iteles** [comment]
@jessyclubsoda I hadn't actually realised this was the case! (I had a little search but couldn't find the issue for this)

I think you're absolutely right - the 2nd option would follow the current pattern we have for drinks and venues (and admin page which we currently have and a public-facing brands page which looks much more like the current drinks and venues pages).

In the shorter term, does the public-facing brands page add much value? It's not particularly in keeping with the rest of the website and at the very least, the 'New Brand' button which does nothing for non-admins should be removed if a visitor is not logged in as an admin.

**Comment by jessyclubsoda** [comment]
I think it came out of these two issues: #499 and #557 originally but just wasn't necessarily fully thought out by us about how we wanted this to look.

I agree the list doesn't add *much* value but I don't think it currently takes away a huge amount so I think we may as well keep it up for the time being in case users do want to search specifically by brand. But I agree we could remove the 'New Brand' button if a visitor is not logged in as an admin

**Comment by SimonLab** [comment]
The first step on this issue is to make sure admin manage brands via the admin section. This means switching the current admin features from `/brands` to /admin/brands` endpoint

**Comment by SimonLab** [comment]
Current display for the member brands:
![image](https://user-images.githubusercontent.com/6057298/67296294-2d37e400-f4e0-11e9-805e-a34b61e78799.png)

I've reused the layout of the venue card to be consistent. @jessyclubsoda did you have in mind this kind of display for the brand? Are there any other information you would like to display on the card?
 
> Ability to upload an image of member brand boxes
I'm wondering if having the upload button on the card might be a bit strange. Otherwise clicking on the card will redirect to the brand page where you can upload the image there:
![image](https://user-images.githubusercontent.com/6057298/67296714-c109b000-f4e0-11e9-9015-6736f140c451.png)

Otherwise I just need know to display the non member brand as simple text under the member cards

**Comment by jessyclubsoda** [comment]
@SimonLab This looks great! 

Will the images just automatically pull from that 'cover' photo then? Because that seems ideal

And yes then non-members just as simple text (hyperlinked to their page still if possible) below the member brand cards. Almost in the way that all the brands are done now but in columns rather than one single column

**Comment by SimonLab** [comment]
> Will the images just automatically pull from that 'cover' photo then? Because that seems ideal
Yes that's right, the image displayed will be the cover one

Is a transition between the members and non members good like this:
![image](https://user-images.githubusercontent.com/6057298/67300335-b30a5e00-f4e5-11e9-9452-e4356a7e2664.png)

**Comment by jessyclubsoda** [comment]
Looks great! @SimonLab

**Comment by jessyclubsoda** [comment]
At the moment I'm not entirely clear how the pictures are pulling from the brand page

I just tried adding Heineken as a member and it appears in the page
![Screenshot 2019-10-24 11 32 35](https://user-images.githubusercontent.com/49029914/67477464-06012400-f652-11e9-940a-91971ec0c769.png)

However the image it pulls seems to be random and isn't like to any images on its brand page

![Screenshot 2019-10-24 11 33 29](https://user-images.githubusercontent.com/49029914/67477502-1fa26b80-f652-11e9-8f75-ad74c4a6967d.png)

**Comment by SimonLab** [comment]
Look better I think @jessyclubsoda :
![image](https://user-images.githubusercontent.com/6057298/67505825-dcf98700-f683-11e9-908c-ce8d66d3b37e.png)
