### ISSUE TITLE
Creating a blog page

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#595]
As an *admin*, I would like to be able to host blogs through the website

Here is a [simple wireframe](https://wireframe.cc/4tl9Vh) of how this page could look

**Simple** version of this issue

- [ ] Set of links that just takes the user to a different hosting website

**Requirements** for this issue

- [ ] Ability to upload blogs that will automatically update the listing, all hosted within the site itself

Example: [Nudging Pubs](http://nudgingpubs.uk/)

I'm *aware* that this would be a big build and don't have much concept of what the process of building it would look like so it'd be great to hear from you guys how maybe you might envisage this

**Comment by iteles** [comment]
@jessyclubsoda Thanks for your final note here, it's good to know you know! ☺️ 
I would suggest that we split this into 2 different issues - one simple version for the contents page essentially and then a 2nd issue for the fully hosted blog - as they are so different that each will merit its own conversation.
