### ISSUE TITLE
Improving related products

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#598]
As a *user*, I would like to see more specific related products when viewing a product

For example, if I look up a **kombucha**, the related products I see are other *soft drinks* rather than other **kombuchas**

![Related products](https://user-images.githubusercontent.com/49029914/58635010-a857ee00-82e4-11e9-9ac3-612960898711.PNG)

Ideally our related products would come from the *sub-category* rather than the main category

**MVP Requirements** for this issue

- [x] Related products display by sub-category rather than main category

**Extension Requirements** for this issue

- [x] Display any weighted products within the sub-category first

**Comment by iteles** [comment]
@jessyclubsoda The 'Related Products' sections only appear on Brand pages as far as I'm aware because there are no product-specific pages.

For these brand pages, we're currently taking the [category of drinks that brand creates the most of](https://github.com/club-soda/club-soda-guide/issues/349#issuecomment-455179455) and using it to display related products. I understand this can be quite broad!

My question is, if we take the _sub_-category that the brand creates most drinks in, will this be too _narrow_ a focus for related drinks? Particularly for brands who have a larger variety (and are possibly better off and therefore also your member brands).

**Comment by jessyclubsoda** [comment]
@iteles This is a great point! 

I decided to have a look at some of the data we have behind this, focusing initially on our member brands as their listings are the most important to us.

![Screenshot 2019-06-05 18 27 33](https://user-images.githubusercontent.com/49029914/58976545-a0ee8400-87bf-11e9-9263-7437eca89cd1.png)

Predominantly our member brands don't have many products so the sub-categories issue doesn't seem to affect them massively. As you predicted, brands which have more drinks start to fall more foul of the categories issue. 

I took a small sample of some more populated brands
![Screenshot 2019-06-05 18 32 51](https://user-images.githubusercontent.com/49029914/58976863-5c171d00-87c0-11e9-83b9-ebfbf47bab12.png)
These brands have a lot more of an even spread of products between multiple sub-categories, but they tend to be within quite close proximity to each other, predominantly within the "Softs" main category.

Having looked at the categorisation as exists, I think the question comes down to which is *preferable*?

> Is it better to have a selection of varying soft drinks on a brand of kombuchas or a selection of white wines on a brand of differing wines?

My hunch is the latter - if we pick out a primary sub-category/most-populated sub-category for a brand at least one drink within the brand will match the recommendations. Whereas if it stays at main categories, you can end up with no cohesion between the two.

The other slight concern I thought of was that sub-categories might not be well populated enough to fulfil the recommended drink section on their own. However, having looked I think only one sub-category couldn't do this ('Sour' within 'Beer') and as the low/no market is expanding so rapidly I would expect this not to even be the case for that much longer

**Comment by SimonLab** [comment]
I'm not sure how often this happen but it's possible that a brand has multiple types (main category) and multiple styles (sub-category). Currently the related product are based on the most common type of the drinks. @jessyclubsoda do we want to keep the same logic for the sub-category, ie find the most common sub-category used in the brand and find all the drinks matching this sub-category, or do we want to find drinks which match any of the sub-category of the brand?

`get_related_drinks/2` function used for the related product:
https://github.com/club-soda/club-soda-guide/blob/24fd810f3322399ba3e406694bec423acf8f6fde/lib/cs_guide_web/controllers/brand_controller.ex#L133-L149

This function takes the brand and the drink type (ie the main category) as parameter. So we need first to change the second parameter of the function to be the drinks' style

**Comment by iteles** [comment]
@SimonLab Jessy has asked that we "pick out a primary sub-category/most-populated sub-category for a brand"

**Comment by SimonLab** [comment]
The PR #634 returns now the list of related product based on the style/sub-category of the brand (most used one).

I think I can speed up  the function which find the most used style in the brand with `Enum.reduce`:
https://github.com/club-soda/club-soda-guide/blob/7546d170f2d578e9823f90a5e2973d56b5907ad6/lib/cs_guide_web/controllers/brand_controller.ex#L191-L195
