### ISSUE TITLE
Geolocate customer

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#6]
As a customer,
I would like to click a link titled 'Use My Location',
so I can search for venues close to where I am

**Comment by iteles** [comment]
GDPR implications and wording to be considered here #82

**Comment by SimonLab** [comment]
Some notes/research

## Main Google Maps Platform documentation
- Create an account on Google Maps Platform https://cloud.google.com/maps-platform/
- Google Maps Platform is intergrated with Google Cloud Platform: https://cloud.google.com/blog/products/gcp/google-maps-platform-now-integrated-with-the-gcp-console
- Use the Google console https://console.cloud.google.com to manage APIs, features,...
- Google Maps Platform documentation: https://developers.google.com/maps/documentation/
- List of APIs for maps:
![image](https://user-images.githubusercontent.com/6057298/49975536-4d009200-ff36-11e8-9be7-fb1095b1843f.png)

![image](https://user-images.githubusercontent.com/6057298/49975604-8fc26a00-ff36-11e8-999f-22ec83442c23.png)


Pricing: https://cloud.google.com/maps-platform/pricing/
![image](https://user-images.githubusercontent.com/6057298/49975467-001cbb80-ff36-11e8-93d0-657935170200.png)


## Create API keys
- doc for Maps JavaScript API: https://developers.google.com/maps/documentation/javascript/tutorial

- Enable `Maps JavaScript API`
![image](https://user-images.githubusercontent.com/6057298/49975984-23e10100-ff38-11e8-83a8-9f6ba367551a.png)


- in your Google Console select `API & Services` then `Credentials`
![image](https://user-images.githubusercontent.com/6057298/49975875-ae753080-ff37-11e8-9a4a-dc41d36f2821.png)

It's recommended to create 2 API keys, one for development (non restricted), on for production restricted to CS website to avoid other to use the key on their website (and using your credit)

Following the guide we can display the Map using the API:
![image](https://user-images.githubusercontent.com/6057298/49976960-28a7b400-ff3c-11e8-8d84-b310a5374d1d.png)

To place the marker to the postcode saved with the venue we'll need to use the `geocoding API`:
- Enable Geocoding API:
![image](https://user-images.githubusercontent.com/6057298/49977811-ab7e3e00-ff3f-11e8-9b9b-ffc1a06db0fa.png)

![image](https://user-images.githubusercontent.com/6057298/49977175-3873c800-ff3d-11e8-9b54-7cb32473f38b.png)

- https://developers.google.com/maps/documentation/geocoding/intro
- https://developers.google.com/maps/documentation/geocoding/best-practices

Here the script used in the show.html of the venue to add a marker based on the postcode of the venue:
``

<script>
  function initMap() {
  var london = {lat: 51.509865, lng: 	-0.118092};
  var address = <%= raw Poison.encode!(@venue.postcode) %>
  var map = new google.maps.Map(
    document.getElementById('map'), {zoom: 15, center: london});
    geocoder = new google.maps.Geocoder();
    codeAddress(address, geocoder, map);
  }

  function codeAddress(address, geocoder, map) {
    geocoder.geocode({'address': address}, function(results, status) {
      if (status === 'OK') {
        map.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
        });
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });
  }
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=addYourKeyHere&callback=initMap">
</script>
```

**Comment by RobStallion** [comment]
Set up an account following the steps @SimonLab posted above. I have created my own account for the time being but will need an account from club-soda to use in production. 

![image](https://user-images.githubusercontent.com/15571853/50088697-a51bea80-01fb-11e9-9ab6-124a9ad9b1e7.png)

Have managed to get a the map to display the address of a given location.

![image](https://user-images.githubusercontent.com/15571853/50092963-4fe5d600-0207-11e9-9bec-95093e69b985.png)

The styling has changed a little and is causing a few elements to overlap at the moment but this should be a relatively quick fix. 

Next step is to look into changing `Get Directions` into a link that shows directions from the users location to the address of the venue.

**Comment by RobStallion** [comment]
@jussi-club-soda thanks for that 👍 

I think that you may need to add a wildcard to the end of your url however so that it matches all the endpoints ClubSoda has e.g. `*.clubsodaguide.com/*`

We should also be able to use the same key for both staging and production. 

You should be able to add another website like so...
![image](https://user-images.githubusercontent.com/15571853/50288650-718cca80-045e-11e9-9979-6c55395713e5.png)

**Comment by jussi-club-soda** [comment]
Cool, have added end wildcard, and heroku URL too!

**Comment by RobStallion** [comment]
I updated the api_key value on staging and the map stopped working 

![image](https://user-images.githubusercontent.com/15571853/50294416-c6840d00-046d-11e9-8784-38c0fdbe3228.png)

![image](https://user-images.githubusercontent.com/15571853/50294478-def42780-046d-11e9-8583-3aa20bc71975.png)

It looks like it is saying the API_KEY does not allow access to this site. 

@jussi-club-soda Could you double check the URL values you entered just in case there was a typo?

**Comment by jussi-club-soda** [comment]
this is what I have there: https://*.club-soda-guide-staging.herokuapp.com/*

is it the dot between the first * and the main URL?

**Comment by RobStallion** [comment]
@jussi-club-soda Thanks for double checking and the super quick update 👍. 

That is working now. 

I realised that I missed a step in the explanation this morning however so sorry about that. We need to enable a few more APIs.

To do this open the menu on the left hand side and scroll all the way to the bottom...
![image](https://user-images.githubusercontent.com/15571853/50295330-c127c200-046f-11e9-887c-96df791ad0c9.png)

click on `google maps`.

Now click APIs
![image](https://user-images.githubusercontent.com/15571853/50295612-57f47e80-0470-11e9-89f1-e4a8a356b29d.png)

Once you are here you should see 2 lists. Enabled APIs and Additional APIs. 

We just need to make sure that `Geocoding API` and the `Maps JavaScript API` are enabled for now. 

Any that are enabled by default can be left enabled

**Comment by jussi-club-soda** [comment]
Done - and it looks like there are requests appearing for both already!

**Comment by RobStallion** [comment]
Amazing. Thanks @jussi-club-soda. Appears to be working as expect 

![image](https://user-images.githubusercontent.com/15571853/50296274-11078880-0472-11e9-82d1-40e2545a5984.png)

**Comment by RobStallion** [comment]
@jussi-club-soda We just deployed the app to production but we were having the same error we had earlier in staging. See [here](https://github.com/club-soda/club-soda-guide/issues/6#issuecomment-449041420) for more info.

Would you be able to double check the url for production again please. 

As this was for production and we didn't want the maps to display an error I have used my api key for now.

**Comment by jussi-club-soda** [comment]
Hmm. Could it be that I didn't have https:// in front of the production URL? Have added that now.

**Comment by ctrembath** [comment]
@RobStallion clicking the 'Use my location' CTA in the search bar.

Having a look in the console and I'm seeing this error:

[Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by RobStallion** [comment]
@ctrembath are you viewing this on the staging site? If so can you post the full URL you used to get this error to occur and also the browser you are using?

My assumption would be that your URL contains `http://` as apposed to `https://` and that this is what is causing the issue.

**Comment by RobStallion** [comment]
@ctrembath 

> @RobStallion currently all the venues on the staging site don't seem to have drinks?

with regards to this point, please see this issue https://github.com/club-soda/club-soda-guide/issues/333. This is being worked on at the moment and you will be able to test this feature once it has been completed and merged into staging.

> @RobStallion clicking the 'Use my location' CTA in the search bar. This links to issue #231

The `Use my location` is only in staging at the moment and this should work if you are on a https connection. There is an open issue #337 that relates to this as well

**Comment by SimonLab** [comment]
@ctrembath we spotted this issue this morning, see #333 

We are currently fixing this issue and adding back the data in staging. 
Once these steps are done you will be able to continue to test the application on staging, https://club-soda-guide-staging.herokuapp.com/ and not on production as the latest features haven't been deployed yet

**Comment by ctrembath** [comment]
@RobStallion the `Use my location` feature with https shows no search results - see screenshot attached
![screenshot 2019-01-10 at 11 51 53](https://user-images.githubusercontent.com/8418748/50966925-6d3c5600-14ce-11e9-84af-589e210bd333.png)

**Comment by SimonLab** [comment]
It seems that one of the venue has not its slug defined:
![image](https://user-images.githubusercontent.com/6057298/50967256-82fe4b00-14cf-11e9-94f2-f29c7dcf6394.png)
