### ISSUE TITLE
Simple contents page

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#603]
As an *admin* I would like to create a simple contents page to allow me to link to blogs hosted on a separate site

**Comment by iteles** [comment]
@jessyclubsoda 
It would be great to have a little additional detail here on how this would differ from a static page with a title and updatable hyperlinks that you can already create at the moment.

**Comment by jessyclubsoda** [comment]
I guess this simple version is actually more of a design issue. It's about making the page look like it's a blog even though it's being hosted elsewhere. 

Here's a kind of simple design I've done which shows that ideally we would just be able to add a photo, header, sub-title, and then hyperlink which will take users to a separate hosting sight for the time being.

![Simple blogs page](https://user-images.githubusercontent.com/49029914/59040939-98558680-886f-11e9-998a-9dbfca7b1be0.png)
