### ISSUE TITLE
Fully hosted blog

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#604]
As an *admin*, I would like to be able to host a full blog on my website

**This issue has now been split into a number of separate issues**

## MVP
#608 Blog tab in header - a tab in the header to click through to the blog page
#609 Articles listings page - the blog page designed in a way to show articles based on how recently they had been published with thumbnail image, headline and summary
#611 Database of articles - a list of all the published articles in the back end with the ability to edit or delete them
#612 Add a new article - the ability to add a new article with sections to upload an image, enter a headline, enter a summary, enter some text (with simple markdown/HTML capability)

## Stretch version
#610 Sharing an article online - ability to automatically share an article to a social channel
#614 Ability to tag articles - ability to create and assign tags to articles
#615 Toggling between blogs listed by tags or by date - ability to change the way blogs are presented
#613 Add metadescriptions to articles
#616 Suggested articles based on blogs' tags - articles of same tag listed at bottom of an article
#617 Suggested drinks based on blogs' tags - ability to assign drinks to a specific blog
#618 Drafting capability - ability to save drafts of articles within the CMS
#619 Blog carousel on home page - ability to select blogs to go on a carousel on the home page

**Comment by iteles** [comment]
Thanks for splitting out this into a separate issue @jessyclubsoda :+1:

There are lots of levels of what a 'full blog' can consist of so we'll wait for you to flesh this out a little more. A good way to tackle this (there could be a lot here) might be to take a full user journey from the admin's perspective of creating blog posts and then a full user journey from a visitor to the website's perspective to determine what they should see.
Another thing to consider would be SEO requirements.

Maybe also keep in mind that you might want two separate issues for this in itself - an MVP/simple version and then a stretch version which for now can be almost like a scratch pad issue to contain all of your ideas for extending blog functionality once the simpler version is live!

**Comment by jessyclubsoda** [comment]
This issue will be split up using the blog label
