### ISSUE TITLE
Add hyperlinked social media bubbles to Contact Us page

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#605]
As a *user*, I would like to easily be able to access Club Soda's social media accounts from the Contact Us page

As an *admin*, I would like our social media links to look more engaging 

- [x] Have a set of social media bubbles on the Guide page that can be hyperlinked to relevant social media accounts

![Bubbles](https://user-images.githubusercontent.com/49029914/59036645-9a1b4c00-8867-11e9-89a4-48c2bf5890b3.png)

**Comment by iteles** [comment]
@jessyclubsoda It would be good to add the position on the page and which ones you need, hyperlinked to which URLs.

**Comment by jessyclubsoda** [comment]
Here's an example of design of how I think this could be positioned

![Contact Us page](https://user-images.githubusercontent.com/49029914/59103277-53405b80-8926-11e9-9555-d05a09ad2ac2.png)

In terms of links and URLs, we'd be looking at:

- Twitter - http://www.twitter.com/joinclubsoda
- Facebook - http://www.facebook.com/joinclubsoda
- Instagram - http://www.instagram.com/joinclubsoda
- LinkedIn - https://www.linkedin.com/company/club-soda-uk/
- YouTube - https://www.youtube.com/channel/UCvR4rMt13bK8dwX-6gDiwAA/feed

Ideally, we would have the functionality to change these hyperlinks if we were going to have any future changes to our social media strategy (e.g. setting up Guide specific social media for example)

**Comment by iteles** [comment]
@jessyclubsoda Would you be able to provide us with the background image and the final social media images you'd like to be used please? ☺️

**Comment by jessyclubsoda** [comment]
@iteles What's the best way for me to host the images and send to you?

**Comment by iteles** [comment]
@jessyclubsoda Google drive would be great. If you have a chance it's also worth optimising the background image so that the image size isn't massive as @jussi-club-soda mentioned on Monday!

**Comment by jessyclubsoda** [comment]
@SimonLab Looking great - just one thing, is it possible to have the social media links open in a new tab rather than redirecting away from the website?

**Comment by jessyclubsoda** [comment]
Can we also update the Youtube link to https://www.youtube.com/channel/UCFaaOD8V84NZTilAvnxzO4w
