### ISSUE TITLE
Deployment to production

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#606]
We need to deploy the most recent version of the Guide

**Comment by nelsonic** [comment]
Hi @jessyclubsoda I have deployed the latest version of the code from `master`. 👍 
If you ever need to do this without us, it's fairly straightforward.
1. Visit: https://dashboard.heroku.com/apps/club-soda-guide
2. Follow: https://github.com/club-soda/club-soda-guide/blob/master/dev-guide.md#deployment

![image](https://user-images.githubusercontent.com/194400/61108644-c59ee100-a47a-11e9-8c0b-afc74634e6c2.png)
