### ISSUE TITLE
Generating a venues Club Soda Score

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#61]
As a venue selecting the Af/ Low A drinks I stock,
I would like to receive my Club Soda Score,
so that I know how good my AF / Low A offering is

**Acceptance Criteria**
The Club Soda Score score should be calculated correctly:

- [x] Venues receive 1pt per AF beer stocked (type=Beer & ABV <= 0.5%)
- [x] Venues receive 1pt per AF wine stocked  (type = Wine & ABV <= 0.5%)
- [x] Venues receive 1pt per AF cider stocked (type = Cider & ABV <= 0.5%) 
- [x] Venues receive 1pt if they stock at least one 1 - 2.5% Beer (type=Beer & ABV > 0.5%)
- [x] Venues receive 1pt if they stock any Low Alcohol wine (1 - 8%) (type = Wine & ABV > 0.5%)
- [x] Venues receive 0.5pt for any Soft Drinks they stock, up to a maximum of 1pt
- [x] Venues receive 0.5pt for any Tonics & Mixers they stock, up to a maximum of 1pt
- [x] Venues receive 1pt for any drink of type Spirits & Premixed 
- [x] Venues also receive 0.5pt per Alcohol Free Cocktail stocked - these are not on the database
so will need a different type of input from other drinks - venues will only receive these points if the cocktails are listed on their menus so they need to confirm that
- [x] The maximum score a venue can get is 5 Club Soda Points
- [x] The minimum a venue can get is 0 Club Soda Points

@iteles - we haven't discussed in much detail our current scoring model. Please see [here](https://docs.google.com/spreadsheets/d/1RskeGSMJlF069fMnQq7TzD_ft8PlaaBD_oiKlOiYxBM/edit#gid=868299136) for how we hope to calculate a venues score

**Comment by jussi-club-soda** [comment]
An addition to this (lower priority): when we upload already signed up venues from the existing websites, most have already have a score which is based on a different calculation. Since it would be a shame to lose these scores, it would be great if we could - for all of those venues - migrate their score and override the blank score value they will have in the new site. If and when they in future edit their listing, the old score disappears and they get a new one based on the new calculation.

**Comment by Cleop** [comment]
@jussi-club-soda 

To calculate mocktail points, what constitutes a mocktail? There are only 6 drinks with mocktail as a style in the airtable list, but these drinks have a type of 'soft drink'. 

Should the function be looking for mocktail listed as a type (which is how we currently filter for beer/wine/cider etc.) or should it be looking for it under style? Or is there another means by which you calculate mocktails?

**Comment by jussi-club-soda** [comment]
@Cleop Yes, good question! These are a bit different from drinks in the database. It is basically any drinks that get made from scratch in the venue, using all kinds of ingredients so we can't list them in the database. The question should really be: "how many alcohol free cocktails do you have on your menu?"

Not sure how this is easiest done? 

Adding "on the menu" prevents people from saying 'oh and I can make you anything you like' which is cheating. 

We'd rather not use the word "mocktail" by the way, "alcohol free cocktail" is the preferred term.

**Comment by jussi-club-soda** [comment]
@Cleop Actually looking at this now, the calculation doesn't really match the database any more... We may have to tweak this a bit...

**Comment by jussi-club-soda** [comment]
An updated version of the drinks database - this still needs a bit of work I'm afraid:
[Guide drinks database for upload 1.xlsx](https://github.com/club-soda/club-soda-guide/files/2509755/Guide.drinks.database.for.upload.1.xlsx)

The six drink types are:
Beer
Wine
Cider
Soft Drink
Tonics & Mixers
Spirits & Premixed

An update to the scoring:

Acceptance Criteria

The Club Soda Score score should be calculated correctly
[] Venues receive 1pt per AF beer stocked (type=Beer & ABV <= 0.5%)
[] Venues receive 1pt per AF wine stocked  (type = Wine & ABV <= 0.5%)
[] Venues receive 1pt per AF cider stocked (type = Cider & ABV <= 0.5%) 
[] Venues receive 1pt if they stock at least one 1 - 2.5% Beer (type=Beer & ABV > 0.5%)
[] Venues receive 1pt if they stock any Low Alcohol wine (1 - 8%) (type = Wine & ABV > 0.5%)
[] Venues receive 0.5pt for any Soft Drinks they stock, up to a maximum of 1pt
[] Venues receive 0.5pt for any Tonics & Mixers they stock, up to a maximum of 1pt
[] Venues receive 1pt for any drink of type Spirits & Premixed 
[] Venues also receive 0.5pt per Alcohol Free Cocktail stocked - these are not on the database
so will need a different type of input from other drinks - venues will only receive these points if the cocktails are listed on their menus so they need to confirm that
[] The maximum score a venue can get is 5 Club Soda Points
[] The minimum a venue can get is 0 Club Soda Points

**Comment by Cleop** [comment]
@jussi-club-soda - 

> Venues receive 1pt for any drink of type Spirits & Premixed
- is this 1 per drink or a maximum of 1 point for this?

**Comment by jussi-club-soda** [comment]
@Cleop 1 per drink, no maximum!

**Comment by jussi-club-soda** [comment]
And to keep things interesting -sorry!- here's yet another update to the drinks database: now with the online shops, shops, and wholesale columns added to the brand sheet, with space for the  longer description for members & link to the brand's own "where to buy" page (nothing in them yet apart from one entry for Big Drop as I was testing how this could work - with variable success is the answer...)

[Guide drinks database for upload 1.xlsx](https://github.com/club-soda/club-soda-guide/files/2510731/Guide.drinks.database.for.upload.1.xlsx)

**Comment by Cleop** [comment]
@jussi-club-soda - to confirm, do the scores have to be whole numbers or those ending 0.5 are also acceptable (up to the usual limit of 5)? E.g. can a venue have a CS score of 2.5?

**Comment by jussi-club-soda** [comment]
@Cleop another good question :)

I guess for the back-end, half scores would be informative, but would we be able to display them in the front-end? Maybe create a half-cup image? Or does that get too complicated? I won't mind if the displayed score is just one of 0, 1, 2, 3, 4, or 5; with any half-scores rounded up.

**Comment by Cleop** [comment]
@jussi-club-soda - this is how I was imagining scores would be displayed (apart from as cups not stars):

If a venue has a club soda score of 0 or they've not yet added any drinks (in other words 0), do we still want to display 5 greyed out cups? I'm concerned it might not be obvious that they have 0 points rather than 5. Also, if you've not added a score yet that doesn't necessarily mean you are a 0 point venue. 

What do you think?

**Comment by jussi-club-soda** [comment]
@Cleop Yep, I like the idea of not displaying anything if they've not filled in their drinks.

I guess there is the same risk in displaying 5 gray cups for the zero rated venues - there may be a few out there, but I would hope everyone would get at least one star! But this is probably much less of an issue.

**Comment by Cleop** [comment]
@jussi-club-soda - how would you like the mocktail scoring process to look? This is the page at present:

![image](https://user-images.githubusercontent.com/16775804/48131230-46bc2d80-e287-11e8-8cee-5b09b05c8c32.png)

- Would you like there to be a text field underneath where they can say how many mocktails they have on the menu?
- How are you going to confirm the drinks are on their menu? Will you have a separate checkbox or will it be in the copy for the mocktails input box?

Please can you confirm the positioning and copy for this aspect of the score.

**Comment by jussi-club-soda** [comment]
@Cleop A text box under the brands form sounds ok to me, and yes, I think let's just put the "menu" thing on the copy. How about this for the copy:

If you serve alcohol free cocktails AND list them on your menu, type in the number of cocktails here:

Positioning: between the brands form and the Submit button?

**Comment by Cleop** [comment]
### Copying and pasting the original acceptance criteria here just for reference:

- [ ] The[ Club Soda Score](https://docs.google.com/spreadsheets/d/1RskeGSMJlF069fMnQq7TzD_ft8PlaaBD_oiKlOiYxBM/edit?usp=sharing) score should be calculated correctly
- [ ] Venues receive 1pt per AF beer stocked
- [ ] Venues receive 1pt per AF wine stocked
- [ ] Venues receive 1pt per AF cider stocked
- [ ] Venues receive 0.5pt per Mocktail stocked
- [ ] Venues receive a maximum of 1pt for all 1 - 2.5% Beers
- [ ] Venues receive a maximum of 1pt for all Low Alcohol wines (1 - 8%)
- [ ] Venues receive a maximum of 1pt for all Soft Drinks
- [ ] The maximum score a venue can get is 5 Club Soda Points
- [ ] The minimum a venue can get is 0 Club Soda Points
- [ ] If a venue is serving 'mocktails' they will only receive points if they agree that the mocktails are listed on their menu

**Comment by jussi-club-soda** [comment]
@Cleop could you check what's in the code: your "reference" accceptance criteria is different from the original at the top of this issue (at least "Venues receive 0.5pt for any Tonics & Mixers they stock, up to a maximum of 1pt" and "Venues receive 1pt for any drink of type Spirits & Premixed" are missing) - having done a quick check I fear these are still missing from the score calculation...

Another question/possible issue: some drinks are in more than one category (eg Punchy is a soft drink AND a premixed) - how does the scoring treat them?

**Comment by Cleop** [comment]
The reference acceptance criteria are what you originally laid out. They are not what has been enforced. The enforced criteria are those in the top comment.

So the two examples you gave should be in place. They have tests which are passing but I tested it on the live site and you're right it's not working. I'm going to take a look into this, my instinct is that it's got something to do with how we changed the names of these types and so I think one of the filters is out of date.

Regarding you question on whether a drink can score for being in more than one category: at the moment yes, a drink would score multiple times.

**Comment by Cleop** [comment]
This example doesn't error locally. I'm looking into why this could be occurring on staging...

**Comment by Cleop** [comment]
The venue that the score error was on is not in my local DB. However and adding these two drinks to any other venue locally generated the correct score.

The scoring error was on the CEDER's drink as that is the drink which should have scored 1pt and was missing. So I decided to remove the drink and add it again on staging and the error was gone:

![image](https://user-images.githubusercontent.com/16775804/50289080-ab120580-045f-11e9-8ddb-2a9909e0e502.png)
![image](https://user-images.githubusercontent.com/16775804/50289623-4bb4f500-0461-11e9-8e59-285e8ea8742d.png)

I'd be interested to know @jussi-club-soda if there are any details you can remember about the way in which '4degrees Craft Bar & Kitchen' was uploaded or 'CEDER's Classic'? I'm wondering if the drink type was changed or added at any particular time or if 4degrees was uploaded in a particular way? 

Otherwise I'm somewhat out of clues for what is distinctive about this scenario and may have caused it initially but not on recreation...

**Comment by iteles** [comment]
@Cleop As discussed, let's take a quick look at the timestamps in the databases on our end 👍

**Comment by Cleop** [comment]
Venue originally inserted: 2018-11-28 14:26:09.1905 with a CS score of 0.
Score changed to 0.5 at 2018-12-06 09:42:22.082071.
Score changed to 1 at 2018-12-06 09:43:25.535207.
Score changed to 0.5 at 2018-12-06 09:44:01.837743.

**Venue ID:** 767
**Associated drinks IDs:** 
- Punchy Drinks Peach and Ginger 384, inserted at 2018-11-28 14:25:47.086489
- Punchy Drinks Peach and Ginger 602, inserted at 2018-12-06 10:15:34.426994, weighting 3.
- Ceder's Classic 119

**Drink types for the scoring:**
384:
602:
