### ISSUE TITLE
Ability to edit brands

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#623]
We've come across an issue whereby if you accidentally assign a drink to the wrong brand, you are unable to edit it. It brings up an 'Internal Server Error'. This is happening on the live site and staging.

**Comment by SimonLab** [comment]
Error on localhost:
![image](https://user-images.githubusercontent.com/6057298/64532281-16ab4400-d309-11e9-84e7-85a3fb98e839.png)
