### ISSUE TITLE
Update production website?

### ISSUE THREAD

**Issue by SimonLab** [club-soda/club-soda-guide#632]
The last time the production website has been updated was the 12th of July.
Since then, some PRs have been merge and deployed into staging:
![image](https://user-images.githubusercontent.com/6057298/67196157-2b8ff280-f3f2-11e9-93eb-f48b61e892e1.png)

@jessyclubsoda would you like the production website to be updated now or do you prefer to wait the end of the week once a few new PRs have been merged and tested on staging?

**Comment by jessyclubsoda** [comment]
Think it'd be good to update now before we start any extra work?

**Comment by jessyclubsoda** [comment]
Any time is fine @SimonLab !

**Comment by SimonLab** [comment]
The production should now be up to date.
