### ISSUE TITLE
Hyperlinking the Sponsor banner on home page

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#666]
We have recently agreed to partner with one specific drinks retail outlet and we have put a banner advertising this on our home page using the 'Sponsor' section in the Admin element of the site

I would like to hyperlink the banner with our affiliate link to the site so that we get income from any sales made through our site

I used this code in the HTML section
`<div class="db tc">   <img src="https://club-soda-prod.s3-eu-west-1.amazonaws.com/Wise-Bartender-banner.png">  <a href="https://wisebartender.co.uk/?ref=clubsoda"> </div>`

However it doesn't link on the home page.

Is this because the Body won't accept html tags other than `<div> <img>` etc. ? And if so, how can we go about adding in the hyperlink?

**Comment by nelsonic** [comment]
Hi @jessyclubsoda, your HTML code is _almost_ right, but you need to _wrap_ the image (`<img>`) in the link (`<a>`). 
e.g:
```html
<div class="db tc"> 
  <a href="https://wisebartender.co.uk/?ref=clubsoda">
    <img src="https://club-soda-prod.s3-eu-west-1.amazonaws.com/Wise-Bartender-banner.png">  
  </a>
</div>
```

Try clicking on the following image:

<div class="db tc"> 
  <a href="https://wisebartender.co.uk/?ref=clubsoda">
    <img src="https://club-soda-prod.s3-eu-west-1.amazonaws.com/Wise-Bartender-banner.png">  
  </a>
</div>

Is that your expected result?

**Comment by jessyclubsoda** [comment]
Perfect thank you!
