### ISSUE TITLE
Admins can import drinks data

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#68]
As an admin,
I'd like to import a CSV of drinks data,
so I can quickly populate the Club Soda Guide with drinks

Agreed in sprint 3 planning session that this is to be used once and doesn't need a pretty interface for now.

**Comment by iteles** [comment]
Updating of the schema accounted for in this estimate.

**Comment by iteles** [comment]
@Cleop @Danwhy We have the current data in the Airtable provided by @ctrembath in the top comment of https://github.com/club-soda/club-soda-guide/issues/92

This is currently being updated, though most fields are expected to stay the same.
