### ISSUE TITLE
Admin can import venue data

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#69]
As an admin,
I'd like to import a CSV of venue data,
so I can quickly populate the site with venues

Note: https://github.com/club-soda/club-soda-guide/issues/69#issuecomment-420706902 as part of acceptance criteria

## Acceptance Criteria
+ [x] Venue data is imported via CSV provided by Jussi
+ [x] Old Club Soda scores are also imported
+ [x] If there are no drinks in the venue's stocklist, display the old CS score
+ [x] When the venue is updated with a stocklist, update the CS score with the new one #61 

Agreed in sprint 3 planning session that this is to be used once and doesn't need a pretty interface for now.

Venues CSVs: https://drive.google.com/drive/u/1/folders/1Ic3FBd-NNWjj4kH5oMTVL6Q_jJWuqIV8

**Comment by ctrembath** [comment]
Is it possible to seed the database with our existing venues and allocate them a score without adding their stocklist based on their current Club Soda Score.
Could we then issue them login details so they can access their account and add their up-to-date stocklist, to regenerate their Club Soda Score?

**Comment by iteles** [comment]
Definitely possible. More of a question of priority 👍

**Comment by jussi-club-soda** [comment]
@iteles it could be an ongoing feature - if eg a chain of bars wants to get all of their bars up at once, they may have the data we can just upload (rather than each bar doing it separately).

**Comment by iteles** [comment]
As mentioned by @jussi-club-soda [here](https://github.com/club-soda/club-soda-guide/issues/61#issuecomment-420679390), this import would ideally include the original venue scores:
![image](https://user-images.githubusercontent.com/4185328/45438374-e0fc5c80-b6ae-11e8-8996-0221e31236b4.png)

**Comment by iteles** [comment]
@jussi-club-soda Will it not be confusing to your users to see a high Club Soda score for a venue that has no stock listed?

**Comment by jussi-club-soda** [comment]
@iteles good point... though in the descriptions of the current venues there is usually a paragraph at the end, along the lines of "Club Soda says: this venue stocks 2 AF beers and a nice range of soft drinks" which is something we've added to let people know why venues score how they score there. So that would help, and hopefully over time they will update their listings and add their drinks. But let's keep this as an open question for now, I'll ask for views in our office too!

**Comment by iteles** [comment]
3 import scripts were created and all the venue data was imported, including the final set of data we received which included drinks linked to the venues. In addition, the venue picture URLs were imported originally but we came up against an issue: https://github.com/club-soda/club-soda-guide/issues/167#issuecomment-442507655

This was resolved separately my manually uploading the venue images.
