### ISSUE TITLE
Admins can flag brands as 'members'

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#73]
As an admin,
I'd like to flag brands as 'members',
so they can have a more extensive profile

**Acceptance Criteria**
- [x] As an admin logged into the CMS, I can visit a page that lists all brands
- [x] Each 'Brand' should have a 'Member' boolean field
- [x] Each 'Brand' membership field should default 'No' 
- [x] I should be able to update the membership field to 'Yes'
- [x] I should be able to update brand 'members' to 'No' if they are no longer members

**Comment by iteles** [comment]
Completed as part of #105
