### ISSUE TITLE
Admin can add a 'weighting' to each drink

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#74]
As an admin,
I'd like to flag members products as 'featured' by adding a weighting to them,
so customers see them in the featured product sections.

This will affect the featured products section of the homepage #8 and also affect the default display order on the drinks page #36

## Acceptance Criteria

+ [x] 0 - 3 weighting for each drink
+ [x] 3 is the highest weighting

**Comment by jussi-club-soda** [comment]
This is fine (in that we can add the weighting variable for drinks - still unsure about the impacts of those...)
