### ISSUE TITLE
Admins can flag venues as favourites

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#75]
As an admin,
I'd like to flag venues as favourites,
so they feature on the homepage

## Acceptance Criteria
+ [x] Checkbox in admin view of venue allows admins to set venue as 'Favourite'
+ [x] Agreed during sprint planning that there was no need to impose a limit on the number of venues that can be favourites (see #10 for treatment on homepage)

**Comment by iteles** [comment]
@jussi-club-soda Would you prefer that this wording was clearer e.g. 'Featured on homepage'? Or would you prefer to keep it more general so you can reuse it for other things?

**Comment by jussi-club-soda** [comment]
@iteles Happy to leave it a bit vague if there are other uses of this in future - but also think the home page feature is the only thing we'll be using it for at the moment..

**Comment by iteles** [comment]
The favourite field has been added to the venue _setup_ form in https://github.com/club-soda/club-soda-guide/pull/150 (and as part of issue #10), when in actual fact, it needs to be part of the admin-only side of venues.

The field is also appearing twice so both will need to be removed from the venue setup form.

![image](https://user-images.githubusercontent.com/4185328/49040447-7f7e6100-f1ba-11e8-8cb8-dfef21a613e8.png)
