### ISSUE TITLE
Admins can export database

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#76]
As an admin,
I'd like to export all drinks and venue data including: all brands, drinks and venues on the database, and what drinks each venue stocks in a CSV format,
so I can track signups and other KPIs, and get useful data eg to inform brands where their products are stocked

**Acceptance Criteria**
- [x] I should have an option to 'Download' all data from the database (brands, drinks, venues, linkages between venues and drinks)
- [x] Pressing the CTA to 'Download Data' should download all data in CSV formatted file(s) [or any other format Excel/Google Sheets can read]
- [x] Download file to include all fields from the database, including id fields not shown in public on the site, date created/modified, and anything else that could be useful for KPIs, analytics, etc

**Comment by jussi-club-soda** [comment]
@iteles not sure how much more I can add here - basically just grab everything you can from the database :)

**Comment by SimonLab** [comment]
Elixir library to encode/decode csv: https://github.com/beatrichartz/csv

**Comment by jussi-club-soda** [comment]
Have just had a quick look at the downloads on staging:
- venues - seems to have everything we need
- drinks & brands - same, has all the basic info
- linking brands to drinks and venues to drinks: are there additional files with this info? we need to be able to link a venue with the drinks it has, and brands with drinks as well.

**Comment by SimonLab** [comment]
@jussi-club-soda what would be your preferenc for creating this links?

For example to show the link of the drinks to the venues we could have a csv file with the name of the venue then the name of the drink:

| venue name | drink |
| -- | -- |
| London Pub | drink 1|
| London Pub | drink 2 |
| Bristol Pub | drink 1 |

Or instead of having the names we could use the venues' ids and drinks' ids?

**Comment by SimonLab** [comment]
I've added the two download links (venues drinks and brands drinks):
![image](https://user-images.githubusercontent.com/6057298/52204299-a9fc3280-286b-11e9-9dcb-af3de1696067.png)

and I'm displaying the ids and the names of the linked items:
brands-drinks
![image](https://user-images.githubusercontent.com/6057298/52204339-c7c99780-286b-11e9-8a67-76b322113baf.png)


venues-drinks
![image](https://user-images.githubusercontent.com/6057298/52204360-d748e080-286b-11e9-9cfa-bce3c5df45dc.png)

**Comment by jussi-club-soda** [comment]
Thanks @SimonLab you got there before I did! Looks good! :)

That should give me everything I need.

**Comment by iteles** [comment]
Thanks both! Only creation date missing to complete this issue now 👍

**Comment by jussi-club-soda** [comment]
Have been looking at these again and think there are still some missing bits / bugs I'm afraid...

"Download drinks" - doesn't have the drink_id field, so can't match drinks to brands (from the "Download brands with drinks" outputs)

"Download drinks" - would also be useful to include the type and sub-type of the drinks (we've just had a request from the Government for a list of all alcohol free beers!)

Formatting - we have things like "Teetotal Gâ€™nâ€™T" and "Weâ€™ve something for all the family â€“ from" in the downloads - encoding issue?

**Comment by SimonLab** [comment]
Hi @jussi-club-soda I will have a look very soon at these issues.
For the encoding problem it might be an issue with the software you are using to read the files but I'll double check this also

**Comment by SimonLab** [comment]
@jussi-club-soda I think the encoding issue might be linked to your "excel" software. You should be able to define which encoding to use when opening the downloaded file. On my computer (using libre office) the default value is utf8 which display properly the text:

![image](https://user-images.githubusercontent.com/6057298/55000811-3b199b00-4fcb-11e9-91c6-cd0a8e0fb8a6.png)



![image](https://user-images.githubusercontent.com/6057298/55000783-2806cb00-4fcb-11e9-93e7-af8d155ec8b3.png)

**Comment by jussi-club-soda** [comment]
Two more additions to the Venues download please @SimonLab :

Parent company/chain
Venue types

**Comment by nelsonic** [comment]
The table/schema definition for Venues is [/lib/cs_guide/resources/venue.ex](https://github.com/club-soda/club-soda-guide/blob/master/lib/cs_guide/resources/venue.ex) (_list of available fields_)
The fields @jussi-club-soda needs us to add to the report are: `:parent_company` and `:venue_types` is a many-to-many relationship  therefore it requires the relationship to be pre-loaded.

**Comment by nelsonic** [comment]
To add more fields to the csv export, we need to edit [`lib/cs_guide_web/controllers/csv_controller.ex`](https://github.com/club-soda/club-soda-guide/blob/master/lib/cs_guide_web/controllers/csv_controller.ex)
and add the fields to both the `venue_csv_data` and `venues_csv_content` functions.

The end result is the following `.csv` exported:
![image](https://user-images.githubusercontent.com/194400/55790240-d7579d80-5ab3-11e9-8ec1-1386bf131def.png)


**Please note**: at the time of writing, there are only 20 venues have a `:parent_company` defined.
```sql
SELECT COUNT(DISTINCT entry_id)
FROM venues 
WHERE parent_company <> 'unknown'
```
![image](https://user-images.githubusercontent.com/194400/55790515-695fa600-5ab4-11e9-888b-084c6a407c71.png)


> I exported the `production` database following these steps: [dev-guide.md#using-real-data](https://github.com/club-soda/club-soda-guide/blob/master/dev-guide.md#using-real-data)

**Comment by nelsonic** [comment]
Fields added in PR: https://github.com/club-soda/club-soda-guide/pull/539

**Comment by nelsonic** [comment]
Hi @jussi-club-soda / @jessyclubsoda,
The two fields `:parent_company` and `:venue_types`  have been added to the `venues.csv` export.
_Please test_ on staging by visiting: https://club-soda-guide-staging.herokuapp.com/admin 
and clicking on the "Download Venues" link:
![image](https://user-images.githubusercontent.com/194400/55863271-1ea46380-5b72-11e9-854a-79f07efd0f65.png)


If you want to export the _whole_ database and run SQL queries on it on your local computer,
follow these instructions: 
https://github.com/club-soda/club-soda-guide/blob/master/dev-guide.md#using-real-data

If this issue is complete, please close it. 
Thanks! ☀️
