### ISSUE TITLE
Drinks brand members treatment / database setup

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#79]
I have some thoughts on this but would be good to discuss together.

Background: drinks brands membership scheme is a key part of our business model for the Guide (the best source of revenue). So we'd like to make sure we can flag member brands in the database, and give them special treatment for their money. (In addition to their profile page being different from the non-member ones.)

There might be several different things here, eg always listing them first in any drinks listing view, giving them a higher probability of appearing at the top of searches, etc. 

This should probably be a part of a wider discussion on the whole drinks database setup.

**Comment by iteles** [comment]
@jussi-club-soda This might be one to revise now in light of the recent rethinking of the drinks database?

**Comment by jussi-club-soda** [comment]
@iteles Yes I think this is now fully covered elsewhere?
