### ISSUE TITLE
Customers can list a venue

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#80]
As a customer,
I would like to create a venue listing,
so I can ensure my favourite AF / Low A venues are on the club soda guide

**Comment by jussi-club-soda** [comment]
Not sure about this one... as long as venues and admins can set up listings, and we have a nomination form for customers, this could be a bit risky even?

**Comment by iteles** [comment]
@jussi-club-soda I think we'll need to revisit the whole venue creation piece in a bit more detail as per my comment in https://github.com/club-soda/club-soda-guide/issues/54#issuecomment-419425635.

Now that we have @harrygfox's design for this, it will be easier to discuss. One for the very end of our sprint planning session 👍
