### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#83]
Would be good to discuss SEO at some point. One thought:
Being so content heavy site, how do we get the best value from the venues and drinks data? On our existing WP site, each venue page has a URL which gets indexed => lots of content on Google.
What will happen on the new site?

**Comment by iteles** [comment]
@jussi-club-soda We now have individual pages with descriptive, human-readable URLs for both venues #223 and brands #222 🎉 

e.g. Albero Lounge (venue): https://www.clubsodaguide.com/venues/albero-lounge-mk40-1ay  
Fentimans (brand): https://www.clubsodaguide.com/brands/Fentimans
