### ISSUE TITLE
Abstract the API

### ISSUE THREAD

**Issue by Danwhy** [club-soda/club-soda-guide#84]
If we go ahead with contentful as a CMS, we should abstract out the API calls to make it easier for us to use them when writing new requests.
An unofficial SDK/wrapper for the API exists at https://github.com/contentful-labs/contentful.ex. We should take some time to look more at this, and decide if we want to use it. There may be some functionality missing that we require, but we could easily extend it if we require.

**Comment by iteles** [comment]
No longer relevant.
