### ISSUE TITLE
Admins can flag venues as 'reviewed'

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#87]
As an admin,
I'd like to flag a venue as 'viewed',
so I know all the information on a venue page is acceptable

**Comment by iteles** [comment]
@ctrembath @jussi-club-soda I believe the use case here was for Jussi to be able review venue listings once they were first created. Now that venues will have the ability to edit their information (any or all of it) at any given time, it will be worth considering whether having something permanently ticked as 'reviewed' will still be of value.

An alternative for a future iteration could be to have listings come up for review whenever there is an edit but this would likely become too cumbersome for the Club Soda team and even unnecessary. There are a number of variations such as 'only bubbling up for review the first 3 times a venue is edited' or building in additional functionality to show _exactly_ what has been edited and surfacing that in a custom dashboard, but for now, venues can be ordered by 'Last edited date' and checked.
