### ISSUE TITLE
Homepage Drinks Category Buttons

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#9]
As a customer,
I'd like to see a list of drink category CTA's,
So I know what types of products are listed on the Club Soda Guide

![image](https://user-images.githubusercontent.com/4185328/47022924-7085a700-d156-11e8-94ad-601ba2223093.png)

**Comment by iteles** [comment]
@jussi-club-soda What is the priority on this please?

**Comment by jussi-club-soda** [comment]
@iteles I've set this as priority 3!

**Comment by iteles** [comment]
From @jussi-club-soda:
Buttons under "Explore All Drinks" on the home page and the drop-down menu in the drinks search page - 
"Spirits & Premixed" doesn't return anything, neither does "Flavoured Tonics" - this should be "Tonics & Mixers" which may be why it doesn't work? Not sure why "Spirits & Premixed" doesn't work...
