### ISSUE TITLE
Admins can order venue listings by their creation date

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#91]
As an admin,
Viewing the venue listings in the CMS, I should be able to view the listings according the their 'date added',
so I can easily see which venues are new to the Club Soda Guide

**Comment by Cleop** [comment]
I've opened an issue discussing the existing logic for date ordering here: https://github.com/dwyl/alog/issues/16

**Comment by Cleop** [comment]
Venues are currently in alphabetical order. To order them by most recently updated:      `Enum.sort_by(& &1.inserted_at)`

Need to create something that gives the option for this.

**Comment by Cleop** [comment]
For testing:

The chevrons next to the appropriate column title indicate how to change the order in which the results appear. Either from A-Z or from most recent to oldest.
![image](https://user-images.githubusercontent.com/16775804/50687389-083db780-1019-11e9-93ef-cd7a09a3e011.png)

**Comment by ctrembath** [comment]
@Cleop this seems to display venues ordered by 'last updated' and not their 'creation date', is there a reason why you decided to order it that way? I'll ask Jussi if that is OK for the Club Soda admin
