### ISSUE TITLE
Venues should select the brand when listing a product

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#92]
As a venue creating my listing,
I would like to filter through brands first,
So I can then find the AF / Low A drink I stock.

![image](https://user-images.githubusercontent.com/4185328/47019259-8db67780-d14e-11e8-878e-e043b9a9e5c7.png)
![image](https://user-images.githubusercontent.com/4185328/47019281-9c049380-d14e-11e8-85cd-d0eafd69c000.png)

**Acceptance Criteria**
- [x] I should be able to search for a brand within the category I selected
- [x] I should be able to select a brand and see the products they stock
- [x] I should be able to select the product and add it to my stocklist
- [x] I should be able to remove the product from my stocklist
- [x] I should see a CTA asking me if there is a brand / product not listed. Clicking this should open an email to jussi@joinclubsoda.co.uk
~- [ ] I should be able to navigate back to the earlier steps if I need to update the drink type / category~
~- [ ] I should be invited to add another drink once I've selected one~
- [x]  I should be able to submit my stocklist

Following on from this I should receive my Club Soda Score #61 

@iteles @nelsonic [here](https://airtable.com/invite/l?inviteId=invg9ybGSvLlwj3tw&inviteToken=bd5828e176694a2edc176992c7145ca75d4a6a64b7be7a5fb509f9b30fb1ac88) is a link to our current brand / product data.

**Comment by nelsonic** [comment]
@ctrembath thanks for sharing link to the sample product data. https://airtable.com/tblba43O2Om1RRqJL/viwZEVEIJIqnBZuZX
![image](https://user-images.githubusercontent.com/194400/45387542-44827d80-b60e-11e8-8de5-c12cd355646a.png)

Looks good. 
Especially insightful to know that a product can be "tagged" as multiple `types`:
![club-soda-products-multiple-categories](https://user-images.githubusercontent.com/194400/45387675-a8a54180-b60e-11e8-865c-700b8334cebc.png)

**Comment by iteles** [comment]
During our sprint 2 planning session, this was slightly altered. 
It was agreed with @jussi-club-soda and Laura that we would _simplify_ the filtering for our starting point for user testing.

We will begin by filtering only for brands, removing the first two screens from the sequence in the top comment.

**Comment by iteles** [comment]
Adding time estimate for the final point:
> I should see a CTA asking me if there is a brand / product not listed. Clicking this should open an email to jussi@joinclubsoda.co.uk

**Comment by jussi-club-soda** [comment]
This seems to be all done and working fine now
