### ISSUE TITLE
What are the primary content types?

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#94]
Moved these questions from @nelsonic to their own issue from https://github.com/club-soda/club-soda-guide/issues/5#issuecomment-422048098 so that we are able to discuss each topic separately:

## 2. Content?  

2. **What** are the primary content types we want to store for the project _and_: 

  2.a ***Who*** is going to _input_ the data for each content type. 
    i. will content be _initially_ created by club-soda "core" team and then updated/maintained by the Venues/Brands?
    ii. Is there already a **workflow** (_preferably diagram_) illustrating how content is created/updated. If not, can we _create/define_ one?
    iii. what are the "***challenges***" to making content editable/maintainable by the stakeholders who benefit the _most_ from keeping it fresh/relevant?
  2.b **What** (micro)format do we want to display the content in to maximise it's usefulness 
  both to the target _end-users_ and search-engines.
  2.c **How** will the content be kept "_fresh_" (_relevant_) so that search engine spiders 
  give it a higher ranking than _competing_ content?

**Comment by jussi-club-soda** [comment]
1) Venues - name, address, geolocation, social media handles, website URL, opening hours, description, images, phone number, email address (public), **drinks served**. Creation: either by Club Soda (manually or bulk upload) or by owner/manager manually. Maintenance/editing: owner/manager or Club Soda admins. Creating these listings should be as easy as possible for the owners/managers (get most important info first! make sure we grab email even if they don't complete full signup process!). Could be large numbers (thousands), ideally information would be updated regularly or some "live" content added (though this could just come from their social media feeds?).

2) Drinks - brand name, product name(s) and for each product: ABV, vegan?, gluten-free?, description (long and short version), social media handles, website URL, link to "where to buy" info on brand's own website, paid member of Club Soda?, "recommended drink"?, similar/related products, which venues served in, shops/online shops sold in, wholesale companies available from, .... Creation: either by Club Soda (manually or bulk upload) or by owner/manager manually. Maintenance/editing: owner/manager or Club Soda admins. Smaller numbers (hundreds), less regular need for updates.

3) Static content - pages: FAQ, About, Contact, links to other Club Soda sites/email list/venue nomination form/social media, possibly also articles/blog/events. Input by Club Soda

4) Venue managers - name, email address, linked venue(s) - not public!

For 1 and 2 need to make sure search engines can read and index venue listing/drink profile pages. Consider SEO in page designs, set up automated xml sitemap creation?
