### ISSUE TITLE
Most effective data storage for content types

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#96]
Moved these questions from @nelsonic to their own issue from https://github.com/club-soda/club-soda-guide/issues/5#issuecomment-422048098 so that we are able to discuss each topic separately.

> This is a question for the dwyl team to answer once we have answers from @jussi-club-soda and @ctrembath for #94 

## 4. Data Storage? https://github.com/club-soda/club-soda-guide/issues/85 (Database Setup)

4.  **What** is the most _effective_ way of _storing_ each content type?
  e.g: is a Document Database best? or a ("traditional") _Relational_ Database?
  do we need "flexibility" or "consistency"?

https://www.getthedata.com/open-pubs >> [open_pubs.csv.zip](https://github.com/club-soda/club-soda-guide/files/2386426/open_pubs.csv.zip) (Sample) Last update: August 2018

**Comment by nelsonic** [comment]
This issue has been answered by the fact that we are using Phoenix (_our "standard stack"_) which uses PostgreSQL (_a relational database_). All data is stored in a relational way using an append-only log for _full_ history of all records. 

Any further questions related to the database/storage/schema should be opened as separate/specific (new) issues.

Thanks. :sparkles:
